### ISSUE TITLE
Websocket bad frameformat which throws Echo off

### ISSUE THREAD

**Issue by JapSeyz** [tlaverdure/laravel-echo-server#108]
Hey, I can not for the life of me get Echo to see my Events.
I see it just fine in the Echo-Server DevMode console, and I can connect the two without a problem, but No Events ever show up.

I looked at the Websocket frames, and I saw that the format is quite a bit different from what I usually get back from something like Pusher.

### Pusher
```bash
{"event":"App\\Events\\Question","data":"{yada-yada}","channel":"game"}
```

###  Echo-Server
```bash
42["PhaseCreated","Game",{yada-yada}]
```

Am I missing some kind of setup?

**Comment by JapSeyz** [comment]
Never mind, putting a dot in front of the Event to listen for, fixed it.

Thanks,
https://github.com/tlaverdure/laravel-echo-server/issues/73#issuecomment-258433496

**Comment by barryvdh** [comment]
Are you using 'listen' or 'on'? One of those formats the event.

**Comment by JapSeyz** [comment]
I am using .listen, but as soon as I put a period in front of the Event, it worked.

It was a namespacing issue with Laravels BroadcastAs and Echo.

Since you normally add App/Events/.... to the listen command, I assumed that it would look for the BroadcastAs name in the global namespace, but apparently not so.
