### ISSUE TITLE
Rename authHost setting in order to fix ambiguity

### ISSUE THREAD

**Issue by kkomelin** [tlaverdure/laravel-echo-server#111]
## Problem/Motivation

I noticed that many people (e.g [this case](https://github.com/tlaverdure/laravel-echo-server/issues/35#issuecomment-273956490)) including myself had issues with Laravel Echo Server configuration caused by some ambiguity of the **"authHost"** setting name.

It is not clear that we should set the absolute url of our Laravel app in the **"authHost"** setting, especially if the **"host"** requires us a hostname.

## Proposed Resolution

Fix this ambiguity by renaming **"authHost"** to something like **"authAppUrl"** to refer to the **app.url** Laravel setting. You may come up with a better name.

**Comment by barryvdh** [comment]
I agree it's confusing, changed the default values in init to indicate that here,; https://github.com/tlaverdure/laravel-echo-server/pull/110

We could also verify the options on boot and give proper messages.

**Comment by kkomelin** [comment]
Thanks @barryvdh. I think it's a step in the right direction.

**Comment by barryvdh** [comment]
I'm also not sure, should authHost usually fall back to host? Do we even need the host at all? In most examples it's just omitted, it just listens for local connections; http://socket.io/get-started/chat/

**Comment by barryvdh** [comment]
https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback
> Begin accepting connections on the specified port and hostname. If the hostname is omitted, the server will accept connections on any IPv6 address (::) when IPv6 is available, or any IPv4 address (0.0.0.0) otherwise.

Isn't that what you would usually want?

**Comment by kkomelin** [comment]
> Do we even need the host at all?

I believe we do. The Laravel Echo Server host should be accessible from the outside and it should not be localhost, especially when the polling transport is used. I guess it can be the server IP address but a browser, as an external client, should be able to communicate with it from the outside. Please correct me if I'm wrong here.

> https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback
> Isn't that what you would usually want?

When an application grew to a point when it needs to be scaleled, we would want to separate Laravel Echo Server from the Laravel application, in other words move it to another VPS, for example. Thus, such default wouldn't probably work.

**Comment by barryvdh** [comment]
Yeah but it says `any IPv4 address (0.0.0.0) otherwise`, so it will still be available for all..
If I set my `host` option to `null`, it will still listen connections from outside.

**Comment by barryvdh** [comment]
But I do agree that that might not be the issue here, but it adds to confusion adding 2 'hosts', which can be different en have a different format.

perhaps appUrl? In reference to the `APP_URL` value?

**Comment by kkomelin** [comment]
> Yeah but it says any IPv4 address (0.0.0.0) otherwise, so it will still be available for all..
Interesting. If it works this way, I would remove host option completely or make it optional (only for cases where the network structure is complex).

> perhaps appUrl? In reference to the APP_URL value?
Yes. Some more ideas:
laravelAppUrl
authAppUrl (to correspond with authEndpoint)
Or even better - include authHost into authEndpoint, so that it would be http://example.com/broadcasting/auth
and then remove authEndpoint. It depends on how the authHost is used inside (I didn't check it out).

**Comment by barryvdh** [comment]
This is the only actual place it's used: https://github.com/tlaverdure/laravel-echo-server/blob/6d83f1817749082b3514bf17c0d4ab4ca3194aec/src/channels/private-channel.ts#L29
So you don't need to extract it.

But `broadcasting/auth` is probably always the url, so might not be really needed to always configure that.

**Comment by kkomelin** [comment]
It's great news. We don't need authHost and we can get server IP address on the fly (or use 0.0.0.0) and concatenate it with "broadcasting/auth" ourselves in the echo server code, so that the authEndpoint becomes a totally optional setting, which is a great usability improvement. More like convention over configuration.

**Comment by barryvdh** [comment]
Huh, you would still need the authHost option, right? Or should we just use the referrer from the application?

**Comment by kkomelin** [comment]
> Huh, you would still need the authHost option, right? Or should we just use the referrer from the application?

If we can be sure that the referrer is always set properly then we can remove authHost setting and obtain it from referrer. On the other hand, we need to be prepared for a custom auth route.

**Comment by barryvdh** [comment]
So not the referrer, but the Origins header is set for cross-origin (which is usually the case).

We could also include it client-side, when we update laravel-echo

**Comment by kkomelin** [comment]
Yeah, there can be a few ways to achieve what we need. It's up to you and other commiters/maintainers. The good thing is that the Laravel Echo Server is improving. Thanks for listening to users' feedback.

**Comment by barryvdh** [comment]
You do realise that I'm also just a contributor, not a maintainer? ;)
I think @tlaverdure is the only maintainer.

**Comment by tlaverdure** [comment]
@barryvdh your help has been very appreciated! I'm listening in on this issue and see where the improvements can be made. I'll check out that PR when I get a chance.

**Comment by kkomelin** [comment]
> You do realise that I'm also just a contributor, not a maintainer? ;)
No, I didn't ) You're so active in the issue queue that I supposed you're a maintainer. Anyway, thank you for helping me.

**Comment by kkomelin** [comment]
> I'm listening in on this issue and see where the improvements can be made. I'll check out that PR when I get a chance.

@tlaverdure Thanks.

**Comment by barryvdh** [comment]
@tlaverdure what do you think about this:

 - in laravel/echo, as `window.location.origin` to the data here, https://github.com/laravel/echo/blob/861ebea42121500b73300c4487d2167f4cdbd529/src/channel/socketio-channel.ts#L68
```js
subscribe(): any {
	this.socket.emit('subscribe', {
		channel: this.name,
		auth: this.options.auth || {},
		authEndpoint: this.options.authEndpoint,
		origin: window.location.origin
	});
}
```
(Note that authEndpoint already exists in laravel/echo, with default '/broadcasting/auth`; https://github.com/laravel/echo/blob/b618e53d1c98fcf4cd68819a2aaf960b47350dde/src/connector/connector.ts#L14 )

We could now default our `authHost` + `authEndpoint` options to `null` and instead use the options from `subscribe` when null (but allow override).

```
let options = {
	url: (this.options.authHost || data.origin) + (this.options.authEndpoint || data.authEndpoint),
	form: { channel_name: data.channel },
	headers: (data.auth && data.auth.headers) ? data.auth.headers : {},
	rejectUnauthorized: false
};
```

This would:
 - Allow zero-config for auth endpoint by default
 - Allow client-side endpoint changes
 - Allow server-side override options when needed.

**Comment by barryvdh** [comment]
Wait, nevermind. You can't allow the client to set the auth directly, because then they can use their own server to validate it :P

**Comment by barryvdh** [comment]
I guess Pusher solves this by returning a signature in the authentication process, which the echo-server can validate, which seems like a good idea. But wouldn't be zero config.

**Comment by tlaverdure** [comment]
I think we that we may just need to clarify when `authHost` should be used. 

The initial intent was to allow you to set a different location for authentication if the domain where you are are running the server as in `host` is different than the domain used to authenticate users, as in `authHost`. That being said, if everything were kept as is, and we removed the prompt to set the authHost during init, I think it would clear up confusion.

Here is a good place to see where that logic is followed.
https://github.com/tlaverdure/laravel-echo-server/blob/891e006e62a3a645fe1147f7222332afb39e74e7/src/channels/private-channel.ts#L43

authHost is not necessary.

**Comment by barryvdh** [comment]
But the `host` is usually the local IP-address of the server, right? And authHost should be the full host, including http/https.
It might be my setup, but I can't start the server with the full address. I CAN on my local valet server, as the host just maps back to 127.0.0.1.

What do you think about removing `host` instead, and defaulting that to `null`?

**Comment by kkomelin** [comment]
Besides, I think we should make sure that if we use "protocol": "https" it will also request the auth host through https by default.

**Comment by barryvdh** [comment]
So I did some more reading, pretty sure you usually want to bind on all addresses, so 0.0.0.0 (when host is null); http://stackoverflow.com/questions/2919068/what-host-do-i-have-to-bind-a-listening-socket-to
So just authHost is the only host you want to configure most of the time.

**Comment by jonnywilliamson** [comment]
@barryvdh I've not been able to reply to this for a few weeks due being away.

Thank you for helping to clarify the issue I've been having for ages https://github.com/tlaverdure/laravel-echo-server/issues/33

When the echo-server binds to `127.0.0.1` it's a disaster! We absolutely want to bind on all addresses `(0.0.0.0)` but there was definitely a change from around version 0.9 --> 1.0 where the echo-server went from defaulting to `0.0.0.0` to `127.0.0.1` which caused me hours of debugging work!

Anything you do to negate the confusion/messing about is a big thumbs up from me.

**Comment by tlaverdure** [comment]
I'm not sure if this is still an issue but I'm going to close.
