### ISSUE TITLE
Is it possible to emit events from the laravel-echo-server ?

### ISSUE THREAD

**Issue by xscence** [tlaverdure/laravel-echo-server#112]
Im trying to make some "BOT" and im wondering if laravel-echo-server can emit events? Or i should make http requests to the broadcaster ? Thanks

**Comment by barryvdh** [comment]
It emits events indeed, which you pass to the broadcaster. Or do you want to send events back?

**Comment by xscence** [comment]
Yes. I want to do something similar to: https://github.com/chadn/trivia-game/blob/master/server.js and i'm wondering if laravel-echo-server can do the trick. Basically what im trying to do is i want to make a chat with a bot in it. The bot will send some questions and the users will answer them. Any idea how this could be done with laravel-echo-server and laravel ? Thank you people.

**Comment by xscence** [comment]
So basically you CAN NOT emit events from the server to the client right (I'm talking about custom events) if so... well that sux. Whould be great if that can be done in the future.

**Comment by barryvdh** [comment]
You can, that's the entire purpose of this server.

**Comment by xscence** [comment]
Can you give me an example how can i do it with laravel-echo-server ?

**Comment by xscence** [comment]
I've found the way how to do it. It takes me around 1 day to figure this out, because there is no tutorials and such things in the internet. It would be very very great if this could be documented in the laravel-echo-server. Basically you have to import the laravel-echo-server and start the server in node command line.
```
echo.server.io.on('connect', function(){});
echo.server.io.emit();
```

**Comment by Wiejeben** [comment]
@lostncg I believe you are looking for `window.Echo.connector.socket.emit` when using Socket.IO?

**Comment by babarsalehhayat** [comment]
@barryvdh how can I send events back to ```laravel-echo-server```? how to send data from client to server like we emit in socket.io from client and listen on nodejs server.
if I emit using this ```window.Echo.connector.socket.emit``` how to listen on it in ```laravel-echo-server```???

**Comment by Thihasoehlaing** [comment]
@babarsalehhayat did you found a way? I'm still searching but it doesn't work.
