### ISSUE TITLE
data event don't work

### ISSUE THREAD

**Issue by argb** [tlaverdure/laravel-echo-server#115]
SyntaxError: Unexpected end of input

the data event don't work, so the var body is empty, then JSON.parse get errors described as above.

**Comment by barryvdh** [comment]
What are you doing? Sending a message with Redis?

Can you show some code?

Also, you can run with `DEBUG=* laravel-echo-server` to show more logging on the server.

**Comment by argb** [comment]
I found the problem, if just send a request like this: http://localhost:6001/apps/e8b6c7fa167533bc/events?auth_key=2522b45f3d9435c1c80f706420052b86
without any data posted, the data event won't be triggered, it will get that error, because the body variable is an empty array, which will trigger JSON.parse error, then the whole service crashed.

I think it should have some fault tolerance abilities, not lead to crash the whole process.

**Comment by barryvdh** [comment]
Can you show the php code for the event? And I assume this is the pusher subscriber?
