### ISSUE TITLE
Not receiving event in Laravel Echo channel listener

### ISSUE THREAD

**Issue by tijme** [tlaverdure/laravel-echo-server#116]
Hi there,

I'm trying to setup Laravel + Redis + LaravelEchoServer. So far, I've got Laravel, Redis and the LaravelEchoServer setup. I can see the messages going to Redis and to LaravelEchoServer (printscreens below).

But the last step, logging the event in my browser console is not working.

**Laravel Echo Server config:**

    {
        "appKey": "base64:somethingsecret123",
        "authHost": "http://test.virtual",
        "authEndpoint": "/broadcasting/auth",
        "clients": [
            {
                "appId": "TEST",
                "key": "AAAAABBBBBBCCCCCDDDDD"
            }
        ],
        "database": "redis",
        "databaseConfig": {
            "redis" : {
                "port": "6379",
                "host": "test.virtual"
            },
            "sqlite": {
                "databasePath": "/database/laravel-echo-server.sqlite"
            }
        },
        "devMode": true,
        "host": "127.0.0.1",
        "port": "6001",
        "protocol": "http",
        "socketio": {},
        "sslCertPath": "",
        "sslKeyPath": ""
    }

**My JavaScript:**

    import Echo from "laravel-echo"

    window.Echo = new Echo({
        broadcaster: 'socket.io',
        host: 'http://127.0.0.1:6001/',
        auth: {
            headers: {
                'Authorization': 'Bearer ' + 'AAAAABBBBBBCCCCCDDDDD'
            }
        }
    });

    window.Echo.channel('examplec')
        .listen('examplee', (e) => {
            console.log('Got event...');
            console.log(e);
        });

**My example event:**

    namespace App\Events;

    use Illuminate\Broadcasting\Channel;
    use Illuminate\Queue\SerializesModels;
    use Illuminate\Broadcasting\PrivateChannel;
    use Illuminate\Broadcasting\PresenceChannel;
    use Illuminate\Broadcasting\InteractsWithSockets;
    use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

    class ExampleEvent implements ShouldBroadcast
    {
        use InteractsWithSockets, SerializesModels;

        /**
         * The event's data
         */
        public $data = [];

        /**
         * Create a new event instance.
         *
         * @return void
         */
        public function __construct($value)
        {
            $this->data['value'] = $value;
        }

        /**
         * Get the channels the event should broadcast on.
         *
         * @return Channel|array
         */
        public function broadcastOn()
        {
            return new Channel('examplec');
        }

        /**
         * Set the event name
         *
         * @return string
         */
        public function broadcastAs() {
            return 'examplee';
        }
        
    }

**And how I trigger the event:**

    event(new ExampleEvent('this is the value'));

**Redis output (`redis-cli monitor`):**
![redis-log](https://cloud.githubusercontent.com/assets/5873573/22338735/5e23fa10-e3e8-11e6-842a-fbb422d63262.png)

**Laravel Echo Server output:**
![laravel-echo-server-log](https://cloud.githubusercontent.com/assets/5873573/22338767/70341bea-e3e8-11e6-845b-477b3d45bf3c.png)

But nothing shows up in my browser console.

Is there something I'm doing wrong? I hope you can help me out here.

Thanks in advance.

**Comment by tijme** [comment]
Ahh, just found the fix! The event name needs to be prefixed with a dot.

    window.Echo.channel('examplec')
        .listen('.examplee', (e) => {
            console.log('Got event...');
            console.log(e);
        });

Source: https://github.com/tlaverdure/laravel-echo-server/issues/73#issuecomment-258433496

**Comment by barryvdh** [comment]
Yeah not really sure why that is.

But usually they suggest to use the namespace like App.Example or something. 

Also, you shouldnt add the key to your authorisation header, thats only for the HTTP subscriber.

**Comment by tijme** [comment]
Ok, thanks!

**Comment by ErnestStaug** [comment]
Same issue here, was working before and then suddenly stopped, adding `.` before event fixes it

**Comment by MatasElectronics** [comment]
The `.` will instruct Echo to not prepend the application's namespace to the event.

[https://laravel.com/docs/5.5/broadcasting#broadcast-name](url)

**Comment by apudiu** [comment]
This should be fixed

**Comment by google-mac** [comment]
My issue (as many people above have found) is that I should use a custom broadcastWith name. If you state the event name, it is prefixed with 'App\\Events\\', but the events I was listening for were under 'App\\Events\\Dialer', which is a different namespace- hence the issue. I don't want to have to state the entire namespace every time I listen for an event, so I resorted to a custom name, prefixed with a period!

**Comment by luscas** [comment]
Install the Pusher
```bash
$ composer require pusher/pusher-php-server "~3.0"
```
Change in **.env** file
```env
BROADCAST_DRIVER=pusher
```

**Comment by wajdijurry** [comment]
> Ahh, just found the fix! The event name needs to be prefixed with a dot.
> 
> ```
> window.Echo.channel('examplec')
>     .listen('.examplee', (e) => {
>         console.log('Got event...');
>         console.log(e);
>     });
> ```
> 
> Source: [#73 (comment)](https://github.com/tlaverdure/laravel-echo-server/issues/73#issuecomment-258433496)

You saved my day!

**Comment by yousufcse06** [comment]
I am trying from react js

import Echo from 'laravel-echo';
import Socketio from 'socket.io-client';

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://127.0.0.1:6001',
    authEndpoint: '/broadcasting/auth',
    client: Socketio,
    auth: {
        headers: {
            'Authorization': `Bearer ${localStorage.getItem('logintoken')}`,
        },
    },
});


window.Echo.channel('elxorders').listen('.orderhistory', (e) => {
            console.log('okkkkkkkkkkkkkkkkkkkkkkkk');
            console.log(e);
        });
        
        After run this code from componentDidMount().
        Nothing showing. Anyone help me

**Comment by RezaHeydarii** [comment]
@aleksandrssd same here
