### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8000 Error sending authentication request. (Using Vue 2.1.0 with webpack and laravel 5.3)

### ISSUE THREAD

**Issue by devlobchannel** [tlaverdure/laravel-echo-server#117]
Any idea what causes this error?

Error: connect ECONNREFUSED 127.0.0.1:8000
Error sending authentication request.

# This is my laravel echo server json file.
{
	"authHost": "http://localhost:8000",
	"authEndpoint": "/broadcasting/auth",
	"database": "redis",
	"devMode": false,
	"host": "localhost",
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"clients": [
		{
			"appId": "APP_ID",
			"key": "my key"
		}
	]
}

This is what I have in the main file.

window.Echo = new Echo({
    broadcaster: 'socket.io',
    authEndpoint: 'http://localhost:8000/broadcasting/auth',
    host: 'localhost:6001'
})

And I have included this in my index.html file.

<script src="http://localhost:6001/socket.io/socket.io.js"></script>

This is my broadcast service provider.

Broadcast::routes();

        /*
         * Authenticate the user's personal channel...
         */
        Broadcast::channel('App.User.*', function ($user, $username) {
            return true;
        });

**Comment by barryvdh** [comment]
You don't need your authorization endpoint on the clientside. Where do you get that error?

**Comment by devlobchannel** [comment]
@barryvdh you mean the authEndpoint on window.Echo = new Echo...? Yeah I have it in the json conf of laravel echo as well, but even if I remove it, I get the same error.

I get it on the laravel echo server. I am running Laravel on XAMPP, using the artisan command.

This is one of the socket io responses.

ÿ42["subscription_error", "private-App.User.19bfe6e0-e598-11e6-b5b0-43b5043c3673", 0]
0:"subscription_error"
1:"private-App.User.19bfe6e0-e598-11e6-b5b0-43b5043c3673"
2:0

I am using uuid instead of ID.

It looks like something is wrong with the subscription.

I have a notification component and I load it on my navbar component. Whenever I refresh the page, I get that error...

**Comment by devlobchannel** [comment]
I logged some additional information, by modifying the private-channel.js file.

{ headers: 
      { host: 'localhost:6001',
        connection: 'keep-alive',
        accept: '*/*',
        origin: 'http://localhost:8080',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36',
        dnt: '1',
        referer: 'http://localhost:8080/',
        'accept-encoding': 'gzip, deflate, sdch, br',
        'accept-language': 'en-US,en;q=0.8,el;q=0.6,de;q=0.4,it;q=0.2,ru;q=0.2,sq;q=0.2',
        cookie: 'wordpress_test_cookie=WP+Cookie+check; wp-settings-time-1=1483028542; PHPSESSID=d4473llrmppsp6icfl10csvke3; Phpstorm-bb64dadb=071571e1-84fd-44c3-b741-7adebe0aa170; io=iVLoCfUY2V-ZMRIJAAAD' },
     time: 'Sun Jan 29 2017 02:56:13 GMT+0100 (CET)',
     address: '127.0.0.1',
     xdomain: true,
     secure: false,
     issued: 1485654973997,
     url: '/socket.io/?EIO=3&transport=polling&t=Lddxzuf',
     query: { EIO: '3', transport: 'polling', t: 'Lddxzuf' } },
  fns: [],
  _events: 
   { subscribe: [Function],
     unsubscribe: [Function],
     disconnecting: [Function],
     'client event': [Function] },
  _eventsCount: 4 }
{ url: 'http://localhost:8000/broadcasting/auth',
  form: { channel_name: 'private-App.User.19bfe6e0-e598-11e6-b5b0-43b5043c3673' },
  headers: {},
  rejectUnauthorized: false }
{"url":"http://localhost:8000/broadcasting/auth","form":{"channel_name":"private-App.User.19bfe6e0-e598-11e6-b5b0-43b5043c3673"},"headers":{},"rejectUnauthorized":false}
Error: connect ECONNREFUSED 127.0.0.1:8000
Error sending authentication request.

**Comment by KekoApp** [comment]
For whatever reason, it's trying to connect to port 8000, however from your posts above it looks like you're running your local web server on 8080 - perhaps a minor oversight in configuration?

**Comment by devlobchannel** [comment]
@KekoApp Laravel runs on port 8000, so I don't see how that is wrong. Vue runs on port 8080... This problem really got me... :/

**Comment by barryvdh** [comment]
So on what url are you viewing your app?

**Comment by KekoApp** [comment]
@devlobchannel Unless you're doing something with multiple web servers that you haven't mentioned Laravel and Vue will be running on the same port. Vue is just the front end, served by laravel.

**Comment by barryvdh** [comment]
With the Laravel 5.4 + mix, I think Vue is actually running on the webpack-dev-server to serve the assets while the app itself is on a different port.

**Comment by KekoApp** [comment]
That's my understanding also, but he's mentioned in the title he's on 5.3 which has thrown me on diagnosing the problem, outside of what's already been suggested

**Comment by tlaverdure** [comment]
Closing this issue. Please follow up if there something that needs to be addressed in the project.
