### ISSUE TITLE
No such file or directory -  (Errno::ENOENT)

### ISSUE THREAD

**Issue by avireddyn** [tlaverdure/laravel-echo-server#118]
While running the test I'm getting below error. It does not mention which file is missing. Thanks in Advance

C:\Ruby22-x64\bin\ruby.exe -EUTF-8 -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:\Ruby22-x64\bin/cucumber "C:/Users/xxxx/RubymineProjects/ePowerCenter/features/login and create new case.feature" --format Teamcity::Cucumber::Formatter --expand --name "^Validate that the user is logged into ePowerCenter$" --color -r features
Testing started at 11:19 AM ...
No such file or directory -  (Errno::ENOENT)

Process finished with exit code 2

**Comment by tlaverdure** [comment]
I'm not sure what test you are running as this package doesn't have any yet. If there is an issue please follow up with more details. Thanks
