### ISSUE TITLE
The server provider does not allow you to run PHP files

### ISSUE THREAD

**Issue by vertisan** [tlaverdure/laravel-echo-server#12]
Hello,
I would like to start the server using Socket.io, but my provider in the public directory only allows you to run static files - if I want to start Node Application (they are using Passenger).
Is there any possibility to run the application on this server or some way of passing through by node.js PHP file?

**Comment by tlaverdure** [comment]
You will need a host that provides full shell access. I suggest [DigitalOcean](https://www.digitalocean.com/).
