### ISSUE TITLE
Correct way getting server status

### ISSUE THREAD

**Issue by Cannonb4ll** [tlaverdure/laravel-echo-server#120]
I have searched everywhere how I could solve this. I have a administration panel where I want to display wether the socket connection is live yes/no.

Whats the best way about going to solve this?

**Comment by barryvdh** [comment]
You can use the HTTP API, if you add a client:
https://github.com/tlaverdure/laravel-echo-server#http-api

**Comment by Cannonb4ll** [comment]
How would I use that? Are those AJAX calls? I know the original socket had like:

```
   socket.on('disconnect', function() {

   });
```

**Comment by barryvdh** [comment]
No server side calls, use guzzle for example.

**Comment by Cannonb4ll** [comment]
Alright, thanks.
