### ISSUE TITLE
Laravel 5.4 & 5.3 fresh installation issue

### ISSUE THREAD

**Issue by d-pollard** [tlaverdure/laravel-echo-server#121]
I recently upgraded to laravel 5.4 and when I try to load a page, I get the following error:

```
L A R A V E L  E C H O  S E R V E R

version 1.2.4

⚠ Starting server in DEV mode...

✔  Running at heroes.derek.app on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

[10:13:57 PM] - JdcgyEqh9AWXkv4rAAAA authenticated for: private-App.Notify.1
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/usr/lib/node_modules/laravel-echo-server/dist/channels/private-channel.js:45:34)
    at Request.self.callback (/usr/lib/node_modules/laravel-echo-server/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

Please help, I have done tons of googleing and gotten nowhere. Has anyone else experienced this issue?

**Comment by tlaverdure** [comment]
There is a probably a problem with your Laravel application.

Can you `POST` to the authentication endpoint `/broadcasting/auth`?

**Comment by dpollard** [comment]
@tlaverdure the response back from the server when `laravel-echo-server` posts all the data is a 200 response with an empty body. I can post that response output if you'd like?

**Comment by barryvdh** [comment]
Is it private or presence? 
Presence expects an array with info like user ID and name.

**Comment by d-pollard** [comment]
It is a private channel I am attempting to access. I'm using `Echo.private()`

**Comment by d-pollard** [comment]
Here is a screenshot of me `POST`ing with vue: 
![selection_015](https://cloud.githubusercontent.com/assets/16292606/22604219/249fac84-ea10-11e6-8663-627fa5d68198.png)

**Comment by d-pollard** [comment]
But again, the response is blank.

**Comment by barryvdh** [comment]
What does your broadcast check look like for that channel, are you returning true? Are you sure it's called?

**Comment by d-pollard** [comment]
I am using the default broadcast check: 

```
Broadcast::channel('App.User.*', function ($user, $userId) {
        return (int) $user->id === (int) $userId;
 });
```

**Comment by d-pollard** [comment]
And I'm also getting the same error with a fresh installation of laravel 5.3

**Comment by barryvdh** [comment]
And it reaches that statement? Eg. When you add a log statement inside the check, it's triggered?

**Comment by tlaverdure** [comment]
That may be your issue,`private-App.Notify.1` and `private-App.User.1` are not the same channel. You would need  separate check for that private channel.

I would check out the section in the docs on [Authorizing Channels](https://laravel.com/docs/5.4/broadcasting#authorizing-channels)

**Comment by dpollard** [comment]
@tlaverdure neither of the channels are working, I switched to using the default to see if it made a difference

@barryvdh  - no, it doesn't reach my log message

**Comment by barryvdh** [comment]
I suggest some higher logging then, to see which request is actually sent.

**Comment by dpollard** [comment]
My BroadcastServiceProvider:
```
...
class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes();

        /*
         * Authenticate the user's personal channel...
         */
        Broadcast::channel('App.User.*', function ($user, $userId) {
            Log::info("Yes, we are here");
            return (int) $user->id === (int) $userId;
        });
    }
}
...
```

My bootstrap.js:
```
...
import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
});
```

My initiation of the code inside a vue component:
```
<template>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Example Component</div>

                    <div class="panel-body">
                        I'm an example component!
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data () {
            return {
            }
        },
        mounted() {
            this.initialMount();
        },
        methods: {
            initialMount() {
                Echo.private('App.User.' + window.Laravel.id)
                .listen('GiveNotice', (res) => {
                    console.log(res);
                });
            },
        }
    }
</script>
```

**Comment by tlaverdure** [comment]
Auth check in 5.4 also doesn't use `*` per the upgrade guide.

https://github.com/laravel/laravel/blob/master/routes/channels.php#L14

**Comment by dpollard** [comment]
Sorry, this is 5.3 now as aforementioned, and for `private` channels, it still utilizes the `*` in 5.4

**Comment by dpollard** [comment]
I tried to rollback and see if the version change was the issue and I'm still getting the same error.

**Comment by dpollard** [comment]
I can teamview if you'd like to take a look at it. It's baffled me for about 3 days now.

**Comment by barryvdh** [comment]
You;re sure you fully reverted to 5.3 (composer, compiled file, cache etc)? Did you try the alternative syntax?
I suggest logging the entire request to determine where it goes wrong and then re-try that with Postman or something.

I think it's on the Laravel side, unless the authentication url is not correctly passed.

**Comment by dpollard** [comment]
@barryvdh to be safe, I completely started with a fresh install of Laravel 5.3:

Here is the example code with a fresh installation of laravel 5.3: https://github.com/dpollard/test_laravel_echo_server

It is also productionized js, so all that needs done is a new laravel-echo-server init in the repo, if you'd like to test it out

**Comment by dpollard** [comment]
@barryvdh how would you suggest I test Laravel? I don't really know where to begin

**Comment by barryvdh** [comment]
You could add log statements in your middleware or routes files. Or something like github.com/barryvdh/laravel-debugbar and view the request with the browse button

**Comment by dpollard** [comment]
So I converted over to pusher, and got it to work with pusher. Is that indicative of anything?

**Comment by d-pollard** [comment]
Any ideas, kind of desperate...I have installed debugbar but really, the connection doesn't stay open long enough to debug anything

**Comment by scheMeZa** [comment]
Also getting this problem. 

![image](https://cloud.githubusercontent.com/assets/7773361/22718954/d8f2f15c-edab-11e6-8632-5f7b02151ee8.png)

**Comment by barryvdh** [comment]
Are you both using the Redis broadcaster? Or pusher?

**Comment by dpollard** [comment]
I am using redis

**Comment by tlaverdure** [comment]
@dpollard can you try installing 1.2.5.

This may or may not fix it, but hopefully so. https://github.com/tlaverdure/laravel-echo-server/commit/ec4277a383755d4141c72c3c9d6eb107f83c56cf

**Comment by dpollard** [comment]
Hot diggity damn, it works!
![selection_020](https://cloud.githubusercontent.com/assets/10744018/22841552/a8f13d40-ef97-11e6-9c37-939f75ee3798.png)


You guys are awesome!

**Comment by tlaverdure** [comment]
Good to hear!
