### ISSUE TITLE
->toOthers "Invalid socket ID"

### ISSUE THREAD

**Issue by menesescesar** [tlaverdure/laravel-echo-server#123]
Hello,
So i made a fresh install of Laravel 5.4.x, laravel-echo-server...
Then when i do this:
`Route::post('/messages', function () {
$user = Auth::user();
$message = $user->messages()->create([
'message' => request()->get('message')
]);
 broadcast(new MessagePosted($message, $user));
return ['status' => 'OK'];
})->middleware('auth');`

Everything goes well. All connected clients receive the message!
But if i change to:
`broadcast(new MessagePosted($message, $user))->toOthers();`

this happens:
![image](https://cloud.githubusercontent.com/assets/24883380/22705732/9d821ac2-ed64-11e6-83fc-b55ab8a938f6.png)

And i confirmed that was the correct socket ID
![image](https://cloud.githubusercontent.com/assets/24883380/22705756/baeea9b8-ed64-11e6-80c1-ac0454fc3194.png)

Is someone else getting this error?
Also i've tested with pusher.com, and everything works fine.

**Comment by d-pollard** [comment]
I have similar issues with both 5.4 and 5.3 - they don't seem to want to help though, sadly.

**Comment by barryvdh** [comment]
Using the pusher driver, not redis?

**Comment by barryvdh** [comment]
@d-pollard what so you mean they don't want to help? 20 comments or so within a day trying to help you :/ Remember that we also just have jobs/family etc

**Comment by menesescesar** [comment]
At the moment is not possible to configure a redis server.
So i've found the problem. In Pusher.php there is a function:
`private function validate_socket_id($socket_id)`
that validates the socket_id with: `preg_match('/\A\d+\.\d+\z/', $socket_id)`
since socket.io has a different spec a error is thrown.
So the fastest solution is to change that preg_match condition. 
A ideal solution would be installing a 'patch' on app side, so the pusher SDK is not changed.

**Comment by jonnywilliamson** [comment]
@menesescesar What is the spec for a redis socket ID name then? How does it differ to pusher?

**Comment by menesescesar** [comment]
The spec for pusher is: '{number} {dot} {number}' as you can see in preg_match. For the socket.io it seems to be a random string so i updated to: `preg_match('/\A.+\z/', $socket_id)`
Later i'll try to find a better solution.

**Comment by barryvdh** [comment]
According to the regex the Pusher spec is <1-.. numbers>.<more numbers>, so `123.456`, while the socket.io id is alphanumeric.

I don't think this is easily fixable without writing a new Http broadcaster..

**Comment by menesescesar** [comment]
Hi, 
So i found a better solution for this problem.
I added a new dependency for the laravel-echo-server:
`"randexp" : "^0.4.4"`

Then in beginning of server.js added:
`var RandExp = require('randexp').randexp;`

And changed the init function to this:
```
Server.prototype.init = function () {
        var _this = this;
        return new Promise(function (resolve, reject) {
            _this.serverProtocol().then(function () {
                var host = _this.options.host || 'localhost';
                log_1.Log.success("Running at " + host + " on port " + _this.options.port);
                resolve(_this.io);
                _this.io.eio.generateId = function () {
                    var socketIdSpec = _this.options.socketIdSpec || '([a-zA-Z0-9]{15})';
                    return RandExp(socketIdSpec);
                };
            }, function (error) { return reject(error); });
        });
    };
```

In config file (laravel-echo-server.json) added a new option:
`"socketIdSpec":"([0-9]{5})[.]([0-9]{5})"`

So now whenever a new client connects the socketId will be `<numbers>.<numbers>`
With this solution there is no need to change the Pusher.php

Does it makes sense to add this improvement to the master branch so other users can use it as well?

**Comment by barryvdh** [comment]
I guess it is officially supported to do something like that:

https://github.com/socketio/engine.io#server-2
> **generateId**
>Generate a socket id.
>
>Overwrite this method to generate your custom socket id.
>Parameters
> - http.IncomingMessage: a node request object
>
>Returns A socket id for connected client.

But not sure it makes sense to set a custom format. Imho if we want to add that, we should just change the id for everyone to match Pusher.

**Comment by barryvdh** [comment]
And could also just use the crypto function for this; `var id = parseInt(crypto.randomBytes(6).toString('hex'), 16) / 1e8;`

**Comment by menesescesar** [comment]
@barryvdh Yes you are right. I just added the custom format so it was possible to wtv is needed.
I'll close since problem has been solved.
Thanks

**Comment by yohang88** [comment]
are there any solutions without rewrite/modify directly on `laravel-echo-server` app ? Maybe it should configurable in options?

**Comment by ano95** [comment]
Any updates on this? :worried:

**Comment by eldiddio** [comment]
Hi,

I have this problem on Laravel 5.6 when using ->toOthers(); with the pusher driver.

Do you have a supported workaround?

Thanks

**Comment by rolandstarke** [comment]
Hi,

a workaround for me is monkey patching the pusher library to allow ids from socket.io.

in App\Providers\ServiceProvider.php i added this to the end of the file.
```php
// fix broadcast()->toOthers "Invalid socket ID"
namespace Pusher;

function preg_match($pattern, $subject, &$matches = null, $flags = 0, $offset = 0)
{
    if ($pattern === '/\A\d+\.\d+\z/') {
        $pattern = '/[\w.]+/';
    }
    return \preg_match($pattern, $subject, $matches, $flags, $offset);
}
```

It overwrites the this preg_match call: https://github.com/pusher/pusher-http-php/blob/97023bae8a3734d6439e43efba416b1d52aac2e5/src/Pusher.php#L292

I also thought about extending the pusher lib... but `validate_socket_id` is a private method... so nah...

**Comment by allawitte** [comment]
I had also yesterday the same issue, the point was BROADCAST_DRIVER=pusher in .env, when I thought I use redis. I just forgot to change settings from an earlier version. 

To change preg_match pattern it brought to another pusher  error: not authorised.

**Comment by rauschmerscen** [comment]
> At the end of the App\Providers\ServiceProvider.php file I added:
> 
> ```
> // fix broadcast()->toOthers "Invalid socket ID"
> namespace Pusher;
> 
> function preg_match($pattern, $subject, &$matches = null, $flags = 0, $offset = 0)
> {
>     if ($pattern === '/\A\d+\.\d+\z/') {
>         $pattern = '/[\w.]+/';
>     }
>     return \preg_match($pattern, $subject, $matches, $flags, $offset);
> }
> ```

I added this code to the end of App\Providers\AppServiceProvider.php & it worked. 
I don't know how but it does override 'preg_match' of Pusher.
@rolandstarke  Thanks for the quick solution.
