### ISSUE TITLE
Run as a dameon

### ISSUE THREAD

**Issue by CowboyDiplomacy** [tlaverdure/laravel-echo-server#126]
Is their currently a way to run the server as a daemon in the background? It seems like this should be an option when starting the server.

**Comment by tlaverdure** [comment]
Not at this point. You'll need to use something like [supervisor](url) to run as a daemon.

**Comment by jonnywilliamson** [comment]
I believe that PM2 is also used to monitor and control node apps. I'm going to have a look into it in the next few days

http://pm2.keymetrics.io/

**Comment by CowboyDiplomacy** [comment]
I actually cloned laravel-echo-server this morning thinking about implementing the forever module :). I'd love to hear about what you find.

**Comment by CowboyDiplomacy** [comment]
It might not be done until tomorrow, but I just forked it and am working on it. CLi has been updated and the forever module has been installed.
