### ISSUE TITLE
Whisper not implemented?

### ISSUE THREAD

**Issue by Luppakorva** [tlaverdure/laravel-echo-server#127]
I'm not sure am I doing something wrong here but when I try to load up whisper:

Echo.channel('chat')
    .whisper('typing', {
        name: username
    });

I get:

Uncaught TypeError: Echo.channel(...).whisper is not a function

listenForWhisper seems to work though (at least doesn't give me an error).

**Comment by barryvdh** [comment]
Do you have the latest version? Should be implemented client-side

**Comment by Luppakorva** [comment]
@barryvdh 

Yep, running the latest version. It seems to work on private channel though, 

Echo.private('chat').whisper('chat',{name: ' is typing...'});   

Perhaps it's not implemented to channel but only to private?

**Comment by barryvdh** [comment]
Yes whisper is for private and persistence only

**Comment by Luppakorva** [comment]
Ok, that explains. Thanks @barryvdh!

**Comment by Dayjo** [comment]
Docs still need to be updated; https://laravel.com/docs/5.5/broadcasting#client-events
