### ISSUE TITLE
Use .here() on a private channel.

### ISSUE THREAD

**Issue by andrew-za** [tlaverdure/laravel-echo-server#131]
So the demo on https://laracasts.com/lessons/introducing-laravel-echo shows you how to use the .here() when joining a public channel but when it does not work when using it on a private channel.

Error is: 
`Echo.private(...).here is not a function`

**Comment by andrew-za** [comment]
So i discovered that you need to also join a Presence channel alongside the private channel in order to use the here() etc methids

**Comment by tinpont** [comment]
Use presence channel instead of private channel, not both of them.

**Comment by tlaverdure** [comment]
`here()` should be used on presence channels. The docs outline it here:
https://laravel.com/docs/5.4/broadcasting#presence-channels 

Hopefully that helps.
