### ISSUE TITLE
Do not use socket.io library from Laravel Echo Server directly

### ISSUE THREAD

**Issue by kkomelin** [tlaverdure/laravel-echo-server#132]
Laravel Echo Server can become a single point of failure for the entire Laravel app if we include socket.io lib as described in [the official Laravel documentation](https://laravel.com/docs/5.4/broadcasting#driver-prerequisites):

```html
<script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>
```

In other words, if Laravel Echo Server stops working, then all JS code of the app stops functioning with the following error:

> Uncaught ReferenceError: io is not defined

I explained the problem in detail and suggested a couple of solutions in [my post](https://komelin.com/articles/realtime-apps-laravel-echo-tips-and-tricks#laravel-echo-server-fails).

**Comment by kkomelin** [comment]
@tlaverdure Why?

**Comment by tlaverdure** [comment]
@kkomelin what are you proposing? Seem's like you are just stating that you should check if the `io` variable is defined before subscribing. Is there anything to do?

**Comment by kkomelin** [comment]
> @kkomelin what are you proposing? Seem's like you are just stating that you should check if the io variable is defined before subscribing. Is there anything to do?

I'm informing you and other users about a serious issue that can be caused by improper use of your project 's feature (socket.io lib). Especially if this improper use is recommended in the official Laravel documentation.

You may think that the problem is trivial and any user can find and fix it themselves, but I don't think so. Therefore, I would propose at least adding a note about this issue to the Laravel Echo Server docs to warn users.

**Comment by tlaverdure** [comment]
Ok will do so.

**Comment by kkomelin** [comment]
@tlaverdure Thank you.

**Comment by barryvdh** [comment]
Responded here; https://github.com/laravel/docs/issues/3173

**Comment by aftabnaveed** [comment]
When I import io through Es6 `import io from 'socket.io-client'`  Laravel echo is not able to find the io object? Do I have to explicitly include the script.io.js file? I don't want to have any external dependencies in my frontend app.

**Comment by kkomelin** [comment]
@aftabnaveed Please see the code snippet https://github.com/laravel/docs/issues/3173#issuecomment-284708455
