### ISSUE TITLE
if echo-server stopped

### ISSUE THREAD

**Issue by xralphack** [tlaverdure/laravel-echo-server#134]
Once the echo-server stop, the rest of my js would not work

error in console

:6001/socket.io/socket.io.js net::ERR_CONNECTION_REFUSED

Uncaught ReferenceError: io is not defined

Anything advise to avoid this situation if echo-server not working, the rest of functionality should work.

**Comment by tlaverdure** [comment]
Hey @xralphack in the laravel echo options you can set how many times to attempt reconnection. These will be based to the socket.io client [Manager](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#manager)

``` js
new Echo({
    reconnectionAttempts: 1
});
```

Let me know if this solves the problem. Thanks

**Comment by barryvdh** [comment]
See https://github.com/laravel/docs/issues/3173

**Comment by xralphack** [comment]
@tlaverdure the way you suggested can not work, because if the problem I met is if the echo-server stop my client side can not get socket.io.js. So everything after that will crash. 

@barryvdh According to the reference

`window.io = require('socket.io-client');`

works fine, thanks ~
