### ISSUE TITLE
Keep track of users in channel

### ISSUE THREAD

**Issue by meijdenmedia** [tlaverdure/laravel-echo-server#137]
In my application all users who are logged in automatically connect to laravel-echo-server.

```
window.Echo.private('notification.{{ $user->id }}')
            .listen('NotificationEvent', function(e) {
                alert('new calendar event!');
            });
```

I have a cronjob which checks my database for notifications. When the timestamp for a notification is in the past Laravel throws an Event which broadcasts to the "notification.x" channel.

```
foreach($events as $event) {
    event(new NotificationEvent($event));
    $event->update(['reminder_sent' => true]);
}
```

The problem is that when the user is not connected to the websocket Laravel still sents the event to the channel. The user never receives the event.

Is there any way for the Laravel application to know if the user is in the channel or if the channel exists?

If that's impossible I could try save to the database when a user joins a channel via the Routes.

```
Broadcast::channel('notifcation.*', function ($user, $event_user_id) {
    // write to database that $user->id is connected
    
    return (int) $user->id === (int) $event_user_id;
});
```

But how do I remove the user from the database when he/she disconnects?

**Comment by tlaverdure** [comment]
Not sure what you are trying to accomplish.

**Comment by meijdenmedia** [comment]
I changed my initial post, I hope it is more clear now.

**Comment by tlaverdure** [comment]
Sounds like you are trying to rebroadcast a real-time notification. Why not just display unread notifications to the user when they come back to your app and mark them as read once seen?

Anyways, you can also try utilizing presence channels.  Users are stored in redis or sqlite based on your your database selection in the config. You can access those though the key `CHANNEL_NAME:members`.

The [HTTP API](https://github.com/tlaverdure/laravel-echo-server#http-api) also exposes an endpoint to get channels users.

**Comment by tlaverdure** [comment]
Closing this now.
