### ISSUE TITLE
Using this with homestead

### ISSUE THREAD

**Issue by edstevo** [tlaverdure/laravel-echo-server#14]
Hi guys, 

Great work on this! I've just managed to get my head around it and once again the Laravel community has outdone itself.

I just wanted to point something out for anyone starting out with this package, which wasn't immediately clear to me.

I had issues getting this to work with presence channels.  When authenticating user against the channel, it was throwing a 404 error for the /broadcasting/auth route.  Digging in, I found that the default authHost was http://localhost, which makes sense, but this wasn't the correct address for my laravel app via homestead.

When I specified the "authHost" in "server.js" with what was configured in homestead (e.g. 'http://app.dev'), then this worked fine.

This may be obvious to some, but I spent a few hours trying to crack this one!

Otherwise, thank you very much for your efforts!

**Comment by tlaverdure** [comment]
Thanks for this very useful feedback. I'll be working on better documentation and a setup process for version 1.0. I'll keep this open and when we get there you can check it out.

**Comment by edstevo** [comment]
No problem! I assumed it was an optional config, which it still could be, but for me in this case, I had to specify the authHost address.

Thanks again.
