### ISSUE TITLE
API CORS problem

### ISSUE THREAD

**Issue by flamisz** [tlaverdure/laravel-echo-server#141]
I use axios to call the API, but I run into CORS problem (and I tried jquery, same problem):
```
XMLHttpRequest cannot load http://echo.app:6001/apps/d6507f699e3c05cb/channels/anon.
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://echo.app' is therefore not allowed access.
```
I fixed it by editing the the `dist/api/http-api.js` by adding header information to the `express`:
```
this.express.use(function(req, res, next) {
                res.header('Access-Control-Allow-Origin', '*');
                res.header('Access-Control-Allow-Methods', 'GET, POST, PATCH, PUT, DELETE, OPTIONS');
                res.header('Access-Control-Allow-Headers', 'Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id');
                next();
        });
```

I don't if there is a simpler solution for this. But if not, maybe it could be a settings parameter to add extra header?
Thanks.

**Comment by okaufmann** [comment]
This works for me. Can you make a PR ?

**Comment by flamisz** [comment]
Sure, just give me some time. But I think I can work on it in a few weeks.

**Comment by skatetdieu** [comment]
Hi @flamisz and @okaufmann, 

I just made a pull request for this implementing your solution but also making settings based on the settings JSON file. Here is the pull request:

https://github.com/tlaverdure/laravel-echo-server/pull/216

**Comment by okaufmann** [comment]
Thank you, looks good!

**Comment by nguyenhaiphan** [comment]
@tlaverdure  @skatetdieu can this solve the problem I have just got?

```
Failed to load https://<real-domain>:<socket-port>/socket.io/?EIO=3&transport=polling&t=LvqOBEm: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://<real-domain>' is therefore not allowed access. The response had HTTP status code 522.
```

**Comment by flamisz** [comment]
Ok, thanks, I just close this issue then.
