### ISSUE TITLE
Nativescript Error 'ReferenceError: window is not defined'

### ISSUE THREAD

**Issue by Skintillion** [tlaverdure/laravel-echo-server#143]
Below is an error I get trying to run Laravel Echo client in Nativescript, there is no window object...

```
ReferenceError: window is not defined
File:"/data/data/org.nativescript.App/files/app/tns_modules/laravel-echo/dist/echo.js, line:208, column:16'
```

Any suggestion to bypass this? Is it not possible to use Laravel Echo in this manner?

Thanks!

**Comment by barryvdh** [comment]
This is an error in Laravel echo, not echo server, right?

**Comment by Skintillion** [comment]
The client yes.

**Comment by barryvdh** [comment]
Why do you want to use the client on the server-side?

**Comment by Skintillion** [comment]
What do you mean? I want to use it as a client. My server is working perfectly. I'm trying to integrate into Nativescript

**Comment by Skintillion** [comment]
Perhaps i'm in the wrong package. my bad.

**Comment by barryvdh** [comment]
Oh sorry, I was mixing things up. But yes, that's what I meant. Try https://github.com/laravel/echo
