### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by akkhan20** [tlaverdure/laravel-echo-server#144]
If i hit the server with http POST request: 
`http://localhost:6001/apps/5780ac79810d7425/events?auth_key=5d9df7139ccba9ba57efd6a791579c83`
it just crashes logging in console: 

> undefined:1
> 
> 
> 
> SyntaxError: Unexpected end of JSON input
>     at Object.parse (native)
>     at HttpSubscriber.handleData (C:\Users\Muhammad Akbar\AppData\Roaming\npm\node_modules\laravel-echo-server\dist\subscribers\http-subscriber.js:25:21)
>     at IncomingMessage.<anonymous> (C:\Users\Muhammad Akbar\AppData\Roaming\npm\node_modules\laravel-echo-server\dist\subscribers\http-subscriber.js:18:59)
>     at emitNone (events.js:86:13)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by barryvdh** [comment]
Can you show your POST data?

**Comment by akkhan20** [comment]
the body is blank

**Comment by barryvdh** [comment]
Why, how are you posting it?

**Comment by akkhan20** [comment]
using http requester to hit the api

**Comment by tchoblond59** [comment]
I have the same problem. I try with postamn and curl.
I am trying to send
`channel:chan-relay
name:test
data:test`
I have various json message error. Can someone help me running one post from curl or postman ?

**Comment by tchoblond59** [comment]
I find myself. I had to use raw option on body form using postman.
Thanks for your amazing work on making laravel real time !

**Comment by tlaverdure** [comment]
Is this still an issue? If not, please close.
