### ISSUE TITLE
Could not authenticate on private channel

### ISSUE THREAD

**Issue by akkhan20** [tlaverdure/laravel-echo-server#145]
i get this error in console:

> Client can not be authenticated, got HTTP status 404

my laravel-server-json is:

> {
> 	"authHost": "http://social.com",
> 	"authEndpoint": "/broadcasting/auth",
> 	"clients": [
> 		{
> 			"appId": "5780ac79810d7425",
> 			"key": "5d9df7139ccba9ba57efd6a791579c83"
> 		}
> 	],
> 	"database": "redis",
> 	"databaseConfig": {
> 		"redis" : {
> 			"port": "6379",
> 			"host": "192.168.8.200"
> 		},
> 		"sqlite": {
> 			"databasePath": "/database/laravel-echo-server.sqlite"
> 		}
> 	},
> 	"devMode": true,
> 	"host": "localhost",
> 	"port": "6001",
> 	"protocol": "http",
> 
> 	"socketio": {},
> 	"sslCertPath": "",
> 	"sslKeyPath": ""
> }
> 

bootstrap.js is like:

> import Echo from "laravel-echo"
> window.io = require('socket.io-client');
> window.Echo = new Echo({
>     broadcaster: 'socket.io',
>     host: 'http://localhost:6001'/*window.location.hostname + ':6001'*/
> 
> });

View is like:

> <script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>
> {{--<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>--}}
> <script src="{{asset('js/app.js')}}"></script>
> 
> <script>
> 
>     window.Echo.private('url-monitor')
>         .listen('urlHit', (e) => {
>         console.log(e);
>     });
> 
> </script>

**Comment by barryvdh** [comment]
Did you add the broadcasting routes to your routes file?

**Comment by akkhan20** [comment]
my routes/channes.php has just this default route:

`Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});`

**Comment by barryvdh** [comment]
https://laravel.com/docs/5.4/broadcasting#defining-authorization-routes
Did you add `Broadcast::routes();` to your routes file?

**Comment by barryvdh** [comment]
Sorry, not in your routes, I mean in your service provider, and register that.

**Comment by akkhan20** [comment]
BroadcastServiceProvider.php :
```
public function boot()
    {
        Broadcast::routes();

        require base_path('routes/channels.php');
    }
```
it already contains this

**Comment by barryvdh** [comment]
And you added the BroadcastServiceProvider to your app config?
Perhaps try some logging to see if the request matches or why it's not found. Not sure why it would give 404 otherwise.

**Comment by akkhan20** [comment]
yes it exists in app config.
i added Log::info($request) to public/index.php and it logs:
```
[2017-03-20 10:59:09] local.INFO: array (
)  
[2017-03-20 09:32:07] local.INFO: array (
  'channel_name' => 'private-url-monitor',
)  
```

**Comment by akkhan20** [comment]
My mistake i took 
`Illuminate\Broadcasting\BroadcastServiceProvider::class,`
for
`App\Providers\BroadcastServiceProvider::class,`
we require both, first one is already present and the second one we need to add manually and run
`php artisan config:cache` if we are caching the configs
