### ISSUE TITLE
Token mismatch

### ISSUE THREAD

**Issue by akkhan20** [tlaverdure/laravel-echo-server#146]
i have `<meta name="csrf-token" content="{{ csrf_token() }}">` in page header
and my request is sent like:

> window.Echo.private('pChat.1')
>             .listen('newChatMessage', (data) => {
>             console.log(data.message);
>         });

but on laravel echo server i get `Client can not be authenticated, got HTTP status 500` which in detail is like:

> E:\Projects\Web\Classified Site\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php line 68">VerifyCsrfToken.php line 68

the user is logged in but i use user_id instead of id in my user model and database as primary key & i dont see any XSRF-token in request cookie in WS console.

**Comment by akkhan20** [comment]
by disabling csrf check it fails on

> \vendor\laravel\framework\src\Illuminate\Broadcasting\Broadcasters\Redi
sBroadcaster.php line 49

which is:

> if (Str::startsWith($request->channel_name, ['private-', 'presence-']) &&
            ! $request->user()) {
            throw new HttpException(403);
        }

**Comment by barryvdh** [comment]
Are you sending to the same domain? Otherwise cookies might not be sent.

**Comment by akkhan20** [comment]
Sorry my mistake, instead of `host: 'localhost:6001'` it should be `host: 'classified.com:6001'` in:

> window.Echo = new Echo({
>     broadcaster: 'socket.io',
>     host: 'localhost:6001'
> });

or better dont hardcode it by setting it:
`window.location.hostname + ':6001'`
