### ISSUE TITLE
Whisper as chat client

### ISSUE THREAD

**Issue by akkhan20** [tlaverdure/laravel-echo-server#149]
Can we use whisper command as client side chat response and make echo server generate an event to save chat. Like laravel echo can emit events to clients but clients cant respond back, using whisper, client can talk directly to other client skipping laravel events if echo server can generate events on the server for saving the chat messages to db and is it safe to do so?

**Comment by barryvdh** [comment]
Why not save them directly then?

**Comment by akkhan20** [comment]
With whisper clients talk directly skiping laravel just hitting laravel echo server in between, currently im sending ajax request to server on each message sent apart from whisper emit.

it is like on sendMessage() an ajax request is made to the server and in the beforeSend method of ajax i emit whisper event to the other client, message is sent instantly to receiver but server is updated after a while when ajax request is processed, problem is that ajax might not succeed or some error on server side might occur but the client gets the message listening to whisper on private channel.

**Comment by dipit2007** [comment]
does beforeSend method will do this job? I don't think so. Simply send separate event. why you are mixing with data msg?

**Comment by akkhan20** [comment]
@dipit2007 see the problem is clients talk directly and the server is updated independently through ajax, if somehow ajax fails the clients will keep talking and server wont have the messages logged to db, i wanted to know if echo server can raise event when it passes the messages to the other client so that the chances of ajax fault is eliminated apart from server errors where clients will still be communicating

**Comment by dipit2007** [comment]
I think whisper method is not intended for that what you actually want.

**Comment by barryvdh** [comment]
Why not just use Ajax to send your messages. Show them as 'sending' when you post it and update the chat when you receive the event back. (add a received icon when received or something)

**Comment by akkhan20** [comment]
@barryvdh that will eliminate the purpose of using whisper as i was already sending messages through ajax but that was taking time like several 100ms as db was getting hit before ajax response was generated + queue process time added for the event being posted to the other client . by using whisper the messages are passing instantly but the problem with ajax failing persists. i will see if echo server can generate laravel events so that whatever happens the data at least reach laravel and i will update here if any progress is made.

**Comment by tlaverdure** [comment]
Not going to be adding support for this as it seems out of scope for this project at this time.

**Comment by anuragrath** [comment]
@akkhan20 Did you find a proper architecture of doing instant communication between clients and taking laravel saving message in the background?
