### ISSUE TITLE
Install and init errors

### ISSUE THREAD

**Issue by mediaceh** [tlaverdure/laravel-echo-server#152]
On install (npm install -g laravel-echo-server) i have error : 

npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: No compatible version found: uws@0.12.0

On init command (laravel-echo-server init) i have error :

Error: Cannot find module '/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node'

What i do wrong?

**Comment by mediaceh** [comment]
oK, i reinstall it and init error disappear. But install warn i have until now.

**Comment by barryvdh** [comment]
Uws is optional so no problem.

**Comment by mediaceh** [comment]
Yes, i know. I change uws varsion to 0.14.1 in optional dependencies and now it installed.

**Comment by barryvdh** [comment]
I think this is related to this: https://github.com/uWebSockets/uWebSockets/issues/551
