### ISSUE TITLE
remote server authentication problem

### ISSUE THREAD

**Issue by MeeDNite** [tlaverdure/laravel-echo-server#154]
Hi,
I had set up laravel-echo-server in homestead. it worked fine.
Then I removed redis and laravel-echo-server to another vm.
now there is authentication problem.
Illuminate\Broadcasting\Broadcasters\RedisBroadcaster::auth on line 47 $request->user() is null.

What am I doing wrong?

**Comment by akkhan20** [comment]
when u initialise laravel-echo-server do you see "listening for redis events"

**Comment by MeeDNite** [comment]
Yes.

version 1.2.8

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

⚠ [2:55:17 AM] - VYBA2MryXHo3igaIAAAA could not be authenticated to private-Kaban.Models.User.1

**Comment by barryvdh** [comment]
Are your cookies being sent to the websocket? Check in dev tools

**Comment by MeeDNite** [comment]
@barryvdh 
Cookie:io=VYBA2MryXHo3igaIAAAA
this is in Request Headers

**Comment by barryvdh** [comment]
That's not the Laravel cookie, so might be why you can't authenticate. Is it a different domain?

**Comment by MeeDNite** [comment]
Laravel is in Homestead VM 192.168.10.10
Redis and L-E-S are in another VM (centos) 192.168.10.101

here is my laravel-echo-server.json:

{
        "appKey": "64bfss8j479lt8a9d0ttf00annngcn83ougk7tlsig2dmq4t4eis8c47s69t",
        "authHost": "http://192.168.10.10",
        "authEndpoint": "/broadcasting/auth",
        "database": "redis",
        "databaseConfig": {
                "redis": {},
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
	"devMode": true,
        "host": null,
        "port": "6001",
        "referrers": [],
        "socketio": {},
        "sslCertPath": "",
        "sslKeyPath": ""
}

**Comment by akkhan20** [comment]
is your domain in the browser 'http://192.168.10.10' or something else?

**Comment by MeeDNite** [comment]
its http://last.app which is only set in host machine. and from L-E-S machine is not viewable.

**Comment by MeeDNite** [comment]
I defined last.app in LES machine's hosts file and now it can see last.app site.
But the problem still exists

**Comment by akkhan20** [comment]
your authhost in LES config must be same as the domain you are using in your browser. e.g

> {
> "appKey": "64bfss8j479lt8a9d0ttf00annngcn83ougk7tlsig2dmq4t4eis8c47s69t",
> "authHost": " http://last.app",
> "authEndpoint": "/broadcasting/auth",
> "database": "redis",
> "databaseConfig": {
> "redis": {},
> "sqlite": {
> "databasePath": "/database/laravel-echo-server.sqlite"
> }

**Comment by MeeDNite** [comment]
I did this. but it doesn't seem to work.

I changed strategy. I moved LES to Homestead and pointed to CentOS vm for Redis server:

{
  "appKey": "64bfss8j479lt8a9d0ttf00annngcn83ougk7tlsig2dmq4t4eis8c47s69t",
  "authHost": "http://last.app",
  "authEndpoint": "/broadcasting/auth",
  "database": "redis",
  "databaseConfig": {
    "redis": {
      "port": "6379",
      "host": "192.168.10.101"
    },
    "sqlite": {
      "databasePath": "/database/laravel-echo-server.sqlite"
    }
  },
  "devMode": true,
  "host": "last.app",
  "port": "6001",
  "referrers": [],
  "socketio": {},
  "sslCertPath": "",
  "sslKeyPath": ""
}

it works now.
But whats the problem with LES authentication from another server?

**Comment by akkhan20** [comment]
Just configurations issue no logical problem

**Comment by MeeDNite** [comment]
@akkhan20 absolutely. Im asking this for help on the configuration

**Comment by aidanayala** [comment]
@MeeDNite Did you fix this?

My guess is you'd need to change the broadcast driver config. By default, for Redis it'll use the localhost when instead you'd want it to connect to the remote hosts Redis

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
