### ISSUE TITLE
Echo.here, .joining, .leaving are not triggered

### ISSUE THREAD

**Issue by Otsukai** [tlaverdure/laravel-echo-server#159]
Hello,

I'm working on a chat application, but I'm having issue with the methods Echo.here, .joining, and .leaving.

The **Echo.join and .listen are working fine** (messages are exchanged between different users), but I'm unable to know who, or how many users are connected.

I've seen the issue #139 , but it didn't change anything for me. Redis puts the default host/port if not set in the config, and I use the default host/port.

One thing quite strange, is that if I change BROADCAST_DRIVER to "pusher" instead of "redis" in my .env file, then the here/joining/leaving methods are triggered ! But once I send a message, the event broadcasting is failing in Laravel, since nothing is configured for pusher.

I'm using Laravel 5.4, Laravel-echo 1.3.0, Laravel-echo-server 1.2.8, and NodeJS 7.9.0

Here are my files/configs

**laravel-echo-server.json**

	"authHost": "http://localhost:8000",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "xx",
			"key": "xx"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "localhost",
	"port": "6001",
	"protocol": "http",
	"socketio": {
		"wsEngine": "uws"
	},
	"sslCertPath": "",
	"sslKeyPath": ""

**bootstrap.js**
```
window.Echo = new Echo({
    broadcaster: 'socket.io',
	host: window.location.hostname + ':6001'
});
```

**.env**
```
BROADCAST_DRIVER=redis
...
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
```

**js file**
```
Echo.join('chatroom.' + this.groupId)
	.listen('MessagePosted', (e) => {
		this.messages.push({
			message: e.message,
			user: e.user
		});
	})
	.here((users) => {
		console.log("here");
	})
	.joining((user) => {
		console.log("joining");
	})
	.leaving((user) => {
		console.log("leaving");
	});
```

**app.blade.js**
```
<script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>
```

**Comment by akkhan20** [comment]
in your LES config u have set database to redis so below that where its redis{} u need to provide host and port

**Comment by Otsukai** [comment]
Thanks @akkhan20 , unfortunately I'm still having the issue, even with the following :
```
"databaseConfig": {
	"redis": {
		"port": "6379",
		"host": "localhost"
	},
```

**netstat -tlp**
`tcp        0      0 localhost:6379          *:*                     LISTEN      1208/redis-server 1`

**Comment by phassani** [comment]
I just went through a similar problem. It may be the way you are authorizing the user connecting to the channel. On Presence channels you need to return data about the user, not true/false. (See docs: https://laravel.com/docs/5.4/broadcasting#presence-channels)

Can you post your Broadcast channel authorization (should be in channels.php)?

**Comment by Otsukai** [comment]
Thank you so much !

My issue was indeed what you described. I just changed my authorizing method so it returns user's data instead of true, and it works :)

**Comment by edisonchenz** [comment]
I have same problem 

Echo.here, .joining, .leaving are not triggered

but Echo.channel.listening can work

I use it with laradocker

**laravel-echo-server.json**

`{
	"authHost": "localhost",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "redis"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}
`

**Comment by EltonPastilha** [comment]
Same problem here
