### ISSUE TITLE
Echo does not listen to broadcast notifications 

### ISSUE THREAD

**Issue by johnveeuminga** [tlaverdure/laravel-echo-server#160]
So I've tried implementing laravel-echo-server since it was recommended in the documentation of Laravel. I'm using Laravel 5.4 and needs to implement broadcast notifications in my system. Everything is working fine except for fetching data/listening to an event. 

Laravel Echo Server listens to the event. joins and authenticate channels but on the page, it fails to fetch the data I guess.

As seen here, the server listens to events and joins channels
![image](https://cloud.githubusercontent.com/assets/27657674/25077156/c16cadb4-2359-11e7-80a1-0383b489973d.png)

I trigger a notification when a user enters a page
![image](https://cloud.githubusercontent.com/assets/27657674/25077207/3775b19a-235a-11e7-8bd0-6eeb126dc96f.png)

On my code, I console log true to test if it's receiving any data.
![image](https://cloud.githubusercontent.com/assets/27657674/25077195/0f293496-235a-11e7-8857-14dd82ad0c4a.png)

But when I test it out, the console is empty. Even when testing it using two different users at two different browser
![image](https://cloud.githubusercontent.com/assets/27657674/25077236/8aba458c-235a-11e7-9ecf-760ca80a1648.png)

Here's my laravel-echo-server config
![image](https://cloud.githubusercontent.com/assets/27657674/25077244/a047f5ca-235a-11e7-8d92-d17765b50014.png)

EDIT:
Turns out that it listens to broadcast events but not broadcast notifications

I listen to event using this
![image](https://cloud.githubusercontent.com/assets/27657674/25077548/acb9f2b0-235d-11e7-9bd7-be4349735d5b.png)

And it logs true on the console
![image](https://cloud.githubusercontent.com/assets/27657674/25077555/bf1d4ace-235d-11e7-8064-80389237ea8c.png)

But still, not listening to broadcast notifications

**Comment by nivanmorgan** [comment]
@taylorotwell I'm having the same problem. Don't want to create events for each notification if it is broadcasted as a notification. I tried listening to BroadcastNotificationCreated and binding to Illuminate\\Notifications\\Events\\BroadcastNotificationCreated. Is there a way to bind these events?

**Comment by AEK-BKF** [comment]
Hi @johnveeuminga ! Any news ? Have you resolved your problem ?

**Comment by m809745357** [comment]
try it
```javascript
Echo.private('users.' + {{Auth::user()->id}})
    .listen(".Illuminate\\Notifications\\Events\\BroadcastNotificationCreated", (notification) => {
    console.log(notification.type);
});
```

**Comment by johnveeuminga** [comment]
@AEK-BKF unfortunately, I resorted to broadcast events on this project because as I said, it works perfectly fine on broadcast events. Try @m809745357 code though.

**Comment by xparthxvorax** [comment]
Guys, I'm having exactly the same issue. Not able to listen to notification but can listen to events. Did anyone get any solution?

**Comment by romrz** [comment]
Same thing here. Not able to listen to notifications. Has anyone found a solution?

**Comment by romrz** [comment]
As @m809745357 pointed out, the following code worked for me:

`Echo.private('App.User.' + {{Auth::user()->id}})
    .listen(".Illuminate\\Notifications\\Events\\BroadcastNotificationCreated", (event) => {
    console.log(event.type);
});`

**Comment by legreco** [comment]
Same problem here

**Comment by sodri126** [comment]
same problem here, i have added "." in the front name of listen. and didn't' working. how to solve?

**Comment by legreco** [comment]
Hi @sodri126 ,
@m809745357  solution worked for me
```
 window.Echo.private('App.User.' + userId)
                    .listen(".Illuminate\\Notifications\\Events\\BroadcastNotificationCreated",(notification) => {
                        window.console.log('Got event...');
                    });
```
Try it

**Comment by sodri126** [comment]
@legreco but, i put my events in App\Events\MessageChat

should i try your code, or change with my event in listen?

**Comment by legreco** [comment]
If all your events are located in App\Events\MessageChat you can do
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'your-pusher-key',
    namespace: 'App.Events.MessageChat'
});
```
and use the event name as usual
```
Echo.channel('orders')
    .listen('Event.Class', (e) => {
        //
    });
```

**Comment by sodri126** [comment]
@legreco without "." or dot in front of name listen?

**Comment by legreco** [comment]
According to documentation

> you may prefix event classes with a . when subscribing to them using Echo. This will allow you to always specify the fully-qualified class name

**Comment by sodri126** [comment]
@legreco ok. will try it. if the your code is not working, i will ask you again.

**Comment by sodri126** [comment]
is not still working @legreco i am confused about this.

**Comment by legreco** [comment]
What version of laravel do you use?

**Comment by sodri126** [comment]
laravel 5.3

**Comment by legreco** [comment]
Do you use pusher as broadcaster?

**Comment by sodri126** [comment]
no, i use socket.io for broadcaster.
is not different with socket.io? because in the laravel-echo server and redis-cli monitor, the message is catched. but in the browser cannot catch message from user 1 to user 2

**Comment by legreco** [comment]
Can i see:
1. The code of your event class
2. The portion of code where you listen to this event
3. your laravel-echo-server config
4. The portion of code in bootstrap.js where you import Echo and attach it to window

**Comment by sodri126** [comment]
ok wait the minutes....

**Comment by sodri126** [comment]
1.. My event class, App\Events\MessageChat

```
<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class MessageChat implements ShouldBroadcast
{
    use InteractsWithSockets, SerializesModels;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public $id;
    public $idfriend;
    public $message;
    public $dateOfMessage;
    public function __construct(array $user)
    {
        $this->id = $user['id'];
        $this->idfriend = $user['idfriend'];
		$this->message = $user['message'];
		$this->dateOfMessage = $user['dateOfMessage'];
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */
    public function broadcastOn()
    {
    	return [
    		new PrivateChannel('msg.'. $this->id),
		    new PrivateChannel('msg.'. $this->idfriend)
	    ];
    }
}
```

2. 
```
Echo.private(`msg.{{ auth()->user()->bnIdUser  }}`)
            .listen('MessageChat', (e) => {
            console.log('success);
});
```

3. 

```
{
	"authHost": *sensored*,
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": *sensored*,
			"key": *sensored*
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "127.0.0.1"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "8098",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": ""
}
```

4. 
```
import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: {path: '/socket.io'},
    namespace: 'App.Events'
});

```

i use host /socket.io because there is any setting that i use path socket.io. web server that i use is nginx.

**Comment by legreco** [comment]
Everything seems ok. 
Currently at work. I will dig deeper into it later today by installing a fresh version of laravel 5.3 and trying to replicate your situation.

**Comment by sodri126** [comment]
ok thanks @legreco 

yeh it's ok when i first try to localhost, but i upload into vps, my code isn't working. i don't know why this code is not running in vps.

**Comment by ctf0** [comment]
https://github.com/tlaverdure/laravel-echo-server/issues/196#issuecomment-355666038

**Comment by kevuno** [comment]
This looks like an old thread, but has anyone found a solution? It works fine locally, but when I deploy to Heroku it just simply doesn't.

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Comment by Jagadhissh** [comment]
first check that channel listening or not 
Echo.private('App.User.' +AuthUserId) .listen(".Channel Name ", (event) => { console.log(event.type); });

listen(.Channel name)
before that ur redis server running or not
