### ISSUE TITLE
User disconnection Event

### ISSUE THREAD

**Issue by Edo-San** [tlaverdure/laravel-echo-server#161]
I would like to fire a Laravel event that performs a couple of database operations related to a user when the same user leaves a presence channel.
I cannot rely on the .leaving() event for this specific purpose, and I was thinking about how could I listen to this event directly from server-side.
Is there a way?
I can see from laravel-echo-server cli that a message get prompted when a user leaves a channel ("left-channel: channel-name (transport closed)". Can I somehow "hook" to this event?

**Comment by akkhan20** [comment]
you need to modify current LES code and put redis pub where u want to generate event and on laravel side implement redis sub to listen for event

**Comment by msonowal** [comment]
@KingCrimson87 
Run a laravel scheduler which checks last_seen timestamp and set a interval if it is not more than 5 minutes then mark it offline and trigger your event

**Comment by KingCrimson87** [comment]
I adopted a solution that it similar to msonowal but I'm not completely satisfied :) Guess I'll stick with that for now. Thank you guys for the answers, any plan on implementing this kind of hook natively as well?

**Comment by msonowal** [comment]
@KingCrimson87 I will try to implement it via LES with redis with LaravelEvent in coming days

**Comment by KingCrimson87** [comment]
@msonowal that would be awesome man :) Thanks!

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
