### ISSUE TITLE
Forge recipe available?

### ISSUE THREAD

**Issue by sandervanhooft** [tlaverdure/laravel-echo-server#164]
I'm thinking of replacing my Pusher setup with Echo on my Forge sites. But the discussions about ssl certificate renewals and the initial config make installing it on Forge seem hacky.

Does anyone have a Forge recipe available to set this up properly?

**Comment by tlaverdure** [comment]
I've been able to run a few instances on forge without any issues. You just need to locate the ssl certificates for the right domain and paste them in.

```json
{
    "sslCertPath": "/etc/nginx/ssl/example.com/1234123/server.crt",
    "sslKeyPath": "/etc/nginx/ssl/example.com/1234123/server.key"
}
```

**Comment by barryvdh** [comment]
But aren't those changing every renewal?

**Comment by tlaverdure** [comment]
I don't think so. I've had one running for a few months now with no problems.

**Comment by sandervanhooft** [comment]
I think the renewal frequency is less than that, so it may still become a
problem. Also, I'd still be interested in a Forge recipe :). Does anyone
have a (tried and tested) bash script lying around?

**Comment by jonnywilliamson** [comment]
@tlaverdure I stand to be corrected, but I thought if you had certs created with Lets Encrypt, then they would be renewed every 3 months or so and so your path/filename would need to continuously be updated each time that happened. Which would be fairly annoying.

Assuming that was the case, I decided to implement another idea.

The current setup has us requiring (at least 2) ports open on our firewall to use our website and Laravel-Echo-Server - namely `port 80/443` for our webserver  and then `port 6001` (or whatever) for  the echo server.

But what if we could do all the connections with just the webserver? That way, we wouldn't have to worry about ssl or certs at all for laravel-echo-server.


Here's how it works:

- We tell nginx that we want to proxy all connections to the url `/socket.io` on our webserver to laravel-echo-server.

- We set the laravel-echo-server.json config file to listen on 'localhost' NOT on a domain name. NO need to set ANY SSL certs etc.

- In our laravel `bootstrap.js` file, we tell it where to look to connect to the echo server



```
//In your nginx setup for your website, eg example.com
//eg /etc/nginx/sites-enabled/example.com, in the server block add the following

location /socket.io {
    proxy_pass http://127.0.0.1:6001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}  
``` 


```
//laravel-echo-server.json config file should include this

	"host": "localhost",
	"port": "6001",
```


```
//laravel's bootstrap.js
import Echo from "laravel-echo"

window.echo = new Echo({
    broadcaster: 'socket.io',
    host: { path: '/socket.io' }
});
```


So now what happens is that:

1. You visit your website as normal (example.com).
2. Laravel makes a connection to `example.com/socket.io` to connect with the laravel-echo server
3. Nginx, detects this and proxy/forwards the request to the actual server running on localhost and port 6001 BEHIND the firewall, not needing any SSL etc.

You don't need to open extra ports, minimal config, it's very clean and secure, and I've been using it for months now.

Hope that helps someone.

**Comment by barryvdh** [comment]
I think there is an issue about apache config similar to that approach, but like the Idea :)

**Comment by jonnywilliamson** [comment]
@barryvdh Thanks.

I have not looked to see if there is an apache command/ability to do the same proxy/forward as nginx as all my sites are using nginx and I've never looked into it for apache.

Sorry if that doesn't help you. 😞

**Comment by barryvdh** [comment]
Oh sorry, I meant there was a similar approach in https://github.com/tlaverdure/laravel-echo-server/issues/39 but I see that is also from you :p

**Comment by tobiasvielmetter** [comment]
@jonnywilliamson Thank you for this configuration, it makes a lot of sense. It works like a charm in my development environment (laravel homestead vm), but I have issues authenticating in my production environment (laravel forge. with ssl cert) that I can't put my finger on:
- The laravel-echo-server script tells me:
```
⚠ [13:40:32] - 63K9kcQdIuJYhnkSAAAC could not be authenticated to private-notification.6-1
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.9</center>
</body>
</html>

Client can not be authenticated, got HTTP status 301
```
- The access logs of nginx all show 200 codes.
- The first two connections to socket.io look good, the third returns `55:42["subscription_error","private-notification.6-1",301]`

So somehow nginx seems to send a 301 at some point. I haven't really understood when this is happening, as the 301 is not showing up on the client side. 

Could anyone give me a pointer on what I can check? The reverse proxy code is before any other in the nginx config, there are no rewrites in the config, I have restarted etc. Not sure where the 301 is coming from.

Thanks for any help in finding the issue.

**Comment by jonnywilliamson** [comment]
Thanks for the write up and update @tobiasvielmetter .

I'm "lucky" in that I have this running for a single personal webapp and I haven't looked into multi-tenant issues at all, so in that regards I can't give you any help.

However, just wanted to check, are you saying that you have this running in production now (for one domain anyway?) If so....that's great!

**Comment by tobiasvielmetter** [comment]
@jonnywilliamson Thanks and sorry for my confusing writ up, I struggeled with this for a while ands figured some of the context out shortly after commenting. I was able to get this working in production with one domain (after setting authHost to the right url), but as the authHost is static, there needs to be additional measures in order to change the authHost according to the tenant subdomain it is used for. I have commented on this at #185 in case someone is interested in more context.

**Comment by nickkuijpers** [comment]
@jonnywilliamson i love your solution, i am using it from now on. Thank you!

**Comment by Eldair** [comment]
@jonnywilliamson how do you access API from within app in this setup ?

**Comment by empresarrollo** [comment]
@jonnywilliamson doesn't you have some problem with nginx exhausting its connections pool?
