### ISSUE TITLE
How to define or pass auth guard for broadcast authentication routes instead of default auth guard?

### ISSUE THREAD

**Issue by msonowal** [tlaverdure/laravel-echo-server#166]
I am very new to realtime event broadcasting, I have simple laravel-echo-server setup and working with everything. I am unable to set/define authentication against other auth `guard` it is always checking with `default` `guard` defined in `auth.php` which is in my case `user`

I have setup the authentication routes for each guards private channels in `routes/channel.php` as below per documentation.
 

> For auth guard user private channels

    Broadcast::channel('users.{id}', function ($user, $id) {
       Log::info(class_basename($user));
       return (int) $user->id === (int) $id;
    });

> For auth guard admin private channels

    Broadcast::channel('admins.{id}', function ($admin, $id) {
       Log::info(class_basename($admin));
       return (int) $admin->id === (int) $id;
    });

 It works fine for guard `user` that is the first case but never worked for the second one i.e. `admin` guard.
and the

`Log::info(class_basename($admin))` always returns `User` class.

So, how do we pass or define that it should use `admin` guard instead of `user`.
after exploring the inside of `Illuminate\Broadcasting\Broadcasters\Broadcaster` I found out that below in line `411`

    public function user($guard = null)
    {
        return call_user_func($this->getUserResolver(), $guard);
    }
So, if we can pass this guard parameter it can solve the purpose.
If anyone can give me anything or way of authorising with multiple guard setup that will be very helpful.
Using `Laravel 5.4, laravel-echo-server, Redis, Socket.IO`
asked the same on so
[http://stackoverflow.com/questions/43682681/how-to-define-or-pass-auth-guard-for-broadcast-authentication-routes-instead-of](url)

**Comment by thesupad** [comment]
Hello msonowal,

In BroadcastServiceProvider.php, in your boot(), you will find :
`
        Broadcast::routes();
`
It declares the needed routes for the broadcasting, including the auth ones.

You can pass attributes to this declaration, such as :
`
        Broadcast::routes([
            "prefix"     => "api",
            "middleware" => "auth:api",
        ]);
`

In this example, i've set a prefix for the routes and api authentification middleware.

That said, i indeed hit the api guard, but i can't find a way to pass the access token thrue laravel echo... :(

**Comment by thesupad** [comment]
To who ever arrives here, the solution for auth with Laravel Echo :
`window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost:6001',
    auth:
    {
        headers:
        {
            'Authorization': 'Bearer ' + token
        }
    }
});`

Thanks to https://laravel.io/forum/10-09-2016-howto-broadcasting-laravel-echo-laravel-echo-server-and-jwt

**Comment by tlaverdure** [comment]
I think that this is a question to be asked on Laracasts or an issue to be opened on Laravel Framework since it has to deal with adding support for multiple auth guards for Broadcasting.
