### ISSUE TITLE
ECONNREFUSED, Authhost is in another docker container

### ISSUE THREAD

**Issue by cre8** [tlaverdure/laravel-echo-server#173]
I am working with 3 docker files (with laradock), one including the laravel-echo-server, one the laravel application and one the for the http server (using caddy).

I can address the redis container with

```
"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "redis"
		}
	},
```

But every try to address the authHost fails:
` Error: Invalid URI "caddy/broadcasting/auth"`

When I use a testdomain that is registered in my local host file it tries to use `127.0.0.1`

**Comment by cre8** [comment]
Okay, it was "just" a docker error. I had to set the auth just to `http://caddy` and the caddy container is listening on `0.0.0.0:80`

**Comment by ModernArtisan** [comment]
@cre8 Ok, but what if I have different domain name? `example.dev`
