### ISSUE TITLE
Client to Server Message?

### ISSUE THREAD

**Issue by akkhan20** [tlaverdure/laravel-echo-server#176]
Why we dont have a feature for client->server message on a channel?

**Comment by tlaverdure** [comment]
There currently isn't any support for sending data from the client to the server. Only Sever -> Client and Client -> Client. If there is a good use case for this please follow up with some details. But for most cases, it seems like pushing data to your server first is the normal pattern in terms of authentication, validation, and hitting the database if necessary. 

Closing for now.
