### ISSUE TITLE
APP_URL from .env file for authHost

### ISSUE THREAD

**Issue by murrant** [tlaverdure/laravel-echo-server#178]
Is there anyway we can use APP_URL from the .env file to populate authHost for laravel-echo-server?

**Comment by tlaverdure** [comment]
No there currently isn't

**Comment by TiBianMod** [comment]
Yes is it @tlaverdure 

Follow the steps below

> - Install dotenv

```npm install dotenv --save```

> - Create a js file on the project root for example ```websocket.js```

```js
require('dotenv').config();

const env = process.env;
const EchoServer = require('laravel-echo-server');

// You can pass here any options you need.
// This is simple example how is work.

const options = {
    authHost: env.APP_URL,
    devMode: env.APP_DEBUG,
    host: 'localhost',
    port: 60001
};

EchoServer.run(options);
```

> Here is the [options](https://github.com/tlaverdure/laravel-echo-server#user-content-configurable-options) you can pass to the object 

> - Finally run on the terminal ```node websocket.js```

That's all, you are ready :)

**Comment by murrant** [comment]
Thanks @TiBianMod !

This should be the default way this package is launched in my opinion.

**Comment by TiBianMod** [comment]
I think the same @murrant 

Basically you can run Laravel Echo Server right now with this two ways, .json and .js file (no proble), but no were in the docs you can see the .js way (also I think is more clean way).

I hope @tlaverdure to see this conversation and to make the necessary changes :)

**Comment by tlaverdure** [comment]
Or make a PR :)

**Comment by TiBianMod** [comment]
hehe :)

**Comment by MarnuLombard** [comment]
Hi guys. I've attempted to address this problem in PR #275 
Have a look.

**Comment by tlaverdure** [comment]
This has been added in 1.3.7. Only change to the PR that was submitted is that the server will automatically look for the .env file and use these env variables if defined:
https://github.com/tlaverdure/laravel-echo-server#dotenv
