### ISSUE TITLE
Echo client cannot receive events from server when using domain/hostname

### ISSUE THREAD

**Issue by a1q123456** [tlaverdure/laravel-echo-server#180]
here is my `laravel-echo-server.json`:
```json
{
    "authHost": "http://app.dev",
    "authEndpoint": "/broadcasting/auth",
    "clients": [
        {
            "appId": "f9224c51a6dfd03a",
            "key": "5e5b63f032d4f6fbe1344d6eb15308fb"
        }
    ],
    "database": "redis",
    "databaseConfig": {
        "redis": {},
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        }
    },
    "devMode": true,
    "host": "app.dev",
    "port": "6001",
    "protocol": "http",
    "socketio": {},
    "sslCertPath": "",
    "sslKeyPath": ""
}
```

and my echo config is:
```javascript
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001',
});
```

echo.html:
```javascript
Echo.private(`order.${orderId}`)
    .listen('OrderPaidEvent', (e) => {
     console.log(e);
});
```

when `OrderPaidEvent ` is fired, laravel-echo-server outputs:

```
Channel: private-order.
Event: App\Events\OrderPaidEvent
CHANNEL private-order.
```

but  nothing logged in browser console window

if I change `host`&`authHost ` to `127.0.0.1` in `laravel-echo-server.json`, client can be notified, but if I'm using domain or hostname in `host`&`authHost` in `laravel-echo-server.json`, client cannot be notified.

I'm using nginx to serve lots of websites on same machine, so I couldn't just use ip here.

please, help me

**Comment by a1q123456** [comment]
problem solved, using nginx to pass all `/socket.io` request to laravel-echo-server

**Comment by aftabnaveed** [comment]
@a1q123456 are you able to share you Nginx configuration? I reverse proxied all requests on /socket.io/ to Laravel echo server, but it seems to be not working. Below is my configuration.

```nginx
upstream websocket {
   server localhost:6001;
}

location /socket.io/ {
       proxy_pass http://websocket;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
   }
```
Thank you.

**Comment by jonnywilliamson** [comment]
@aftabnaveed Can you run through the instructions here https://github.com/tlaverdure/laravel-echo-server/issues/164#issuecomment-309214294 carefully and see if it helps you.

Sounds like you might just have missed changing details in your Laravel `bootstrap.js` file.

**Comment by aftabnaveed** [comment]
@jonnywilliamson thanks for your response. I was able to resolve the issue but creating a different subdomain dedicated for websockets (ws.domain.com) this still proxy to localhost:6001. It's strange but worked for me :-)

**Comment by a1q123456** [comment]
@aftabnaveed  sorry for late, my nginx configuration is
    
    location ~* \.io {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_pass http://localhost:6000;
      proxy_redirect off;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

**Comment by callemac88** [comment]
I have a problem i could not resolve.

when I use the program in localhost work perfect but when I move it to the server production it does not work.

I saw when i run laravel-echo-server start in localhost it shows:
✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

but in production it shows:
✔  Running at localhost on port 6001
✔  Listening for http events...
✔  Listening for redis events...

What could be happening??? why the option Channels are ready. is not working??? thank you
