### ISSUE TITLE
falling back to source compile with node-gyp

### ISSUE THREAD

**Issue by pavinthan** [tlaverdure/laravel-echo-server#181]
pavi@pavi:~$ sudo  npm install -g laravel-echo-server
npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly
/usr/bin/laravel-echo-server -> /usr/lib/node_modules/laravel-echo-server/bin/server.js

> sqlite3@3.1.8 install /usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/bin/nodejs',
node-pre-gyp verb cli   '/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@7.10.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http EACCES: permission denied, mkdir '/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding' 
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/build'
gyp ERR! System Linux 4.10.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v51-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.10.0-24-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v51-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pavi/.npm/_logs/2017-06-27T14_13_46_841Z-debug.log

**Comment by kuczmaja** [comment]
I have the same. @pavinthan Have you solved this?

**Comment by pavinthan** [comment]
Yes @kuczmaja, I tried `npm i npm@4.6.1 -g` then install `npm i laravel-echo-server -g` that work fine after that you can update your npm to latest version using `npm i npm@latest -g`

**Comment by trotsaleksandrov** [comment]
Facing the same issue also. Only dwongrading npm helped

**Comment by scotthelps17** [comment]
Same issue, `Failed at the sqlite3@3.1.8 install script.`. @pavinthan's answer did the trick!

**Comment by pavinthan** [comment]
Latest version NPM support me install `laravel-echo-server` after fixed NPM permissions, please  [use this link](https://docs.npmjs.com/getting-started/fixing-npm-permissions) to fix your NPM permissions.
