### ISSUE TITLE
Keep track user online status in database 

### ISSUE THREAD

**Issue by martingg88** [tlaverdure/laravel-echo-server#182]
Can anyone give some example to keep track user online status in database? your help is much more appreciated. thanks.

**Comment by tlaverdure** [comment]
Check this out: https://github.com/tlaverdure/laravel-echo-server#http-api

**Comment by martingg88** [comment]
What is if we have million online users. Do you think it is a best way to call this API?
Is that anyway to get the online users by directly contact to database layer?
