### ISSUE TITLE
Event being broadcasted but client wont pick up on it

### ISSUE THREAD

**Issue by thorlucas** [tlaverdure/laravel-echo-server#187]
I'm trying to broadcast a simple event using Redis, Laravel Echo, Laravel Echo Server, and socket.io.
I've got everything in place on the client side. The message is indeed being broadcasted and laravel echo server is picking up on it.

On chat.dev/ I have the client joining. On chat.dev/new I have the event being broadcast.

```
[5:14:31 PM] - HvEq_a12YnQFJGFiAAAE joined channel: chat
Channel: chat
Event: message.created
CHANNEL chat
```

So it seems like everything is working. On the client side, I'm including socket.io and it is finding it.

`<script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>`

Then I'm running

```
import Echo from 'laravel-echo'

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
});


window.Echo.channel('chat')
    .listen('.message.created', (e) => {
        console.log("Got message");
    });
```

But nothing is being logged to the console. Why?

**Comment by thorlucas** [comment]
After a lot of fiddling, the frame is now being received by the client. BUT .listen isn't picking up on it!

```
42["message.created", "chat", {,…}]
0
:
"message.created"
1
:
"chat"
2
:
{,…}
message
:
{id: 23, body: "Modified", created_at: "2017-07-19 01:11:18", updated_at: "2017-07-19 01:11:18"}
socket
:
null
```

**Comment by enzonotario** [comment]
Hi! I think that your problem is that, by default, Echo Client listens to an event with namespace `App\Events`. But your events seems to be `message.create`, without namespace.

See https://laravel.com/docs/5.4/broadcasting#namespaces

**Comment by thorlucas** [comment]
Nope. That's not it. I'm using the prefix "." syntax to escape the namespace.

**Comment by thorlucas** [comment]
Plus the frame that's being received only says "messages.created" without any namespace

**Comment by enzonotario** [comment]
https://github.com/laravel/echo/pull/132

**Comment by sarfraznawaz2005** [comment]
I am also having same issue. Everyhing works okay locally or staging but not on production. `listen` doesn't seem to fire on `https`. Any solution for this ?

**Comment by tlaverdure** [comment]
This looks like a client configuration issue. Closing
