### ISSUE TITLE
I can't get it working :/  ( Client can not be authenticated, got HTTP status 500 )

### ISSUE THREAD

**Issue by AEK-BKF** [tlaverdure/laravel-echo-server#188]
Hi all,
I've followed many tutorials to get laravel echo server working but no way !!
Here my state :
L 5.4,
```
{
	"authHost": "http://192.168.1.1:8000",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}
```
Bootstrap.js :
```
window.axios = require('axios');

window.axios.defaults.headers.common['X-CSRF-TOKEN'] = window.Laravel.csrfToken;
window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

/**
 * Echo exposes an expressive API for subscribing to channels and listening
 * for events that are broadcast by Laravel. Echo and event broadcasting
 * allows your team to easily build robust real-time web applications.
 */

import Echo from 'laravel-echo'

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost:6001'
});
```
```
public function boot()
    {
        // Broadcast::routes(['middleware' => ['web', 'auth']]);
         // Broadcast::routes(['middleware' => ['auth', 'web']]);
        Broadcast::routes();

        require base_path('routes/channels.php'); 
           
    }
```
```
Broadcast::channel('private-ticket-{ticketID}', function ($user, $ticketID) {
	// $ticket = App\Models\Ticket\Ticket::find($ticketID);
	// if(in_array(auth()->user()->id, explode(',', $ticket->category->users->pluck(id)))) {
		return true;
	// } else {
	// 	return false;
	// }
});
```

```
<script>
	
	window.Echo.private('private-ticket-{{$ticket->id}}')	
    .listen('CreateTicketEvent', (e) => {
        toastr.info('New Ticket has been created !', 'info');
    });    

	</script>
```

and here terminal output :

```
</div>

            </div>
    </body>
</html>
Client can not be authenticated, got HTTP status 500
[11:53:09] - fXL0507CYfI3IB_wAAAB left channel: private-private-ticket-48 (transport close)
[11:53:11] - 1tpQgxVDDf6_AXtHAAAD authenticated for: private-private-ticket-48
[11:53:11] - 1tpQgxVDDf6_AXtHAAAD joined channel: private-private-ticket-48

```

Please help me :(

**Comment by tobiasvielmetter** [comment]
@AEK-BKF since you get a 500 you surely have a server error -> typo somewhere in your php code. 
Please check your laravel logs. You can also activate full verbose output for the express server by running:
`DEBUG=* laravel-echo-server start`

**Comment by AEK-BKF** [comment]
Sorry for delay, I found a good tutorial for using your wonderful package :)
Here : [https://www.youtube.com/watch?v=WrsI6qf0KSA](url)

But I have a question, is it a good idea to use this package with Redis & Socket on the same server of Laravel App ? I mean what's the best way to establish a web app which uses notifications server ?

**Comment by tobiasvielmetter** [comment]
@AEK-BKF don't speak french, so the video is not for me. I would assume most projects would be best served to run all these services on the same machine. It reduces any latency between the services. Once you need to scale, you would think about isolating each service onto its own machine to balance the performance.

**Comment by AEK-BKF** [comment]
Thank you so much for quick reply,
Other thing, Why we should run php artisan queue:listen to get laravel-echo notifications running ?

**Comment by tobiasvielmetter** [comment]
@AEK-BKF depending on how you produce events and if you queue them, you will need to run a queue in order to emit the events (eg beanstalkd). Btw. this is not a help forum for laravel, but a issue tracker for laravel-echo-server. Just check the laravel docs in the events section https://laravel.com/docs/5.4/events and ask over at https://laracasts.com/discuss if you have concrete questions about laravel that are not easily answered by the docs. I think this issue can be closed. Good luck!

**Comment by AEK-BKF** [comment]
Thank you so much dear sir :))))

**Comment by tlaverdure** [comment]
Closing
