### ISSUE TITLE
Question: Can We use it without redis ?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [tlaverdure/laravel-echo-server#189]
Is it possible to use this package without redis dependecy ? I can see that it also supports http, can we use for example curl to broadcast messages to client-side without using redis ?

Thanks

**Comment by barryvdh** [comment]
Yes

**Comment by sarfraznawaz2005** [comment]
@barryvdh : I assume `http` can be used for that as the docs say but can you give a simple example of how to send such request? Will event class still be needed ?

**Comment by barryvdh** [comment]
You can just use events with the sync queue driver. See https://github.com/tlaverdure/laravel-echo-server/blob/master/README.md#http

**Comment by sarfraznawaz2005** [comment]
@barryvdh : Thanks yes i had seen that. My question is how to send that POST request with laravel as the docs say:

Request Endpoint

`POST http://app.dev:6001/apps/your-app-id/events?auth_key=skti68i...`

Request Body

```
{
  "channel": "channel-name",
  "name": "event-name",
  "data": {
      "key": "value"
  },
  "socket_id": "h3nAdb134tbvqwrg"
}
```

So it is still a bit confusing. Docs do not give example **how to send `http` POST request with event class.**

Thanks

**Comment by barryvdh** [comment]
You can use the pusher api and examples from laravel docs, but with the socketio endpoint/user etc

**Comment by sarfraznawaz2005** [comment]
Doesn't help, closing anyway...

**Comment by barryvdh** [comment]
What did you try? Did you set your broadcasting driver to pusher, following https://github.com/tlaverdure/laravel-echo-server#pusher ?

**Comment by sarfraznawaz2005** [comment]
yes I set but I don't know how to send `http` POST with event class as the docs suggest.

**Comment by sarfraznawaz2005** [comment]
@barryvdh : Thanks one last question. Can we send events without pusher ? (You see I am trying to avoid redis or any third party services)

**Comment by barryvdh** [comment]
The HTTP API simulates the Pusher API. If you configure the pusher options to use localhost (or whatever server it runs on) with the socketio port, you are not using Pusher, just the HTTP api. So Laravel will take care of sending the HTTP post messages to SocketIO. If you configure your queue driver as sync, you don't need redis.

You can also create your own driver but creating the http messages with Guzzle or something, but would not recommend that.

**Comment by sarfraznawaz2005** [comment]
@barryvdh thanks now it makes sense, thanks for the help.

**Comment by sarfraznawaz2005** [comment]
@barryvdh thanks for all the help, I managed to use this package now without redis, pusher.com and queues.

**Comment by CaptainCannabis** [comment]
I cant get it working. Events are firing, channels are up. I see the fired event and its payload in laravel.log but i can't get it to the frontend. What are the settings for using the pusher-options to work with the http api?

Do i only have to insert my key and app_id generated by laravel-echo-server and the options host, port and scheme in the connections array?

If i do that and trie to start the server i get "Class 'Pusher\Pusher' not found". Do i have to install it 
even though i wont use it?

**Comment by hungntv** [comment]
I implement RabbitMQ as Laravel broadcasting driver. Check it: https://github.com/hungntv/laravel-echo-server-with-rabbitmq

I had a mission, deploy a laravel project on Windows Server where can't install Redis officially. That's why I make my github repo. I'm still develop it. Feel free to ask me.
