### ISSUE TITLE
Segmentation Fault on HTTPS

### ISSUE THREAD

**Issue by rodolphovfreire** [tlaverdure/laravel-echo-server#191]
When using laravel-echo-server with encryption (https), nodejs hangs with Segmentation Fault, as below:

![a](https://user-images.githubusercontent.com/7843442/28603619-9d328870-719b-11e7-9ba7-9a663b261e75.png)

Search all over the internet and can not found any answer. Something related with CA Bundle or Intermediate CA can be related with this issue. But I really do not know.

> **laravel-echo-server.json**

> {
> 	"authHost": "https://laravel-host.com",
> 	"authEndpoint": "/broadcasting/auth",
> 	"clients": [],
> 	"database": "sqlite",
> 	"databaseConfig": {
> 		"redis": {},
> 		"sqlite": {
> 			"databasePath": "/database/laravel-echo-server.sqlite"
> 		}
> 	},
> 	"devMode": true,
> 	"host": "laravel-host.com",
> 	"port": "6001",
> 	"protocol": "https",
> 	"socketio": {},
> 	"sslCertPath": "/etc/nginx/ssl/comodo_uva_wildcard_ssl.crt",
> 	"sslKeyPath": "/etc/nginx/ssl/comodo_uva_private_key.key"
> }

**Environment:**
- 2 CPU
- 2 GB RAM
- Node Version: v6.10.3
- NPM Version: 3.10.10
- OS: Linux CentOS 7
- Kernel:  Linux 3.10.0-514.26.2.el7.x86_64

**Comment by duydev1994** [comment]
Have you tried this yet?
https://github.com/tlaverdure/laravel-echo-server/issues/65

**Comment by st0ck53y** [comment]
The socketio documentation states that the default engine is ws, but i think it might actually be using uws instead, as i tried changing it to that to see if it worked, and it still segfaulted. 
If you specify the engine as ws, like so: `"socketio": {"wsEngine": "ws"},` that worked for me.

**Comment by jonnywilliamson** [comment]
@st0ck53y Yeah, its uws

https://github.com/tlaverdure/laravel-echo-server/pull/168

Make a PR to update the docs to help the next person!

**Comment by rodolphovfreire** [comment]
Sorry for the late,

Well, the problem was solved by downloading the NodeJS from https://nodejs.org

> **DO NOT INSTALL** nodejs from EPEL Repository or other repo, it'll crash (Segmentation Fault).

Solution on my environment:

- OS: Linux CentOS 7

- Kernel: Linux 3.10.0-514.26.2.el7.x86_64

`$ sudo yum groupinstall 'Development Tools'`
`$ cd /opt`
`$ curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -`
`$ yum -y install nodejs`

Hope can help...

**Comment by coder-wen** [comment]
@rodolphovfreire  Thanks, work like a charm 😄

**Comment by tlaverdure** [comment]
Can we close this?
