### ISSUE TITLE
Events not picked up on https site

### ISSUE THREAD

**Issue by sarfraznawaz2005** [tlaverdure/laravel-echo-server#193]
Hi thanks for the nice package!

So I have implemented this (without redis and with sync queue) and everything is working fine locally as well as on staging. However on production site which is on `https`, the laravel echo server doesn't seem to pick up the events fired from laravel even though it does get connected to channel as can be seen in this screenshot:

![echo-server](https://user-images.githubusercontent.com/201788/28658172-72b4e588-72c3-11e7-9320-cac7c4f36d71.jpg)

 - My `BROADCAST_DRIVER` is set to `pusher`:

        'pusher' => [
            'driver' => 'pusher',
            'key' => 'f898eefeb26826aa993d13d95b67bafd',
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => '35dc81417bc28b2c',
            'options' => [
                'host' => 'mydomain.com',
                'port' => 3070,
            ],
        ],

- `QUEUE_DRIVER` is set to `sync`

- laravel-echo-server.json

		{
			"authHost": null,
			"authEndpoint": "/broadcasting/auth",
			"clients": [
				{
					"appId": "35dc81417bc28b2c",
					"key": "f898eefeb26826aa993d13d95b67bafd"
				}
			],
			"database": "redis",
			"databaseConfig": {
				"redis": {},
				"sqlite": {
					"databasePath": "/database/laravel-echo-server.sqlite"
				}
			},
			"devMode": true,
			"host": "mydomain.com",
			"port": "3070",
			"protocol": "https",
			"socketio": {},
			"sslCertPath": "/home/mydomain/public_html/file.crt",
			"sslKeyPath": "/home/mydomain/public_html/file.key"
		}

- I am including `io` library like this:

        <script src="//{{ Request::getHost() }}:3070/socket.io/socket.io.js"></script>

 - Echo code:

       if (typeof io !== 'undefined') {
       
          window.Echo = new Echo({
              namespace: 'AgentsApp.Modules.Agentportal.Events',
              broadcaster: 'socket.io',
              host: window.location.hostname + ':3070';
          });

          window.Echo.channel('notification').listen('UserWasLoggedIn', (data) => {
                  alert(data.message);
          })
       }

- Event class:

      class UserWasLoggedIn extends Event implements ShouldBroadcast
      {
          use SerializesModels;

          public $message;

          public function __construct(User $user)
          {
              $this->message = ucwords(strtolower($user->full_name)) . ' just logged into portal.';
          }

          public function broadcastOn()
          {
              return ['notification'];
          }
      }

So this all is working fine locally or on non-https staging site but not on `https`.  On `https` site, the server is connected and also ready to listen to channels as can be seen in above screenshot, it is just that **it doesn't pick up fired events.**

- What I've tried:

  - Tried default port 6001
  - Specified host url in `authHost`, setting this to `null` works too for me locally or staging (non-http).
  - Checked to make sure events are really fired from laravel and they are.

Could it be that I am not using redis but my `database` config is set to it ? I assume not because same conf is working fine on non-http site or locally without even running redis server. Also I assume returning array instead of any channel instance from `broadcastOn` isn't issue either as same works fine locally/staging. I dont know how `appId` and `key` for clients work internally so I am using same on staging and https sites.

Also tried plain socket.io code which also doesn't do anything:

        var socket = io.connect(window.location.hostname + ':' + __port__);
    
        socket.on('connect', function () {
            console.log('io');
    
            socket.on('notification:AgentsApp\\Modules\\Agentportal\\Events\\UserWasLoggedIn', function (data) {
                console.log(data);
            });
        });

So it seems laravel-echo-server is not firing events when on https.

If however, I set `BROADCAST_DRIVER` to `log` or `redis` instead of `pusher`, I can see event details being logged fine.

Also I am not using any pusher.com account because I assume I don't need it because it is working fine on non-https without pusher.com account.

Any idea of what I am missing here or why laravel echo server doesn't pick up fired events on https ?

FYI, I am using laravel 5.1 and everything is working fine on non-https.

Thanks for the help

**Comment by sarfraznawaz2005** [comment]
Anyone ?

**Comment by kenny08gt** [comment]
Same here, do you find any solution?

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Comment by sarfraznawaz2005** [comment]
yes quit a while ago without a solution till today and now suddenly closed, stopped using this package!
