### ISSUE TITLE
leave event is not executed

### ISSUE THREAD

**Issue by sald19** [tlaverdure/laravel-echo-server#195]
Hi, I am try get user is online with private notification channel.

The channel `private-user.{id}.notifications` is only occupied by a user, this way i can verify if the user is online.

The problem is that when I consult the channel through the api and the user reload his browser (**Especially firefox**) very fast, the leave event is not executed

``` http
GET /apps/:APP_ID/channels/:CHANNEL_NAME
```

![nlxvly4](https://user-images.githubusercontent.com/1674971/28989116-ab956ce2-7930-11e7-943d-7a471a31d393.png)

![hmtevm3](https://user-images.githubusercontent.com/1674971/28989146-d5371bb8-7930-11e7-86c9-52548995ccc6.png)

If I close the page, it will always be busy.
![fgvaunj](https://user-images.githubusercontent.com/1674971/28989192-1621c998-7931-11e7-8314-4425f807ed30.png)

**Comment by michgeek** [comment]
Any news on that one?

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
