### ISSUE TITLE
Not able to receive notification

### ISSUE THREAD

**Issue by xparthxvorax** [tlaverdure/laravel-echo-server#196]
Hello,

I'm trying to build a chat application and for that, I'm using Laravel's Echo and Laravel echo server. Idea is to listen for a message notification.

I have done everything according to the:

https://laravel.com/docs/master/notifications

https://laravel.com/docs/master/broadcasting

resources/assets/js/bootstrap.js: (of course I have complied it down using NPM)

```
import Echo from 'laravel-echo'

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
});
```

laravel-echo-server.json:

```
{
	"authHost": "http://laravel-notifications.local",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}
```

ChatController.php (To fire a notification)

`$toUser = User::find($toUser)->notify(new MessageNotification($message));`

MessageNotification.php

```
public function toBroadcast($notifiable)
{
      return new BroadcastMessage([
        'message' => $notifiable,
        ]);
}
```

Blade view( Listening for notification):

```
window.Echo.private('App.User.' + window.Laravel.user.id)
    .notification((notification) => {
        console.log(notification); // Not getting executing 
});
```
When I visit the page, I see following log from the Laravel Echo Server:

```
[9:34:41 AM] - XnmH1wzMJM-5VON-AAAA authenticated for: private-App.User.7
[9:34:41 AM] - XnmH1wzMJM-5VON-AAAA joined channel: private-App.User.7
```

But when I'm firing that notification, I don't see anything logged on the browser console.

Complete source code:

https://github.com/xparthxvorax/Laravel-Notifications

NB: I'm successfully able to listen to the event but not notifications.

**Comment by romrz** [comment]
I'm facing exactly the same issue.

**Comment by romrz** [comment]
This worked for me:

`
Echo.private('App.User.' + window.Laravel.user.id)
    .listen(".Illuminate\\Notifications\\Events\\BroadcastNotificationCreated", (event) => {
    console.log(event);
});
`

**Comment by catalinux** [comment]
in order to debug in browser socket.io messaging you should write this in console: `localStorage.debug = '*';`

then refresh

**Comment by ctf0** [comment]
to broadcast a notification, u need to run a queue [docs](https://laravel.com/docs/5.5/notifications#formatting-broadcast-notifications)

> All broadcast notifications are queued for broadcasting

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
