### ISSUE TITLE
React Native referer bug

### ISSUE THREAD

**Issue by a-komarev** [tlaverdure/laravel-echo-server#197]
When connecting to LES from React Native application server crashes:

```
url.js:81
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at PrivateChannel.authHost (/var/www/node_modules/laravel-echo-server/dist/channels/private-channel.js:21:27)
    at PrivateChannel.authenticate (/var/www/node_modules/laravel-echo-server/dist/channels/private-channel.js:13:23)
    at Channel.joinPrivate (/var/www/node_modules/laravel-echo-server/dist/channels/channel.js:60:22)
    at Channel.join (/var/www/node_modules/laravel-echo-server/dist/channels/channel.js:19:22)
    at Socket.<anonymous> (/var/www/node_modules/laravel-echo-server/dist/echo-server.js:112:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at /var/www/node_modules/socket.io/lib/socket.js:514:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Here is the line:
```
var referer = url.parse(socket.request.headers.referer);
```

I suppose it's a bug at least because server is crashing. There should be try-catch block.

And how to deal with Native apps when they don't have referer?

**Comment by enzonotario** [comment]
I have the same issue. Can you fixed it?

**Comment by enzonotario** [comment]
Sorry. It seems that is a problem with `www` or without it. Now I put the `www` in echo-client and it works.

**Comment by omar10594** [comment]
We have the same problem but with an cordova app.

**Comment by enzonotario** [comment]
I'm using ionic, so it is, more or less, the same thing. 
But I think that the problem is in our configuration, isn't an error of this package.

Realized that if you run the server without any device trying to connect to it, the server doesn't crash. It crash when a client try to connect, and, in my case, was because a wrong configuration.

**Comment by omar10594** [comment]
On an web client that we have, all works great. Same configuration (same code actually, we port the web client to a cordova app).

What configuration did you change to make it work?

**Comment by enzonotario** [comment]
I changed the `script` src in index.html:
`<script type="text/javascript" src="https://www.mydomain.com:6001/socket.io/socket.io.js"></script>`

Before it was without `www`.

Hope it helps you

**Comment by omar10594** [comment]
Thanks, I will try it.

**Comment by enzonotario** [comment]
Hey! sorry but it doesn't resolve the problem. I realized that the problem still exists. I just have it in supervisor so I didn't realized.

I just installed the 1.2 version, that works fine for me.

Hope it helps you.

**Comment by omar10594** [comment]
Yes, 1.2 version work.

I made a pull request #203 that should fix this issue too.

I will use 1.2 version until this is fixed.

**Comment by exzib** [comment]
I am having this issue on my web-server now, I have no idea what is going on, I developed  for a few days, solved all my issues that I had and now I get this:

http://i.imgur.com/H3yFEh6.png

Whatever I do it keeps returning that, and lots of users have their tabs open and I have no idea how to debug it, I debuged it to that line you stated in OP but I can't change it.

Please?
