### ISSUE TITLE
Not work with https server

### ISSUE THREAD

**Issue by jeffersonsetiawan** [tlaverdure/laravel-echo-server#198]
Here is my config:
```
{
	"authHost": "https://foobar.com",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
      			"host": "localhost"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "https",
	"socketio": {},
	"sslCertPath": "/home/ubuntu/www/echo-server/cert.pem",
	"sslKeyPath": "/home/ubuntu/www/echo-server/privkey.pem"
}
```

And the error is:
```
L A R A V E L  E C H O  S E R V E R

version 1.3.0

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

[12:51:41 PM] - j8VEpMDpBnBTfJWSAAAA joined channel: qr-code-detected
laravel-echo-server: ../src/util-inl.h:196: TypeName* node::Unwrap(v8::Local<v8::Object>) [with TypeName = node::TLSWrap]: Assertion `(object->InternalFieldCount()) > (0)' failed.
```

And here is the error from browser console
```
VM49:35 WebSocket connection to 'wss://foobar.com:6001/socket.io/?EIO=3&transport=websocket&sid=ABmVlwKF52USUOOrAAAA' failed: Connection closed before receiving a handshake response
polling-xhr.js:264 GET https://foobar.com:6001/socket.io/?EIO=3&transport=polling&t=LtAkLgg&sid=ABmVlwKF52USUOOrAAAA net::ERR_CONNECTION_REFUSED
polling-xhr.js:264 POST https://foobar.com:6001/socket.io/?EIO=3&transport=polling&t=LtAkMvs&sid=ABmVlwKF52USUOOrAAAA net::ERR_CONNECTION_REFUSED
```
I don't know what happens.

Please help.

**Comment by khuesmann** [comment]
exact same problem here ... 👍

**Comment by jeffersonsetiawan** [comment]
@khuesmann I fix it by updating my NPM.

**Comment by muzafarali** [comment]
getting same error after updating NPM

**Comment by rafwell** [comment]
+1

**Comment by yoyosan** [comment]
@jeffersonsetiawan what do you mean by
> I fix it by updating my NPM.
?

**Comment by catalinux** [comment]
@yoyosan : probably  he updated npm  (`npm update npm -g`) and then reinstalled the dependencies `npm i`

Some old versions of npm did not intall OK the dependencies for this project

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Comment by sahilmushtaq** [comment]
Hi tlaverdure,
Hope you are doing well.

I am using laravel echo server http api for getting active channels. At local its working fine.
Local url
http://localhost:6001/apps/appid/channels?auth_key=...
This is working fine. i allowed cros request in json file at local.

But when i am trying same process on live server then i am getting error 
There was an error connecting to https://abc.pk:6001/apps/appid/channels?auth_key=... 

Live json file

{
	"authHost": "https://abc.pk",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": ".....",
			"key": "......."
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "",
	"port": "6001",
	"protocol": "https",
	"socketio": {},
	"sslCertPath": "/etc/letsencrypt/live/abc.pk/cert.pem",
	"sslKeyPath": "/etc/letsencrypt/live/abc.pk/privkey.pem",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"subscribers": {
		"http": true,
		"redis": true
	},
	"apiOriginAllow":{
		"allowCors" : true,
		"allowOrigin" : "https://abc.pk",
		"allowMethods" : "GET, POST",
		"allowHeaders" : "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	  }
}

Could you please guide me where i am doing mistake. Thanks
