### ISSUE TITLE
Send Subscription Succeeded event to Laravel

### ISSUE THREAD

**Issue by antonkomarev** [tlaverdure/laravel-echo-server#199]
Is there is a way to notify Laravel that exact user has been successfully subscribed?

On user subscription I want to raise an Event in Laravel with sending initial user state to the client.

**Comment by catalinux** [comment]
You could fire events on your channel authorization. Let's say you have

```php
Broadcast::channel( 'App.User.{id}', function ( $user, $id )
{
    return (int) $user->id === (int) $id;
} );
```

You could change into

```php
Broadcast::channel( 'App.User.{id}', function ( $user, $id )
{
    $isAuthorized = (int)$user->id === (int)$id;
    if($isAuthorized === true){
        throw \App\Events\ChannelSubscribed('App.User.{id}', $id);
    }
    return $isAuthorized;
} );

**Comment by tlaverdure** [comment]
Working on a hooks feature https://github.com/tlaverdure/laravel-echo-server/pull/322
