### ISSUE TITLE
Could not start server

### ISSUE THREAD

**Issue by davidsoderberg** [tlaverdure/laravel-echo-server#2]
Hi I could not start server with your provided info.
I get this error:
```
node_modules/laravel-echo-server/dist/echo-server.js:108
    emitPresenceEvents(channel, members, member, action = null) {
                                                        ^

SyntaxError: Unexpected token =
```

**Comment by tlaverdure** [comment]
Hey there. You must be running an older version of node than I am. I removed that default value. Can you please try again?

Thanks

**Comment by joriswa** [comment]
You need to update do node v6.3.1. I was running v4.4.7 and ran into the same issue.

**Comment by tlaverdure** [comment]
Looks like the case and I've noted in the docs.
