### ISSUE TITLE
Get constant error of "Cannot set property 'socketId' of undefined".

### ISSUE THREAD

**Issue by skatetdieu** [tlaverdure/laravel-echo-server#202]
If I connect on a public channel it all works just fine. But if I connect on a presence or private channel I get the following error every time.

> UnhandledPromiseRejectiionWarning: Unhandled promise rejection (rejection id: [some number]): TypeError: Cannot set your property 'socketId' of undefined. 

After which point I no longer receive any events broadcasted to the user. The users are authenticated and joined to listen to the channel but they don't receive any events. 

I am using Laravel Echo Server 1.3 with Laravel 5.4 and Laravel Echo JS

Here is a screen grab of what I get:

[https://ibb.co/kv8Hjv](https://ibb.co/kv8Hjv)

Does @tlaverdure or anyone else know what the issue is or how to resolve this?

**Comment by 4QStudios** [comment]
I'm having the same issue

**Comment by skatetdieu** [comment]
Hi @4QStudios 

I finally managed to figure this out. I looked through the JS files and managed to pin it down to the fact that the code [in this line](https://github.com/tlaverdure/laravel-echo-server/blob/master/src/channels/private-channel.ts#L115) of code having the `try catch` section doesn't actually throw errors if the Laravel channels.php check to who can listen to a channel doesn't return a user model instance as it should. 

Something like this in Channels.php will throw out that error:

```PHP
Broadcast::channel('users', function ($user) {
    if($user->type == 'admin'){
         return $user;
    }else{
         return false;
    }
})
```

Since it's not returning JSON and simply false I think it should log that the response body did not pass the `JSON.parse()` function so you can see that in the terminal. Something like this:

```Typescript
try {
     body = JSON.parse(response.body);
} catch (e) {
     Log.warning('Response body provided is not expected JSON. Response body provided ${response.body}');
     body = response.body;
}
```

This way we can see if Laravel isn't returning a user model instance. 

So when you don't get a user model instance as expected, there is no user object for the code to attach the `sockedId` to because it's undefined. There was never any JSON to make the object with.

I would think the code should stop trying to connect to the presence or private channel if you don't get a user instance either rather than trying to attach a socket ID. 

Anyways, to actually return a user make sure you are logged in [using Laravel's Auth system](https://laravel.com/docs/5.5/authentication). If you didn't use that you might have to do some work around to get it to work. If you are not using it then [this function in Laravel will throw a 403](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php#L51) error because it can't find you to be logged in. 

I had to over write the function that checks the password hash algorithm to a custom algorithm with a provider so I don't mess with the Laravel core and make the user model extend the class Laravel is looking for. 

Then in your channels.php file just make sure what check you're doing you're actually returning the `$user` in the callback function from the auth check the Broadcaster.php file does. Something like this:

```PHP
Broadcast::channel('users', function ($user) {
     return $user;
});
```

That's a super simple private/presence channel but with a logged in user and returning the `$user` this will not throw out this error.

**Comment by 4QStudios** [comment]
I'm using this package for authentication [https://github.com/rydurham/Sentinel](https://github.com/rydurham/Sentinel), will check and get back here

**Comment by skatetdieu** [comment]
Alright @4QStudios . I highly recommend using the [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar) since it will show you whether or not Laravel has you logged in through its Auth system. 

I'm not sure how Sentinel does it at all. But if your login isn't hooking into Laravel's Auth, this is why you're not getting a good response in your Echo server.

**Comment by tlaverdure** [comment]
Thanks for the analysis on this @skatetdieu. I've updated the presence channel in 1.3.3 to not attempt adding a user to a presence channel if there is no data present. 

https://github.com/tlaverdure/laravel-echo-server/blob/ed749a7038f0c663e42cc0de1a2dc862d272a48b/src/channels/presence-channel.ts#L90-L94
