### ISSUE TITLE
Socket is always null

### ISSUE THREAD

**Issue by MJunaidAhmad** [tlaverdure/laravel-echo-server#208]
I am broadcasting the event on a channel in laravel 5.4 (tried both public and private chaanels). 
My log shows the following:

```
[2017-08-22 19:20:56] local.INFO: Broadcasting [App\Events\UserSubscribed] on channels [App.User.1] with payload:
{
    "user": {
        "id": 1,
        "name": "Junaid ahmad",
        "email": "junaid6095@gmail.com",
        "created_at": "2017-08-21 18:45:11",
        "updated_at": "2017-08-21 18:45:11"
    },
    "socket": null
}  
```

I want to confirm is its okay that socket is always null. Also nothing is showing on client side while laravel echo server is working fine.
`[12:20:53 AM] - f8lYwPP3r412D4SPAAAD joined channel: App.User.1
`
Here is client side code: 
```
 window.Echo.channel('App.User.1')
               .listen('.UserSubscribed', (e) => {
           console.log('Got event...');
       console.log(e);
       });

```
And here is the code which I included in bootstrap.js : 
```
import Echo from "laravel-echo"
if (typeof io !== 'undefined') {
    window.Echo = new Echo({
        broadcaster: 'socket.io',
        host: window.location.hostname + ':6001'
    });
}
```

Environment details are as follows:
BROADCAST_DRIVER: log
QUEUE_DRIVER=sync
Running on localhost:8000
node -v
v6.10.2
npm -v
3.10.10

**Comment by tlaverdure** [comment]
Try using the redis BRAODCAST_DRIVER as opposed to the log driver

https://github.com/laravel/framework/blob/91765f5a35a6410d6315042638721242ed0e9c5f/src/Illuminate/Broadcasting/Broadcasters/RedisBroadcaster.php#L92-L96
