### ISSUE TITLE
Cant get around Authentication

### ISSUE THREAD

**Issue by MeeDNite** [tlaverdure/laravel-echo-server#210]
Hi,
I want to run LES on a different server from laravel application.
I created a client with appId and key, but I dont know how to implement this in laravel application to let the authentication be done.
I've searched and found this:
`window.Echo = new Echo({
            broadcaster: 'socket.io',
            host: 'http://les.server:6001',
            auth:
                {
                    headers:
                        {
                            'Authorization': 'Bearer SOMECODE'
                        }
                }
        });`

How can I generate SOMECODE from appId and key?!

Regards,

**Comment by tlaverdure** [comment]
You would need to use something like JWT and setup you broadcasting routes to use the right middleware. You can use Laravel passport to generate the token and it's middleware to secure the broadcasting channels.

https://laravel.com/docs/5.4/passport
