### ISSUE TITLE
Feature request, choice config file

### ISSUE THREAD

**Issue by approached** [tlaverdure/laravel-echo-server#213]
Hi @ all

i have for _prod server_ and _local system_ **separate** config files.

It would be cool, if can say... `server.js start -config local.json`

**Comment by catalinux** [comment]
As hack, we provide another config file during deployment process. 

Usually is a bad practice to keep production config files in main repository

**Comment by approached** [comment]
@catalinux that's true.

**Comment by approached** [comment]
If you have a good deployment process, you doesn't need this function.

**Comment by csiszarattila** [comment]
It has nothing to do with the deployment process, i have fine deployment process, thanks.

The biggest problem is not that the server.js command assumes that your config file named after laravel-echo-server.json, but that its searching only for in current working directory.

Take example for a systemd config. You can't give a full url to the start command ( I dont want to install echo server globally for various reasons)

Then:

`ExecStart=/path/to/my/project/node_modules/laravel-echo-server/bin/server.js start`

It wont find your config file hence wont work. 

A workaround is that you set WorkingDirectory

```
WorkingDirectory=/path/to/my/project/
ExecStart=/node_modules/laravel-echo-server/bin/server.js start
```
But I don't like it.

The option is that give people choose.

But hey, we living in a great world. I can fork and make it work.

**Comment by jonnywilliamson** [comment]
Sorry but I'm having this issue as well, and wondering how you are all doing it.

Say my project has a url of `example.com`

When I'm doing local development (using homestead) my domain is `example.test`, therefore inside my `laravel-echo-server.json` I have the following:

```json
{
	"authHost": "http://exmaple.test",
	"authEndpoint": "/broadcasting/auth",
[....]
}
```

This allows me to do work away locally, and my browser can get events from the `example.test` echo server.

Of course when I push my code to production, it all breaks. I need this in my `laravel-echo-server.json` file:

```json
{
	"authHost": "https://example.com",
	"authEndpoint": "/broadcasting/auth",
[...]
}
```

So at the moment my horrible hack is to have TWO files:

`laravel-echo-server-production.json`
`laravel-echo-server.json`

And have my production script COPY `laravel-echo-server-production.json` to `laravel-echo-server.json` after the push has finished.

I think this is terrible! What is a better idea?

**Comment by csiszarattila** [comment]
As @catalinux suggested its not the best idea to put your config file under version control, because it might contain sensitive information.

I'm doing it by having a sample file, eg.: laravel-echo-server.json.sample in version control, and create a separate version for production, staging etc. on the running environment.
