### ISSUE TITLE
Can this library use with other apllication like ionic.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [tlaverdure/laravel-echo-server#215]
This is not a bug, But i don't know where to ask the question.

Can laravel-echo-server use from other application like ionic, Or How to listen channel and event manually with socket.io-client ?

Thank you.

**Comment by catalinux** [comment]
can you be more specific?

> Can laravel-echo-server use from other application

laravel-echo-server runs by itself. It will manage subscribing on channel from clients.

> How to listen channel and event manually with socket.io-client ?

with socket.io-client you will connect to the server and ask for subscribing to channels for events.

If you want to push some messages on the channel that the server will push them to the clients, you will have to push messages to the redis queue. Server will be notified, and will pass to the subscribed clients

**Comment by ThunderBirdsX3** [comment]
@catalinux Sorry.

I mean, I use `laravel-echo-server` to been a server and connect with Laravel one.
But in other side I want to connect from "ionic" application. And i don't know how to connect or listen to the server.

**Comment by catalinux** [comment]
I am not familiar with ionic apps, but I see you can connect as a client to websocket server:
https://gist.github.com/melvin0008/1453395aa0987531c79c

Use same steps a simple js io-socket example

**Comment by catalinux** [comment]
@ThunderBirdsX3 : did it work?

**Comment by ThunderBirdsX3** [comment]
@catalinux Not sure.
I just fork package 'laravel-echo' then change some thing, And it work well when connect with 'laravel-echo-server'.

This [repo](https://github.com/ThunderBirdsX3/echo).
