### ISSUE TITLE
Can I set authEndpoint when make a connection.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [tlaverdure/laravel-echo-server#217]
I think if I can set `authEndpoint` when make a connection , It will be good when use laravel-echo-server with multiple laravel website connect with laravel-echo-server.

Normal connect with `laravel-echo`.
```
    Echo = new Echo({
      broadcaster: 'socket.io',
      host: 'http://myapp.local:6001'
    });
```
It will set `authHost` and `authEndpoint` in `laravel-echo-server.json` file.
```
  "authHost": "http://mcchat.local/",
  "authEndpoint": "/broadcasting/auth",
```

If I can set `authEndpoint` when make a connect.
```
    Echo = new Echo({
      broadcaster: 'socket.io',
      host: 'http://websocket.local:6001',
      authHost: 'http://myapp2.local/',
      authEndpoint: '/some/uri'
    });
```

**Comment by zmarwa** [comment]
any solution please , i need this feature to make different authentication from different clients!

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
