### ISSUE TITLE
Claims to be listening for redis events, but not doing so

### ISSUE THREAD

**Issue by flxsource** [tlaverdure/laravel-echo-server#218]
I'm using laravel-echo-server with Redis. Broadcast events aren't being picked up by laravel-echo-server - is ideas?

This is being run within a docker network, hence the slightly odd hostnames.

### laravel-echo-server.json
```
{
	"authHost": "php",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "xxxxxxxxxxxxxxxx",
			"key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "redis"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": ""
}
```

### Queue log
```
Horizon started successfully
[2017-09-11 10:35:22] local.INFO: Broadcasting [MyNamespace\MyEvent] on channels [testChannel] with payload: [] [] []
```

### Laravel Echo Server Logs
```
L A R A V E L  E C H O  S E R V E R

version 1.3.1

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

[10:33:17] - zwec8Ey7iqlmib4nAAAB joined channel: testChannel
```

**Comment by anouarabdsslm** [comment]
@flxsource  what do you get within larave echo server logs when you fire an event. does it logged there ?

**Comment by flxsource** [comment]
@anouarabdsslm No, the echo server logs remained empty.

Have now solved this - it turns out that environment variables weren't being transmitted correctly into the docker container, so Laravel was still using the log driver.

Apologies for wasting your time!

**Comment by flxsource** [comment]
@SammyLee666 I was a while ago, so my memory is a little hazy, but I seem to recall using a .env within the container instead of relying on the environment variables set via docker-compose.

**Comment by SammyLee666** [comment]
Thank you very much for your reply. I have already solved it. Thanks again
