### ISSUE TITLE
Response from PHP differs from Postman

### ISSUE THREAD

**Issue by darkgoldblade01** [tlaverdure/laravel-echo-server#219]
Using this package as a replacement for Pusher.

Everything works when using Postman, I get the following back when I manually post to create an event:

```json
{
  "message": "ok"
}
```

However, when I use the app to generate an event, I am getting an error that is blank.

<img width="1713" alt="screen shot 2017-09-12 at 5 44 21 pm" src="https://user-images.githubusercontent.com/9066551/30354556-17633ace-97e2-11e7-95fb-3108b61dec5d.png">

I don't understand what exactly is going on, but it only happens when I use PHP to send the event.

I went into the cURL portion, and even debugged all of that, and it appears to be fine. That is where I got the data I used for Postman.

Any clues?

**Comment by catalinux** [comment]
I think this is not the right place to put this question. Here is the echo-server project. Another driver than pusher. 

Use stackvoverflow .
