### ISSUE TITLE
Error : net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by AEK-BKF** [tlaverdure/laravel-echo-server#221]
I'm running L5.4 application on production server ubuntu 16.04, with nginx server,
Every thing works fine except real time notification :
Laravel-echo-server.json : 
```
{
	"authHost": "http://x.x.x.x", // public ip @
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": false,
	"host": "x.x.x.x", // public ip @
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"verifyAuthPath": true,
    "verifyAuthServer": false
} 
```
App.js :

```
import Echo from 'laravel-echo'

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
})
```

But here the console error :

> GET http://127.0.0.1:6001/socket.io/?EIO=3&transport=polling&t=LwVfo-e net::ERR_CONNECTION_REFUSED 

Please any help ?

**Comment by catalinux** [comment]
Does your laravel echo server runs on the machine?

Pls check: ps aux| grep echo

Does it listen on 6001 port?

lsof-ni :6001

**Comment by catalinux** [comment]
Why dows your socket client tryies to connect to localhost?

Is your production servers'ip 127.0.0.1?

**Comment by AEK-BKF** [comment]
> me$ ps aux| grep echo
> xxx       5463  0.0  1.4 1101936 56096 pts/0   Sl+  09:12   0:00 laravel-echo-server
> xxx      5536  0.0  0.0  12944  1092 pts/1    S+   09:45   0:00 grep --color=auto echo
> 
> me$ lsof -ni :6001
> COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> laravel-e 5463  xxx  12u  IPv4  39263      0t0  TCP *:x11-1 (LISTEN)

**Comment by AEK-BKF** [comment]
Is your production servers'ip 127.0.0.1? 
No, it's my public @

**Comment by catalinux** [comment]
Than make your client js code connect to your server IP

**Comment by AEK-BKF** [comment]
How do I do that ? thanks a lot

**Comment by catalinux** [comment]
Show us the script client side that you connect to websocket?

**Comment by AEK-BKF** [comment]
it's as laravel doc says :
`<script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>`

**Comment by catalinux** [comment]
client-side means browser.

You have to connect to the server

**Comment by AEK-BKF** [comment]
Please explain it ! I followed laravel docs but it doesn't work with me :/

**Comment by anouarabdsslm** [comment]
@AEK-BKF what is the domain name you are using ?

**Comment by AEK-BKF** [comment]
@anouarabdsslm :
I've just a public ip @.
Yes, 6001 port is opened.
Please I'm using nginx, is there a specific config on it ?

**Comment by catalinux** [comment]
Ok, than pleas use you IP for connecting to your echo server, not 127.0.0.1

**Comment by AEK-BKF** [comment]
@catalinux  Could you please show us an example how to deploy L5 mode production with :
Nginx server
Laravel-echo-server
Redis
Socket 
?
Thanks !

**Comment by catalinux** [comment]
Ok. 

Let's say your app is installed on your www.domain.com. On that server your app and also you laravel echo server run.

In your browser you will have something like that

```html
 
<script src="//www.domain.com:6001/socket.io/socket.io.js"></script>
```
and than you need to put compiled version of js

```js
import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
});

```

Try all of this without  https, because things get more complicated

**Comment by catalinux** [comment]
Please, provide html of your client side page

**Comment by catalinux** [comment]
You can find me and other people might help you on https://socketio.slack.com

**Comment by AEK-BKF** [comment]
@catalinux 
Ok thanks for trying help me but I did all what you wrote ...
I need an example with more details for each part of system : nginx, redis, laravel-echo, socket.

:/

**Comment by catalinux** [comment]
Ok, I will try to come up with a minimum viable setup redis laravel-echi socket, but I need a little effort from your side. I ask you twice to share some client code and you did not share.

**Comment by catalinux** [comment]
Let's try to make the most simple setup

First,  you need to make the server RUN.

1. Create a file called laravel-echo-server.json like this
https://gist.github.com/catalinux/3613d61aa020ed5a59476764e51429a7
2. Make sure http://my.domain.com/ is pointed to your laravel app and it is resolved . 
3. Make sure any call to your app route `POST broadcasting/auth` return 200
curl -X POST  'http://my.domain.com/auth/broadcast`
4. Start server in the same dir with the config file `laravel-echo-server start`

Second

Create a  html file in your `public/` folder for example: server.html
and add a compile version of the following js https://gist.github.com/catalinux/ab2e97de0de9d3916aae2a051c751e7c

At this stage your html page should connected to your websocket server. Next step would be to create an event from laravel side .


If you have any problems please share details

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Comment by ulyanaapril** [comment]
Did you start laravel-echo-server with command: laravel-echo-server start ? Or you can create the js file with code: 
var echo = require('laravel-echo-server');
echo.run();
and run this something this: node server.js
