### ISSUE TITLE
Can't make it work in production

### ISSUE THREAD

**Issue by janva255** [tlaverdure/laravel-echo-server#222]
Hi, so i'm trying to get laravel echo server to work on production but i can't

![screenshot_5](https://user-images.githubusercontent.com/13240448/30714558-a2af3890-9ee9-11e7-95d7-876a5bcdfa58.jpg)

```
{
	"authHost": "https://site.com",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "071e0d11945da9a5",
			"key": "73e255898eec05c7a5e762fcf99ecfb7"
		}
	],
	"database": "redis",
	"databaseConfig": {
	    "redis" : {
	      "port": "6379",
	      "host": "127.0.0.1"
	    },
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "https",
	"socketio": {
	    "wsEngine": "uws"
	},
	"sslCertPath": "/etc/letsencrypt/live/site.com/fullchain.pem",
  	"sslKeyPath": "/etc/letsencrypt/live/site.com/privkey.pem"
}
```

![screenshot_4](https://user-images.githubusercontent.com/13240448/30714557-a2ac4996-9ee9-11e7-8261-dc69b9058c70.jpg)

![screenshot_6](https://user-images.githubusercontent.com/13240448/30714772-7aa252e6-9eea-11e7-80fd-b07e7f215dc0.jpg)

![screenshot_7](https://user-images.githubusercontent.com/13240448/30714904-e4f3a2c6-9eea-11e7-964d-dfa18a25210d.jpg)

It starts on dev and listens to everything but can't understand why in production it doesn't work, any help?

**Comment by janva255** [comment]
Changed port to 8443 because of cloudflare and now i'm getting this
#162

**Comment by janva255** [comment]
![screenshot_9](https://user-images.githubusercontent.com/13240448/30720130-9d736a00-9efc-11e7-8efe-0059e04ca938.jpg)

**Comment by catalinux** [comment]
There are too many errors. Could you break down a little your problems?

1. Can your socket.io.js file  be downloaded/opened in yoru browser?
2. Can you try without ssl?

Side question: how do you implement ssl on your sockets?

**Comment by buglinjo** [comment]
I have the same problem. @janva255 can you write down how you fixed this problem?

**Comment by ipabz** [comment]
Has anyone find a solution?

**Comment by khalilst** [comment]
Didn't work in cloudflare for me.
