### ISSUE TITLE
 Pre-built binaries not found for sqlite3@3.1.11 and node@8.4.0

### ISSUE THREAD

**Issue by larsbadke** [tlaverdure/laravel-echo-server#224]
/usr/local/bin/laravel-echo-server -> /usr/local/lib/node_modules/laravel-echo-server/bin/server.js

> uws@0.14.5 install /usr/local/lib/node_modules/laravel-echo-server/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

sh: 1: cannot create build_log.txt: Permission denied

> sqlite3@3.1.11 install /usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.11 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'clean' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | linux | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | linux | x64
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.4.0
gyp verb command install [ '8.4.0' ]
gyp verb install input version string "8.4.0"
gyp verb install installing version: 8.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.4.0
gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/build'
gyp ERR! System Linux 4.4.0-96-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.0-96-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.37
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by larsbadke** [comment]
I've installed node v7.10.1, and now it works. Thanks

**Comment by JordanDalton** [comment]
This problem also exists with Node 8.8.1. I did what @larsbadke did and downgraded to 7.10.1 and things are working now.
