### ISSUE TITLE
private channel not working

### ISSUE THREAD

**Issue by lighter** [tlaverdure/laravel-echo-server#225]
I want to create a private channel with JWT auth, but it does not work. I created a [laravel-echo][1] server. Thank your help!!

This is my **MainController**

    class MainController extends Controller
    {
        ... 
    
        public function index()
        {
            return \View::make('main/index')->render();
        }
    
        public function sendTestMessage()
        {
            event(new TestBroadcasting(date('Y-m-d H:i'), '123456'));
            return 'ok';
        }
    }

**TestBroadcasting**

    <?php
    
    namespace App\Events;
    
    use Illuminate\Broadcasting\Channel;
    use Illuminate\Queue\SerializesModels;
    use Illuminate\Broadcasting\PrivateChannel;
    use Illuminate\Broadcasting\PresenceChannel;
    use Illuminate\Foundation\Events\Dispatchable;
    use Illuminate\Broadcasting\InteractsWithSockets;
    use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
    
    class TestBroadcasting implements ShouldBroadcast
    {
        use Dispatchable, InteractsWithSockets, SerializesModels;
        private $testMessage;
        private $receiverId;
    
        public function __construct($testMessage, $receiverId)
        {
            $this->testMessage = $testMessage;
            $this->receiverId = $receiverId;
        }
    
        public function broadcastOn()
        {
            // return 'testChannel.' . $this->receiverId; // it's work!!!
            return new PrivateChannel('testChannel.'  . $this->receiverId);
        }
    
        public function broadcastWith()
        {
            return ['testMessage' => $this->testMessage];
        }
    }

**resources/assets/js/bootstrap.js**

    import * as io from 'socket.io-client';
    window.io = io;
    import Echo from 'laravel-echo';
    
    window.Echo = new Echo({
      broadcaster: 'socket.io',
      host: window.location.hostname + ':6001',
      auth:
        {
          headers:
            {
              'Authorization': 'Bearer ' + jwtToken
            }
        }
    });

**BroadcastServiceProvider.php**

    <?php
    
    namespace App\Providers;
    
    use Illuminate\Support\ServiceProvider;
    use Illuminate\Support\Facades\Broadcast;
    
    class BroadcastServiceProvider extends ServiceProvider
    {
        /**
         * Bootstrap any application services.
         *
         * @return void
         */
        public function boot()
        {
            Broadcast::routes(['middleware' => ['api', 'jwt.auth']]);
    
            require base_path('routes/channels.php');
        }
    }

**channels.php**

    Broadcast::channel('testChannel.{id}', function () {
        return true;
    });

**index.blade.php**

    window.Echo.private('testChannel.123456')
        .listen('TestBroadcasting', (e) => {
            console.log(e);
        });

**laravel-echo-server.json**

    {
      "appKey": "blablablabla",
      "authEndpoint": "/broadcasting/auth",
      "authHost": "http://localhost",
      "devMode": false,
      "port": "6001",
      "database": "redis",
      "databaseConfig": {
        "redis": {
          "port": "6379",
          "host": "redis",
          "password": "blablablabla"
        }
      },
      "protocol": "http",
      "referrers": [],
      "sslCertPath": "",
      "sslKeyPath": "",
      "verifyAuthPath": true,
      "verifyAuthServer": false
    }

  [1]: https://github.com/tlaverdure/laravel-echo-server

**Comment by catalinux** [comment]
Your laravel echo server needs to be able to check you laravel app. Do you see any logs in your webserver for auth endpoints?  What status code do they send back?

You should run your laravel-echo-server in DEBUG mode to see more details.

Also set client  also in debug mode to have more verbose logs

**Comment by lighter** [comment]
I found the problem. Because I use JWT auth, my auth is not corrected.
