### ISSUE TITLE
Laravel 5.3 / Redis / Socket.IO / Laravel-Echo private channels

### ISSUE THREAD

**Issue by pdroge84** [tlaverdure/laravel-echo-server#226]
Hi,

I've been trying all weekend to get this working but after pulling alot of hair out i've stopped trying and going to ask here.

I've got a laravel project running in which i wish to have Redis with socket.io and laravel-echo working.
I got this all working with public channels no problem at all. Now i wish to have it working with private channels aswell, here comes the fun part, I can't get it to work.

After googling alot I still can't seem to find THE solution to my problem. I'll try to explain what I've got so far:

laravel-echo-server.json
```json
{
	"authHost": "http://192.168.10.10",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "***",
			"key": "***"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "192.168.10.10",
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": ""
}
```

BroadcastServiceProvider.php boot method
``` php
public function boot()
    {
        Broadcast::routes();

        Broadcast::channel('tenant_id.*', function ($user, $tenant_id) {
            return true;
        });
    }
```

My event
``` php
class ProgressUpdated implements ShouldBroadcast
{
    use SerializesModels;

    public $tenantId;
    public $data;

    public function __construct($tenant_id)
    {
        $this->tenantId = $tenant_id;

        $this->data = array(
            'power'=> '10'
        );
    }

    public function broadcastOn()
    {
        return ['tenant_id.' . $this->tenantId];
    }
}
```

In the blade head:
```html
<meta name="csrf-token" content="{{ csrf_token() }}">
```

In my Vue template (script part)
``` javascript 
import Echo from "laravel-echo";
```

and in it's ready
```javascript
window.Echo = new Echo({
                broadcaster: 'socket.io',
                host: 'http://192.168.10.10:6001'
            });
```

and inside an method that does an API call first to define what the tenant_id is:
``` javascript
var channelName = 'tenant_id.' + _this.integration.tenant_id;
                    window.Echo.private(channelName).listen('ProgressUpdated', (e) => {
                        console.log(e.data.power);
                    });
```

gulp runs fine, no issues there.

Whenever i got to the page to subscribe to the channel, laravel-echo-server returns the following messages:
[11:36:56 AM] - BOpvHckeCQxfph8QAAAC could not be authenticated to private-tenant_id.1
Client can not be authenticated, got HTTP status 500

Could anyone please help me.

Thanks in advance.
Kind regards,
Pim Dröge

**Comment by catalinux** [comment]
Check  your logs for a PHP error. As it says in your logs: there is a 500 error.

Check in your web server logs for auth end points. Is there 500 status?

**Comment by pdroge84** [comment]
@catalinux 
This is the error in the log:
`
[2017-09-25 11:36:56] testing.ERROR: Illuminate\Session\TokenMismatchException in /home/vagrant/Code/application/bootstrap/cache/compiled.php:3314
Stack trace:
#0 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#2 /home/vagrant/Code/application/bootstrap/cache/compiled.php(13749): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#3 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 /home/vagrant/Code/application/bootstrap/cache/compiled.php(12155): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /home/vagrant/Code/application/bootstrap/cache/compiled.php(13495): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/vagrant/Code/application/bootstrap/cache/compiled.php(13432): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8356): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8347): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#17 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8338): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#20 /home/vagrant/Code/application/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#26 /home/vagrant/Code/application/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#27 {main}  
`

**Comment by tlaverdure** [comment]
If you are using JWT, you need to use the right middleware. By default, the Broadcast routes utilize the web middleware. You need to set this up differently based on how your users will be authenticated.

https://laravel.com/docs/5.5/broadcasting#defining-authorization-routes

**Comment by pdroge84** [comment]
@tlaverdure 
Sorry for asking but how do i check if that is being used? This project has been build by someone else and I'm continuing on his development.

The original developer is on vacation as we speak so no way to ask him this.

I'm fairly new to the whole Laravel business so any help would be appriciated.

**Comment by akkhan20** [comment]
private channels require you to authenticate incoming user and in the authentication method u have return true or false, i’m not sure where it has to be done because i used this package a while ago so may be someone who is still into this package can guide you clearly where u have to do what

**Comment by catalinux** [comment]
@pdroge84 : you can get inspired from here: https://laravel.io/forum/10-09-2016-howto-broadcasting-laravel-echo-laravel-echo-server-and-jwt

**Comment by pdroge84** [comment]
@catalinux 

After changing 
``` php
        Broadcast::routes();
```

To:
``` php
        Broadcast::routes([ 'middleware' => [ 'api', 'jwt.auth' ] ]);
```

and changing

``` javascript
            window.Echo = new Echo({
                broadcaster: 'socket.io',
                host: 'http://192.168.10.10:6001'
            });
```

to
``` javascript
            var token = $('meta[name=csrf-token]').attr('content');

            window.Echo = new Echo({
                broadcaster: 'socket.io',
                host: 'http://192.168.10.10:6001',
                auth:
                    {
                        headers:
                            {
                                'Authorization': 'Bearer ' + token
                            }
                    }
            });
```

I still get 500 error with this in the Log:
`[2017-09-25 14:48:43] testing.ERROR: ReflectionException: Class jwt.auth does not exist in /home/vagrant/Code/application/bootstrap/cache/compiled.php:1479
Stack trace:
#0 /home/vagrant/Code/application/bootstrap/cache/compiled.php(1479): ReflectionClass->__construct('jwt.auth')
#1 /home/vagrant/Code/application/bootstrap/cache/compiled.php(1433): Illuminate\Container\Container->build('jwt.auth', Array)
#2 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2011): Illuminate\Container\Container->make('jwt.auth', Array)
#3 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10064): Illuminate\Foundation\Application->make('jwt.auth')
#4 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10177): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#10 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8356): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8347): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8338): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/vagrant/Code/application/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 /home/vagrant/Code/application/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 {main}  
[2017-09-25 14:48:43] testing.ERROR: ReflectionException: Class jwt.auth does not exist in /home/vagrant/Code/application/bootstrap/cache/compiled.php:1479
Stack trace:
#0 /home/vagrant/Code/application/bootstrap/cache/compiled.php(1479): ReflectionClass->__construct('jwt.auth')
#1 /home/vagrant/Code/application/bootstrap/cache/compiled.php(1433): Illuminate\Container\Container->build('jwt.auth', Array)
#2 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2011): Illuminate\Container\Container->make('jwt.auth', Array)
#3 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2529): Illuminate\Foundation\Application->make('jwt.auth')
#4 /home/vagrant/Code/application/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#5 {main} `

So it seems I'm not even using this JWT authentication or what so ever.

**Comment by catalinux** [comment]
So it seams. jwt auth can be made with

https://github.com/tymondesigns/jwt-auth

**Comment by pdroge84** [comment]
But why should i use that? 

The reply from @taylorotwell  states: 

> If you are using JWT, you need to use the right middleware. By default, the Broadcast routes utilize the web middleware. You need to set this up differently based on how your users will be authenticated.

> https://laravel.com/docs/5.5/broadcasting#defining-authorization-routes

However apparently i'm not using JWT so that is not the reason of my problem.

**Comment by catalinux** [comment]
True. Your are don't have to.  It's an option only.

I think in your first log errors, your problem was the lack of csrf in the headers

`VerifyCsrfToken` ....


Try to disable for a little bit csrf middleware and see if it works. If it works, than you shoul try to send csrf as headers when auth (same like the jwt example)

**Comment by pdroge84** [comment]
As stated here https://laravel.io/forum/11-14-2014-disabling-the-csrf-middleware-in-laravel-5 I've disabled the VerifyCsrfToken and tried again. But yet again no result. It's still not working.

@tlaverdure 
Could this issue be reopened again as it's not solved yet...

**Comment by tlaverdure** [comment]
My guess is that this CSRF issue is cookie/domain related. The echo client sends cookie data from to the echo server and in turn that could be used to authenticate. But that will only work if your cookie is created on the same domain.

I remember seeing something similar here:
https://github.com/tlaverdure/laravel-echo-server/issues/184

**Comment by pdroge84** [comment]
I've done what was sald19 said in the issue

> 
> solved with share Cookie domain
> 
> in config/session.php set
> 
> 'domain' => '.laravel.com',  //keep the dot

Sadly it didn't work. 

I'm completely lost now...

**Comment by pdroge84** [comment]
Guess I'll start with a clean slate and try from scratch. Any good guide which I can follow to setup Laravel 5.3 on homestead with Redis, Laravel Echo, Socket.IO, Laravel Echo Server?

Thanks in advance.

**Comment by pdroge84** [comment]
Had one more last try and i started the server in full debug and this was the output:

`
  engine intercepting request for path "/socket.io/" +52s
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=LwwcmSr" +0ms
  engine handshaking client "InuVl_nKLVicTc6iAAAA" +2ms
  engine:socket sending packet "open" ({"sid":"InuVl_nKLVicTc6iAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}) +2ms
  engine:socket sending packet "message" (0) +1ms
  engine:polling setting request +1ms
  engine:socket flushing buffer to transport +0ms
  engine:polling writing "97:0{"sid":"InuVl_nKLVicTc6iAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}2:40" +2ms
  engine:socket executing batch send callback +6ms
  socket.io:server incoming connection with id InuVl_nKLVicTc6iAAAA +0ms
  socket.io:client connecting to namespace / +2ms
  socket.io:namespace adding socket to nsp / +2ms
  socket.io:socket socket connected - writing packet +5ms
  socket.io:socket joining room InuVl_nKLVicTc6iAAAA +2ms
  socket.io:socket packet already sent in initial handshake +1ms
  socket.io:socket joined room InuVl_nKLVicTc6iAAAA +1ms
  engine intercepting request for path "/socket.io/" +10s
  engine handling "POST" http request "/socket.io/?EIO=3&transport=polling&t=LwwcopA&sid=InuVl_nKLVicTc6iAAAA" +1ms
  engine setting new request for existing client +1ms
  engine:polling received "128:42["subscribe",{"channel":"private-tenant_id.1","auth":{"headers":{"X-CSRF-TOKEN":"omhLcLuDbvGKX6PDrf5058HBaaTV8TwRwLhaWt9h"}}}]" +4ms
  engine:socket packet +1ms
  socket.io-parser decoded 2["subscribe",{"channel":"private-tenant_id.1","auth":{"headers":{"X-CSRF-TOKEN":"omhLcLuDbvGKX6PDrf5058HBaaTV8TwRwLhaWt9h"}}}] as {"type":2,"nsp":"/","data":["subscribe",{"channel":"private-tenant_id.1","auth":{"headers":{"X-CSRF-TOKEN":"omhLcLuDbvGKX6PDrf5058HBaaTV8TwRwLhaWt9h"}}}]} +2ms
  socket.io:socket got packet {"type":2,"nsp":"/","data":["subscribe",{"channel":"private-tenant_id.1","auth":{"headers":{"X-CSRF-TOKEN":"omhLcLuDbvGKX6PDrf5058HBaaTV8TwRwLhaWt9h"}}}]} +2ms
  socket.io:socket emitting event ["subscribe",{"channel":"private-tenant_id.1","auth":{"headers":{"X-CSRF-TOKEN":"omhLcLuDbvGKX6PDrf5058HBaaTV8TwRwLhaWt9h"}}}] +5ms
  socket.io:socket dispatching an event ["subscribe",{"channel":"private-tenant_id.1","auth":{"headers":{"X-CSRF-TOKEN":"omhLcLuDbvGKX6PDrf5058HBaaTV8TwRwLhaWt9h"}}}] +2ms
  engine upgrading existing transport +31ms
  engine:socket might upgrade socket transport from "polling" to "websocket" +4ms
  engine intercepting request for path "/socket.io/" +2ms
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=LwwcopB&sid=InuVl_nKLVicTc6iAAAA" +1ms
  engine setting new request for existing client +0ms
  engine:polling setting request +1ms
  engine:ws received "2probe" +1ms
  engine:ws writing "3probe" +2ms
  engine:socket writing a noop packet to polling for fast upgrade +104ms
  engine:polling writing "1:6" +0ms
  engine:ws received "5" +7ms
  engine:socket got upgrade packet - upgrading +0ms
  engine:polling closing +2ms
  engine:polling transport discarded - closing right away +1ms
⚠ [7:54:46 PM] - InuVl_nKLVicTc6iAAAA could not be authenticated to private-tenant_id.1
`

**Comment by pdroge84** [comment]
Anyone?

**Comment by darrynten** [comment]
I had something similar happen to me with private channels.

I managed to fix it and [submitted a patch](https://github.com/laravel/framework/pull/22207).

Try out the code change to see if it resolves your problem.
