### ISSUE TITLE
Emit Events from Client

### ISSUE THREAD

**Issue by tlaverdure** [tlaverdure/laravel-echo-server#23]
Some events may need to be published from the client. 

https://github.com/laravel/echo/pull/43#issuecomment-246120370

**Comment by vesper8** [comment]
+1!

**Comment by fiveanddone** [comment]
Currently working on a presentation application that would benefit from emitting my scroll wheel position.  If I could bypass larval for this, everybody wins!

**Comment by barryvdh** [comment]
Fixed with #100
