### ISSUE TITLE
Events from Redis coming through as "undefined"

### ISSUE THREAD

**Issue by smcgovern** [tlaverdure/laravel-echo-server#231]
First off, great tool.  Definitely what I was looking for.

I have ran into an issue, when I run the server it is detecting items that are getting pushed to Redis channels, and it's appropriately echoing out the channel's name, but the event data comes through as "undefined".  The data, as far as I know, is JSON encoded.

Below is console log:

> L A R A V E L  E C H O  S E R V E R
> 
> version 1.3.2
> 
> ⚠ Starting server in DEV mode...
> 
> ✔  Running at localhost on port 8080
> ✔  Channels are ready.
> ✔  Listening for http events...
> ✔  Listening for redis events...
> 
> Server ready!
> 
> Channel: tick
> Event: undefined
> CHANNEL tick

Any tips or clue? I've been itching my head over this.

Thanks!

**Comment by smcgovern** [comment]
Ah now I feel silly.

In case anyone ever runs into such an issue I had to change what I was doing:
```
Redis::publish('tick', $msg);
```

to:
```
$data = json_decode($msg, 1);
Redis::publish('tick', json_encode(array('event' => $data)));
```

**Comment by nhitze** [comment]
Thx @smcgovern that saved me hours
