### ISSUE TITLE
getting error 404 when trying to  authenticated to private-notif_owner.2

### ISSUE THREAD

**Issue by djellalmohamedaniss** [tlaverdure/laravel-echo-server#232]
hello guys am getting an error when i try to authenficate a user i dont know the reason :/
here is my code : 
- this is the broadcastOn function on the event class
```php
 public function broadcastOn()
    {
        return new PrivateChannel('notif_owner.'.$this->publication_id);
    }
```
- this is the broadcast rule : 
```php
Broadcast::channel('notif_owner.{id_publication}', function ($user, $id_publication) {
     return true;
    //return (int) $user->id === (int) Publication::find($id_publication)->user_id;
});
```
- and this is the listen in the app.js ( am using 2 just for testing ) : 
```php
import Echo from 'laravel-echo'
let e = new Echo({
    broadcaster : 'socket.io',
    host : window.location.hostname + ':6001'
})
e.private('notif_owner.2')
    .listen('CommentForUserEvent', (e) => {
        console.log(e);
    })
```
- and finally the authhost : "authHost": "http://localhost:8000"

please need help :'( thank you

**Comment by catalinux** [comment]
Your laravel app listens on port 8000?

**Comment by djellalmohamedaniss** [comment]
yes its on 8000

**Comment by catalinux** [comment]
You should be trying to make auth calls from your rest client of your own to debug your code.  You could use postman to makle suck call son your  router auth path

`POST {{url}}/broadcasting/auth`

cu body:
{
  "channel-name": "my-channel"
}

**Comment by djellalmohamedaniss** [comment]
still not working :/ so sad stucked on this for 2 days

**Comment by catalinux** [comment]
contact me on socketio.slack.com

**Comment by lukepolo** [comment]
Did you ever fix this.

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
