### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by synkyo** [tlaverdure/laravel-echo-server#233]
Hi,

I am getting the following error when trying to connect to presence channels:

`(node:4556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot set property 'socketId' of undefined`

### I am using
- Laravel 5.4.36
- Laravel Echo Server 1.3.2
- Laravel Echo 1.3.2
- Redis 4.0.2

### Notes
- I am using the Laravel auth system with Entrust for permissions
- Debugbar shows the correct user authenticated
- Public and Private channels do not produce this error
- I have just implemented this on another project using Laravel 5.5.* which was also using Laravel Echo Server and it works fine on that, however that was a more greenfield project.
- BroadcastServiceProver is enabled
- I've tried Laravel Echo Server version 1.3.0 and 1.3.1 and also get the same issue.

I've had a look through google and issues within the board and tried a few things but it seems I am not having any luck.

**Comment by redhedded1** [comment]
Yes, I'm still having the same problem as described above with Presence channels. Private channels work fine. I too am using Laravel authentication.

channels.php
`Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});

Broadcast::channel('messages.{chatId}', function ($user, $chatId) {
     if($user->canJoinChat($chatId)) {
        return $user;
     }
});
`
Setting a breakpoint with xdebug on the if statement in the second block never gets hit.

**Comment by redhedded1** [comment]
Can anyone point to an example or give a nudge in the right direction? I've been working on getting this to work on and off for weeks. I'm not sure why the socket id is null, when it prints it out in dev mode. I am assuming that is why the Promise is false. Any help would be appreciated...

**Comment by tlaverdure** [comment]
This error gets thrown when your channel doesn't return a user object.

```php
Broadcast::channel('messages.{chatId}', function ($user, $chatId) {
     if($user->canJoinChat($chatId)) {
        return $user;
     }
});
```

When you are joining your presence channel, have you verified that `$user` is actually set?

`\Log::info('user', [$user]);`

**Comment by redhedded1** [comment]
Yes, a temporary modification of the LES js files allows me to log out the body of the response.

```
log_1.Log.error("[" + new Date().toLocaleTimeString() + "] - body " + body); L A R A V E L  E C H O  S E R V E R

version 1.3.2

⚠ Starting server in DEV mode...

✔  Running at 127.0.0.1 on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

socket >>>
socket serverRequest >>>
[2:06:45 PM] - 6NKPiLmHPLdQk-khAAAA authenticated for: presence-messages.1
[2:06:45 PM] - body {"id":1,"name":"Larry Ball","email":"larry@larryaball.net","created_at":"2017-11-07 20:23:53","updated_at":"2017-11-07 20:23:53"}
res >>>
[2:06:45 PM] - 6NKPiLmHPLdQk-khAAAA joined channel: presence-messages.1
(node:32282) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'socketId' of undefined
```

**Comment by tlaverdure** [comment]
Could there possibly be two attempts occurring here? Looks you are successfully joining the channel.

**Comment by redhedded1** [comment]
I don't mean to be ignorant, but I console.log the method in my javascript (Vue) that joins the channel and it only fires once. I set the debugger on channels.php in the plain Laravel install and it never reaches the breakpoint for the channel. So I am really confused by this.

```
<?php
use Illuminate\Support\Facades\Log;

/*
|--------------------------------------------------------------------------
| Broadcast Channels
|--------------------------------------------------------------------------
|
| Here you may register all of the event broadcasting channels that your
| application supports. The given channel authorization callbacks are
| used to check if an authenticated user can listen to the channel.
|
*/

Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
Broadcast::channel('messages.{chatId}', function ($user) {
	Log::info('user', [$user]);
	return $user;
});
```
I set a breakpoint on both return statements just to be sure. Neither was hit. 

I console.log socket in LES js files and get null in the following locations:

dist/channels/channel.js
```
Channel.prototype.joinPrivate = function (socket, data) {
        log_1.Log.error('socket >>> ', socket);
        var _this = this;
        this.private.authenticate(socket, data).then(function (res) {
            log_1.Log.error('res >>> ', res);
            socket.join(data.channel);
            if (_this.isPresence(data.channel)) {
                var member = res.channel_data;
                try {
                    member = JSON.parse(res.channel_data);
                }
                catch (e) { }
                _this.presence.join(socket, data.channel, member);
            }
            _this.onJoin(socket, data.channel);
        }, function (error) {
            log_1.Log.error(error.reason);
            _this.io.sockets.to(socket.id)
                .emit('subscription_error', data.channel, error.status);
        });
    };
```
/dist/channels/private-channel.js
```
PrivateChannel.prototype.serverRequest = function (socket, options) {
        var _this = this;
        return new Promise(function (resolve, reject) {
            options.headers = _this.prepareHeaders(socket, options);
            log_1.Log.error('socket serverRequest >>> ', socket.id);

            var body;
            _this.request.post(options, function (error, response, body, next) {
                if (error) {
                    if (_this.options.devMode) {
                        log_1.Log.error("[" + new Date().toLocaleTimeString() + "] - Error authenticating " + socket.id + " for " + options.form.channel_name);
                    }
                    log_1.Log.error(error);
                    reject({ reason: 'Error sending authentication request.', status: 0 });
                }
                else if (response.statusCode !== 200) {
                    if (_this.options.devMode) {
                        log_1.Log.warning("[" + new Date().toLocaleTimeString() + "] - " + socket.id + " could not be authenticated to " + options.form.channel_name);
                        log_1.Log.error(response.body);
                    }
                    reject({ reason: 'Client can not be authenticated, got HTTP status ' + response.statusCode, status: response.statusCode });
                }
                else {
                    if (_this.options.devMode) {
                        log_1.Log.info("[" + new Date().toLocaleTimeString() + "] - " + socket.id + " authenticated for: " + options.form.channel_name);
                    }
                    try {
                        log_1.Log.error("[" + new Date().toLocaleTimeString() + "] - body " + body);
                        body = JSON.parse(response.body);
                    }
                    catch (e) {
                        body = response.body;
                    }
                    resolve(body);
                }
            });
        });
    };
```
Admittedly I am not familiar with the code and these console.logs could be worthless, but I include them in case they are useful. Thank you for your responses as well.

**Comment by tlaverdure** [comment]
You check your log file in `/storage/logs/laravel.log`?

**Comment by redhedded1** [comment]
Yes, nothing there.

**Comment by redhedded1** [comment]
Also I am able to send messages fine from the presence channel. I just don't get the join/leave events I'm after.

**Comment by redhedded1** [comment]
Does anyone have an example of presence channels working in Laravel 5.5?

**Comment by tthdvd** [comment]
@redhedded1 We have the same issue here, We don't get the join/leave events.Has anyone some solution for this bug?

**Comment by redhedded1** [comment]
I haven't gotten a response since it was suggested to check the Laravel logs. The only event I get is one for subscribing to a channel.

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Comment by saaagar** [comment]
Please check if your BROADCAST_DRIVER is set to redis on .env file
