### ISSUE TITLE
Configuring Laravel-echo server: 401 error

### ISSUE THREAD

**Issue by synfony** [tlaverdure/laravel-echo-server#235]
I am trying to configure the Laravel-echo-server with Redis server. Laravel version is 5.5.

The laravel-echo-server.json file got created with app-id and app-key.
Now when I am trying to send request to the echo server I am using:

import Echo from "laravel-echo";
window.RedisEcho = new Echo({
        broadcaster: 'socket.io',
        host: 'http://localhost.com:3000',
        auth: {
                headers: {
                    Authorization: 'Bearer ' + AUTH_API_TOKEN,
                },
            },
});

My question is: **Which token should I use for the Bearer auth_api_token?** I am getting "error: client cannot be authenticated, got HTTP status 401 "

The laravel-echo server and redis is running fine on my localhost. Here is the laravel-echo-server.json file:
{
	"authHost": "http://dawgtired.unleash.solution/",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "my-xxx-app-id",
			"key": "my-kk-app-key"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
                        "port": "6379",
			"host": "127.0.0.1"},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "3000",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"apiOriginAllow": {
		"allowCors": true,
		"allowOrigin": "http://localhost.com:3000",
		"allowMethods": "GET, POST",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
}

**Comment by tlaverdure** [comment]
If you are using an auth middleware that supports tokens like Laravel Passport you need to setup the configure the broadcast routes to use that middleware. https://laravel.com/docs/5.5/broadcasting#authorizing-channels

**Comment by renatosistemasvc** [comment]
same problem here. Can you solve it?
