### ISSUE TITLE
Client can not be authenticated, got HTTP status 301

### ISSUE THREAD

**Issue by ahmedemad2051** [tlaverdure/laravel-echo-server#237]
i got this error with https protocol but it work well with http

laravel echo server.json

{
        "authHost": "https://rawahi.com",
        "authEndpoint": "/broadcasting/auth",
        "clients": [
                {
                        "appId": "cbef825d44deaee9",
                        "key": "121f629d8e3f771dedb27209bf655306"
                }
        ],
	"database": "redis",
        "databaseConfig": {
                "redis": {
                },
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
        "devMode": false,
        "host": null,
        "port": "6010",
        "protocol": "https",
        "socketio": {},
        "sslCertPath": "/home/rawahi/ssl/certs/rawahi_com_95088_ca039_1517073692_372492c5388944fa2eb03f.crt",
        "sslKeyPath": "/home/rawahi/ssl/keys/95088_ca039_0f53adad7e02032e37c6.key",
        "sslCertChainPath": "",
        "sslPassphrase": "",
        "apiOriginAllow": {
                "allowCors": true,
                "allowOrigin": "https://rawahi.com",
                "allowMethods": "GET, POST",
                "allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
        }
}

bootstrap.js

import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
});

broadcastServiceProvider

  public function boot()
    {
        Broadcast::routes(['middleware'=>['web','auth']]);

        require base_path('routes/channels.php');
    }

how can i fix this problem?
Thanks

**Comment by ekadesign** [comment]
first time set devMode parametr to true, and execute this command laravel-echo-server start. And see logs

**Comment by smaqeelkazmi** [comment]
I'm also facing the same issue, **Client couldn't be authenticated to private channel, got HTTP status 301**.
Working correctly on local server but the issue is only on the production server.

**Comment by khalidabi** [comment]
@ahmedemad2051 
did u find a solution ?

**Comment by khalidabi** [comment]
@smaqeelkazmi  did u find a slution?

**Comment by khalidabi** [comment]
@tlaverdure  could help on this matter. I am also facing this issue
