### ISSUE TITLE
How do you send event back to server?

### ISSUE THREAD

**Issue by exzib** [tlaverdure/laravel-echo-server#238]
I am building a chat module now for my site and I have completed it except the sending.

So my ideal chat module would work like sending an event from the client to the server which then Laravel listens after and when it gets triggered it will handle the event and distribute out the message to both users and log it in the database.

How do I send an event from the client? And how do I listen for it? I find 0 resources or information on how this is done.

I guess I could send the message using ajax but that kinda ruins the whole socket thing and it isn't really optimal for a website with 20000 users.

Any information on how to do this?

For example my JS code could look something like this:

```
   $(".msg-input").keypress(function (e) {
        if($(this).val().replace(/^\s+|\s+$|\s+(?=\s)/g, "")!="") {
            if (e.which == 13) {
                if($(this).data("dest")!=""){
                    socket.emit('message', {"to":$(this).data("dest"),"msg":$(".msg-input").val() });
                    $(this).val("");
                }
            }else {
                x++;
                if(x==1) {
                    if ($(this).data("dest") != "") {
                        socket.emit('typing', {"to": $(this).data("dest")});
                        x=0;
                    }
                }
            }
        }
    });
```

`socket.emit('message', {"to":$(this).data("dest"),"msg":$(".msg-input").val() });`

The above line should send an event like one I made in laravel, like so: event(new EventName('Message here', 'userid') and then I could handle it in an listener from there.

Got any tips on how to achieve this?

**Comment by mostafaznv** [comment]
I need some information about this matter too.
but i didn't find any documentation/information ...

if is there anybody who can help, he will save my life :D

**Comment by tlaverdure** [comment]
There currently is not any support for sending messages to the server and having your Laravel application listen for those events. If you have some ideas on how to do that securely I would submit a PR.

**Comment by mostafaznv** [comment]
any other idea to fire events from client?
is there any other package?
I want to implement a small chat system and it's important to fire events client side.

**Comment by wajdijurry** [comment]
For who still searching for a solution to send an event from client side, here is an example using Pusher:
```
<script>
    // Sending message
    const my_push = new Pusher("{appKey}", {
        cluster: 'mt1',
        wsHost: window.location.hostname,
        wsPort: 6001,
        forceTLS: false,
        disableStats: true,
        authEndpoint: '/broadcasting/auth',
        auth: {
            headers: {
                'Accept': 'application/json',
                'csrf-token': '{csrf_token}',
                'Authorization': 'Bearer {JWT}',
            }
        }
    });
    var channel = my_push.subscribe('private|public-{channel_name}');
    channel.bind('pusher:subscription_succeeded', function() {
        channel.trigger('{event_name}', event_data_as_object );
    });
```

**Comment by AbolfazlAkhtari** [comment]
> 

And how do you listen it in laravel?
