### ISSUE TITLE
Are broadcasted events queued till client joins the channel?

### ISSUE THREAD

**Issue by slashsBin** [tlaverdure/laravel-echo-server#240]
Hi
Can anyone tell me when an Event(Ex. with payload: "message: hi") was broadcasted to a Private Channel(Ex. `private-user.1`), and the specified user is not online in the channel, does the broadcasted event gets lost? or It's queued until user joins the channel?

I'm using:
-  laravel 5.5 with redis broadcast driver
-  laravel-echo-server with redis
-  laravel echo on client

Everything is fine when the user is on the channel when event was broadcasted, but not when user hasn't joined the channel yet.

**Comment by catalinux** [comment]
If there is no subscriber to that specific channel there won't be any  broadcasting event.

**Comment by slashsBin** [comment]
So is this flow correct:

1. An Event is fired within Laravel to be Broadcasted on "private-user.1" Channel
2. Laravel will queue the Event on Redis
3. Laravel Horizon(or `php artisan queue:work`) will Publish the Event to Queue "private-user.1" on Redis
4. Echo-Server Subscribes to Channel "private-user.1" on Redis **only when** Requested by Client
5. Client(Laravel Echo) Connects to Echo-Server and joins the Channel "private-user.1"
6. **Only then** Client Recieves the Event

**Comment by slashsBin** [comment]
could you please verify this flow?

**Comment by josteph** [comment]
@slashsBin Queue will send to user that is currently subscribed to that private channel. You use axios post to store the message in database, so doesn't matter if other user is not active in that private channel.

**Comment by slashsBin** [comment]
thanks for reply.

**Comment by slashsBin** [comment]
@Kunsect Apparently horizon will **not** wait till client joins the channel, instead when a queued event gets processed it will be broadcasted to any **current** registered users on channels.

**Comment by Kunsect** [comment]
@slashsBin thx.

**Comment by erlangp** [comment]
@slashsBin thanks
