### ISSUE TITLE
Server down status

### ISSUE THREAD

**Issue by lilian21** [tlaverdure/laravel-echo-server#241]
Hi,
   I need to make this echo server restart automatically whenever the production server gets restarted. I have in mind a cron job which checks, somehow, if laravel echo server is down. If true => start it, otherwise do nothing. Is there any command which tells the status of echo server? I tried with `laravel-echo-server status` but it doesn't return anything, either started or stopped. 
Thank you,
Lilian

**Comment by catalinux** [comment]
You could try user supervisord


Your config for supervisord would be:

```
[program:echo_server]
directory=/path/of/your/laravel_echo_server..json/
command=/usr/bin/laravel-echo-server start
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/log/echoserver.log
