### ISSUE TITLE
Is it safe to deploy laravel-echo-server on a public facing server (internet)?

### ISSUE THREAD

**Issue by jorgenb** [tlaverdure/laravel-echo-server#242]
Or should I stick it behind a proxy (e.g. nginx)?

**Comment by antoniopaisfernandes** [comment]
Safe is a relative term :)

I've been running one for months (dockerized). I've done through a proxy (apache) and now directly.

Go for it!

P.S. - as for everything you have on the internet, you'll need to be vigilant (security issues and stuff)

**Comment by catalinux** [comment]
@jorgenb : 
 
I use nginx in front as it makes easier with ssl and also your client don't have to connect to exotic ports.

**Comment by jorgenb** [comment]
@catalinux Do you use the same nginx server as your Laravel project or do you use a dedicated server?

**Comment by catalinux** [comment]
Same. You can have your websock path as your app path also , so you don't have to handle any CORS issues

**Comment by catalinux** [comment]
Something like that: https://stackoverflow.com/questions/39310308/how-to-use-laravel-echo-on-production-server-with-https/43047046#43047046

**Comment by jorgenb** [comment]
Thanks @catalinux  I was just writing some Nginx config before you posted that. The SO post probably saved me some time since I did not know about WebSocket proxying.

http://nginx.org/en/docs/http/websocket.html
