### ISSUE TITLE
POST http://localhost/broadcasting/auth 404 (Not Found) error

### ISSUE THREAD

**Issue by nriddhi** [tlaverdure/laravel-echo-server#243]
I am trying to make my app connecting to pusher on a private channel.

But I am getting the following error in console:

> _POST http://localhost/broadcasting/auth 404 (Not Found) Pusher : Couldn't retrieve authentication info. 404Clients must be authenticated to join private or presence channels_

**ChatEvent.php**
```
<?php

namespace App\Events;

use App\User;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class ChatEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;


   public $message;
   public $user;



    public function __construct($message, User $user)
    {

       $this ->message = $message;

        $this ->user = $user;


    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('chat');
    }
}

```
**App.js**
```
/**
 * First we will load all of this project's JavaScript dependencies which
 * includes Vue and other libraries. It is a great starting point when
 * building robust, powerful web applications using Vue and Laravel.
 */

require('./bootstrap');

window.Vue = require('vue');

import Vue from 'vue'
import VueChatScroll from 'vue-chat-scroll'
Vue.use(VueChatScroll)

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */

Vue.component('example', require('./components/Example.vue'));

Vue.component('chat-message', require('./components/ChatMessage.vue'));


const app = new Vue({
    el: '#app',

   data:{ 

    message:'',

     chat:{     

        message:[]

     } 

      },

   methods: {  send() { 

if(this.message.length !=0)
{

    this.chat.message.push(this.message);

    this.message= '';

}
   } },


   mounted()

   {

       Echo.private('chat')
    .listen('ChatEvent', (e) => {
        console.log(e.order.name);
    });

   } 

});
```
**channels.php**
```
<?php



Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});


Broadcast::channel('chat', function() {

return true;

});
```
**ChatController.php**

```
<?php

namespace App\Http\Controllers;

use App\Events\ChatEvent;
Use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class ChatController extends Controller
{


  public function __construct()

    {
        $this->middleware('auth');
    }


  public function chat()


  {

 return view('chat');

}


//public function send(Request $request)

//{

 // $user = User::find(Auth::id());

 // event(new ChatEvent($request -> $message, $user));

//}


public function send()

{

    $message = "Hello";

  $user = User::find(Auth::id());

  event(new ChatEvent( $message, $user));

}

}
```
**bootstrap.js**

```
window._ = require('lodash');

/**
 * We'll load jQuery and the Bootstrap jQuery plugin which provides support
 * for JavaScript based Bootstrap features such as modals and tabs. This
 * code may be modified to fit the specific needs of your application.
 */

try {
    window.$ = window.jQuery = require('jquery');

    require('bootstrap-sass');
} catch (e) {}

/**
 * We'll load the axios HTTP library which allows us to easily issue requests
 * to our Laravel back-end. This library automatically handles sending the
 * CSRF token as a header based on the value of the "XSRF" token cookie.
 */

window.axios = require('axios');

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

/**
 * Next we will register the CSRF Token as a common header with Axios so that
 * all outgoing HTTP requests automatically have it attached. This is just
 * a simple convenience so we don't have to attach every token manually.
 */

let token = document.head.querySelector('meta[name="csrf-token"]');

if (token) {
    window.axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;
} else {
    console.error('CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token');
}

/**
 * Echo exposes an expressive API for subscribing to channels and listening
 * for events that are broadcast by Laravel. Echo and event broadcasting
 * allows your team to easily build robust real-time web applications.
 */

import Echo from 'laravel-echo'

 window.Pusher = require('pusher-js');

 window.Echo = new Echo({
     broadcaster: 'pusher',
     key: '815bcd2378a647ffaad7',
      cluster: 'ap2',
    encrypted: false
 });
```
what may be the cause for this error? any solution

**Comment by bozhkos** [comment]
Inside your config/app.php uncomment line with         App\Providers\BroadcastServiceProvider::class,

**Comment by nriddhi** [comment]
yes, i have uncommented this, any help, i am becoming frustrated about this.

**Comment by omar10594** [comment]
You could use the artisan command to see if the route was register.

Also you could check if you need change the group or any other config of the route.

https://laravel.com/docs/5.5/broadcasting#authorizing-channels

> The Broadcast::routes method will automatically place its routes within the web middleware group; however, you may pass an array of route attributes to the method if you would like to customize the assigned attributes:

**Comment by kennblvnp** [comment]
Has this been fixed?

@nriddhi

**Comment by nriddhi** [comment]
no

**Comment by josteph** [comment]
@nriddhi Why are you using pusher with laravel-echo-server? You can integrate echo with pusher without this...

Make sure your BROADCAST_DRIVER is set to pusher, and QUEUE_DRIVER is set to sync (if you are not implementing queue).

PS: You need to specify PUSHER credentials in .env file.

**Comment by jamahlmd** [comment]
fixed yet? I have the same issue.

**Comment by patrickbennett** [comment]
@jamahlmd I had this issue, and it turns out I was logged out of the app and didn't realize it. Make sure you are logged in and your session is active.

**Comment by pthien92** [comment]
@jamahlmd @nriddhi 
I encountered this issue as well. Here below are steps I fixed it:
1. Do a route recaching after uncomment App\Providers\BroadcastServiceProvider::class
  `php artisan route:cache`
2. Log out all of your session and log in again

**Comment by deliaahm** [comment]
Anoyone can help me? I had same issues, i got this error : POST http://localhost:8000/send 500 (Internal Server Error)
I checked Developer tools and error is : 
TokenMismatchException - in VerifyCsrfToken.php (line 68).
I added csrf token in my view, but still error

**Comment by deliaahm** [comment]
*anyone

**Comment by Skintillion** [comment]
Something might be causing your token to refresh. Like an ajax request?

**Comment by deliaahm** [comment]
public function send(request $request)
    {
        $user = User::find(Auth::id());
        $this->saveToSession($request);
        event(new ChatEvent($request->message,$user));
    }

**Comment by lukepolo** [comment]
Did anyone ever fix this?

**Comment by insteadsoftwares** [comment]
I think think if you are not using a normal server on local host like wamp or xamp you shoold try this:
"authHost": "http://localhost/your-app-name/public",
"authEndpoint": "/broadcasting/auth",
Hope this helps

**Comment by razvysb93** [comment]
add:
`Broadcast::routes();`
to /your project /routes/web.php

**Comment by Asadlaravel** [comment]
still the error exit please help

**Comment by hoffenheimtech** [comment]
In my own case i added
authEndpoint: "../broadcasting/auth",

In Your own case maybe you should add 
authEndpoint: "broadcasting/auth",

It worked for me that way.

**Comment by k01yasik** [comment]
Try this:

1. Uncomment `App\Providers\BroadcastServiceProvider::class` in `config/app.php`
2. Use `php artisan config:cache`
3. Use `php artisan route:cache`
4. Check new route `broadcasting/auth` with `php artisan route:list`
![route-list](https://user-images.githubusercontent.com/2293885/47729672-aa37d100-dc71-11e8-9ca6-8f19954f652e.jpg)
5. Run `laravel-echo-server start` and check output.
![laravel-echo](https://user-images.githubusercontent.com/2293885/47730055-68f3f100-dc72-11e8-9beb-b119281ad00d.jpg)

**Comment by Asadlaravel** [comment]
![github](https://user-images.githubusercontent.com/38780235/47735286-132d4200-dc8e-11e8-8ce1-a84b52b80a83.png)
![image](https://user-images.githubusercontent.com/38780235/47735441-57204700-dc8e-11e8-9975-73ed3aa26112.png)

**Comment by Asadlaravel** [comment]
![image](https://user-images.githubusercontent.com/38780235/47735522-7dde7d80-dc8e-11e8-9739-cad235ed013b.png)
but still not working

**Comment by Asadlaravel** [comment]
finally fixed thank you so much

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Comment by AkhilRaj003** [comment]
I got this resolved when used http://127.0.0.1:8000 instead of localhost by starting Laravel development server.

use 'php artisan serve' to start laravel server

**Comment by alexanderlinjin** [comment]
@k01yasik thanks,it's work

**Comment by shramiknakarmi** [comment]
> I think think if you are using a normal server on localhost like wamp or xamp you shoold try this:
> "authHost": "http://localhost/your-app-name/public",
> "authEndpoint": "/broadcasting/auth",
> Hope this helps

where do add these lines ??

**Comment by tirta-keniten** [comment]
Uncomment ``Broadcast::routes();`` in ``app/Providers/BroadcastServiceProvider.php``.

**Comment by Stakvino** [comment]
Some people will have this error because they didnt change the default route (/pusher/auth) used by pusher.js to '/broadcasting/auth'. you can acheive this by adding authEndpoint option :

`var pusher = new Pusher('your key here', 
{
    
        authEndpoint: '/broadcasting/auth',
        auth: {
            headers: {
                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            }
        },
        cluster: 'your cluster here',
        encrypted: true,
});`

**Comment by retry19** [comment]
> @jamahlmd @nriddhi
> I encountered this issue as well. Here below are steps I fixed it:
> 
> 1. Do a route recaching after uncomment App\Providers\BroadcastServiceProvider::class
>    `php artisan route:cache`
> 2. Log out all of your session and log in again

thanks, it's work

**Comment by AlexioVay** [comment]
If you use Jetstream with Livewire try 

`Broadcast::routes(['middleware' => 'auth:sanctum']);`

on your `boot` method in `BroadcastServiceProvider.php`.

**Comment by erickson1999** [comment]
You need modify the code of this 

**channels.php**
`<?php
Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
Broadcast::channel('chat', function() {
return true;
});`

to this

`<?php
Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
Broadcast::channel('chat{id}', function() {
return true;
});`

it is necessary to have an identifier in the route when it is a private channel.

Hope this can help you :)
