### ISSUE TITLE
Firefox can’t establish a connection to the server at wss://...

### ISSUE THREAD

**Issue by ThunderBirdsX3** [tlaverdure/laravel-echo-server#244]
I got this error.

> Firefox can’t establish a connection to the server at wss://my.site.com:6001/socket.io/?EIO=3&transport=websocket&sid=fAuiKDiXpkhOoSndAAAD.

What is it.

**Comment by M0H3N** [comment]
@ThunderBirdsX3 
did you solve this issue ? I have such a problem

**Comment by ThunderBirdsX3** [comment]
@M0H3N Sorry. I can't remember. What did I do in that time. Are you solved it?

**Comment by M0H3N** [comment]
@ThunderBirdsX3  No the error still happens
