### ISSUE TITLE
echo-server not subscirbe event because of config redis password 

### ISSUE THREAD

**Issue by alexli0707** [tlaverdure/laravel-echo-server#248]
After some work in my dev env, I got this work perfectly . But when I  push myproject to online env,I got this problem. It can auth ,but not subscribe event.This is my config.

```
{
	"authHost": "http://luck.fight-platform.newgamer.cn",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "xxxxx",
			"key": "xxxxxx"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {"port":"6479","host":"10.117.186.86","options.db":"1","options.password":"xxxxxx"}
	},
	"devMode": true,
	"host": "luck.fight-platform.newgamer.cn",
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": ""

}
```

It can auth and join channel like 

```
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...
[4:45:28 PM] - UeSgfkdY0rZe8hDGAAAR authenticated for: private-user.10144
[4:45:28 PM] - UeSgfkdY0rZe8hDGAAAR joined channel: private-user.10144
```
But not receive publish event 

```
10.117.186.86:6479[1]> publish private-user.1     "{\"event\":\"user.update\",\"data\":{\"username\":\"JohnDoe\"}}"
(integer) 0
```

**Comment by catalinux** [comment]
What version of  library do you use?

What  event are your listening for?

There was a problem of event naming on between some versions and a `nmp i` might install diferent versions on `dev` vs `prod`: https://github.com/laravel/echo/issues/147

**Comment by alexli0707** [comment]
Thanks for replying.
My web server use the version of 1.3.3 and my local machine use the version of 1.3.1. I just listening for cutsom event which implement according laravel's broadcasting tutorial and it worked fine in dev env.

**Comment by catalinux** [comment]
As you see, there were changes made. You have to adapt your event naming.

To test in good way, please update your `dev` environment with latter version : 1.3.3

**Comment by alexli0707** [comment]
Thanks a lot ,I went to seen your issue,it save my time!!!

**Comment by catalinux** [comment]
If you have still problems paste your `listen` line from `js`  and your `broadcastAs` method from `php`

**Comment by alexli0707** [comment]
After downgrade to 1.3.1 still cannot work,this is my code.

```
new Vue({
        el: '#app1',
        data: {
            users: ['11'],
        },
        mounted: function () {
            window.Echo.private('user.10144').listen('.user.update', function (e) {
                console.log(e);
                this.users.push(e.userId)
            }.bind(this));
        }
    })
```

```
public function broadcastAs()
    {
            return 'user.update';
    }
```

**Comment by alexli0707** [comment]
After I test version 1.3.3 in local `dev` .It also worked fine,so I don't think is laravel-echo-server's version problem.

**Comment by alexli0707** [comment]
Finnally I found the problem ,the database's redis passwordconfig not work!

```
"databaseConfig": {
		"redis": {"port":"6579","host":"172.25.1.111","options.db":"0","options.password":"xxxx"}
	},
```

After I remove password everythind goes fine.
