### ISSUE TITLE
Hi All. Can some help me how to set this up on a shared hosting?

### ISSUE THREAD

**Issue by danmarkl** [tlaverdure/laravel-echo-server#250]
Good day to all :)

Can someone help me how to setup this on a shared hosting (GoDaddy)? Given that I can't use the port 6001 because I am only on a shared hosting (limited ports to use).

Any help or ideas is welcome and much appreciated!

Thanks!

**Comment by catalinux** [comment]
You can user proxypass for nginx

https://stackoverflow.com/questions/39310308/how-to-use-laravel-echo-on-production-server-with-https/43047046#43047046

I am sure that apache has something similar

**Comment by danmarkl** [comment]
Hi @catalinux 

Thanks for the idea. I'll try this one.
