### ISSUE TITLE
Error: EACCES: permission denied, open '/etc/letsencrypt/live/site-name.com/fullchain.pem'

### ISSUE THREAD

**Issue by solancer** [tlaverdure/laravel-echo-server#251]
I'm trying to get the echo server to work in HTTPS mode but it fails to start and returns with an error that it can't access the SSL certs. 

I could do a chown but since the certs get renewed every 3 months I would have to copy them to another location and change the permissions or something like that.

Any suggestions?

![screen shot 2017-12-08 at 1 11 57 am](https://user-images.githubusercontent.com/800668/33735377-1c96dfa2-dbb5-11e7-9df3-7c50ce31913c.png)

`cat laravel-echo-server.json`

```
{
	"authHost": "https://sitename.com/",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "https",
	"socketio": {},
	"sslCertPath": "/etc/letsencrypt/live/sitename.com/fullchain.pem",
	"sslKeyPath": "/etc/letsencrypt/live/sitename.com/privkey.pem",
	"verifyAuthPath": true,
        "verifyAuthServer": false
}
```

**Comment by rafwell** [comment]
Try `chown yourusername /etc/letsencrypt/live/ -R`.

**Comment by neetin** [comment]
@solancer I have having same issue, did you solve it?

**Comment by solancer** [comment]
@neetin I ended up creating a reverse proxy and mapped basepath/socket.io to port 6001

**Comment by neetin** [comment]
@solancer can you please share some sample to create a reverse proxy. thanks!

**Comment by solancer** [comment]
@neetin  here the piece of configuration from my virtual host, since I'm force redirecting all non-http requests to https I've added the rewrite module reverse proxy in the ssl virtual host file created by certbot

```
RewriteEngine On
RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
RewriteCond %{QUERY_STRING} transport=websocket    [NC]
RewriteRule /(.*)           ws://localhost:6001/$1 [P,L]
ProxyPass        /socket.io http://localhost:6001/socket.io
ProxyPassReverse /socket.io http://localhost:6001/socket.io
```


You need to enable ProxyPass & ProxyPassReverse in apache2 for this to work

**Comment by neetin** [comment]
Thanks @solancer 
Your concept worked.
I have been using nginx instead of apache. Here is the config for nginx. It would help others who are using nginx.

`location ~* \.io {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;

      proxy_pass http://localhost:6001;
      proxy_redirect off;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
`

**Comment by rocramer** [comment]
Thanks for sharing! What change did you make in your laravel-echo-server.json when using the proxy approach?

**Comment by neetin** [comment]
@rocramer I have not modified default config of laravel-echo-server.json.
I used http instead of https so it did not require SSL cert paths.

**Comment by gileneusz** [comment]
@neetin 
Isn't it unsafe solution to use http instead of https? If it is an option to use https and ssl keys for laravel-echo-server - they should be used. I've found this solution : 
https://komelin.com/articles/realtime-apps-laravel-echo-tips-and-tricks

but I cant make permissions right

**Comment by rocramer** [comment]
@gileneusz No, it shouldn't be unsafe. Your client should connect via https to your proxy server. Only the connection between your proxy and echo server communicates in an internal network via http.

**Comment by manu144x** [comment]
I have this exact same crappy issue.

Echo server runs perfectly fine if I start it manually. However when I start it under supervisor, it tells me it has permission denied to read the letsencrypt certificates.

In supervisor I configured it to run under www-data, and I made www-data owner master and god of the entire letsencrypt folder, but to no avail.

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
