### ISSUE TITLE
Listen not working

### ISSUE THREAD

**Issue by Juliaandavid** [tlaverdure/laravel-echo-server#253]
Hi there,

I was following laravel's documentation and, but I have a problem, try in all possible ways to use this:

```
  Echo.channel('ChannelTest').listen('EventTest', function (data) {
    console.log(data);
  });
```

But never work, however I was reviewing the server code and found the `on` method like this:

```
  Echo.channel('ChannelTest').on('EventTest', function (data) {
    console.log(data);
  });
```

and you know what? this works, I don't know why, the question is: Is this a normal behavior or is it wrong?

I'm not using redis neither pusher, im using http way.

**Comment by redhedded1** [comment]
you won't get any help here man

**Comment by decodedmrq** [comment]
Reference this issue: https://github.com/tlaverdure/laravel-echo-server/issues/214
