### ISSUE TITLE
'laravel-echo-server' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by AbdulWahab007** [tlaverdure/laravel-echo-server#256]
After installing npm install -g laravel-echo-server command
when i want to run this above command "laravel-echo-server init"
it shows the following error
'laravel-echo-server' is not recognized as an internal or external command,
operable program or batch file.

any help????

**Comment by skatetdieu** [comment]
I would recommend closing and opening whatever command line window you're using. Sometimes commands aren't added until the window is restarted.

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
