### ISSUE TITLE
Notice the HTTP application server when users subscribe, unsubscribe the presence channel, or disconnect the socket

### ISSUE THREAD

**Issue by eddiclin** [tlaverdure/laravel-echo-server#257]
Can we get some notices in the HTTP application server when users subscribe, unsubscribe the presence channel, or disconnect the socket?
I have created a H5 game which is combined with the real world devices. It has a player queue feature. Users can be enqueue if other one is playing. When game over, the system will notice the next user that it is his turn. So if someone who is in the queue disconnect the socket or close the web page directly, I want to discover him as soon as possible, and pop him out of the queue, and notice the next one to begin play the game.
Because I have 500 devices, if using the cron job to polling the users in the presence channel by the http-api of laravel-echo-server, I think it's a heavy job.

**Comment by eddiclin** [comment]
I think we can point some channels that users join and leave the laravel-echo-server can notice the HTTP application server. These channels can be set by config or http-api.
Any ideas?

**Comment by msonowal** [comment]
@eddiclin 
You need to subscribe to that events in Redis directly or in your app server to Redis

**Comment by eddiclin** [comment]
Could you tell me more detail? Which events should I subscribe?

**Comment by eddiclin** [comment]
@msonowal 
I think that laravel-echo-server will subscribe channels of Redis, and the app server can publish some events for it by Redis. laravel-echo-server will broadcast the events' message for corresponding sockets.
But when the user disconnects the socket, or unsubscribes channels, laravel-echo-server cannot notify the app server. This is what I hope can be solved.

Do you mean the app server must connect to laravel-echo-server and subscribe some presence channels like H5 users, so that the app server can be notified when someone leaving?

**Comment by msonowal** [comment]
@eddiclin 
Yes I mean exactly that
```
subscribe some presence channels like H5 users
```
based on the events the channels that is used to manage by echo server
those channels need to be subscribed

**Comment by eddiclin** [comment]
If so there will subscribe so many presence channels in app server. Now one game device has at least two presence channels. So I must at least subscribe 500 X 2 = 1000 channels in app server ?

Can we solved it by HTTP ? When a user disconnects socket, or unsubscribes channels, make echo-server to notify app server through HTTP. It is just like the authenticate request which is from echo-server to app server.

**Comment by eddiclin** [comment]
@msonowal 
If so there will subscribe so many presence channels in app server. Now one game device has at least two presence channels. So I must at least subscribe 500 X 2 = 1000 channels in app server ?

Can we solved it by HTTP ? When a user disconnects socket, or unsubscribes channels, make echo-server to notify app server through HTTP. It looks like a logout request, as same as the authenticate request which is from echo-server to app server.

**Comment by msonowal** [comment]
@eddiclin 
You can subscribe to pattern like wildcard so you dont have to create subscribers for all channels
e.g.
`PSUBSCRIBE game_rooms.*`
so it will listen to all events on the channels and based on the payload you can execute your logics

**Comment by eddiclin** [comment]
@msonowal 
I don't think so. As above mentioned, my app server will 

> subscribe some presence channels like H5 users

so its role is a socket.io client, it connects echo-server, and subscribe channels by socket, not by Redis.
So I can't use `PSUBSCRIBE game_rooms.*`

**Comment by msonowal** [comment]
@eddiclin 
I get you point but your laravel app server can subscribe to Redis through which it will know who left or joined etc by which it will solve your problem.

**Comment by eddiclin** [comment]
@msonowal 
Unless change the source code, I cannot using this way to solve my problem. I have read [the source code](https://github.com/tlaverdure/laravel-echo-server/blob/master/src/channels/presence-channel.ts#L125), the `leave` action does not publish anything by Redis.

**Comment by MarcHef** [comment]
@eddiclin 
you have any solution? i need the same. thx

**Comment by eddiclin** [comment]
No, just planning. I think we can add a event feedback mechanism about making a event notice to callback the HTTP API when users subscribe, unsubscribe the presence channel or disconnect sockets.

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
