### ISSUE TITLE
getaddrinfo ENOTFOUND https://project.app

### ISSUE THREAD

**Issue by pderiy** [tlaverdure/laravel-echo-server#26]
![image](https://cloud.githubusercontent.com/assets/9549383/18412790/1e5b7078-7798-11e6-9347-8c1b6ce2a352.png)

`{
	"appKey": "90mf4eojc6ogu4sfpg4g12i9escptj68p1qg2iu34rmnr09d58lj7f5h4j4g",
	"authEndpoint": "/broadcasting/auth",
	"authHost": null,
	"database": "sqlite",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": false,
	"host": "https://project.app",
	"port": "6001",
	"referrers": [
		{
			"host": "pasta-masta.app",
			"apiKey": "44ter5dm3isq6p89f8s1ufufkfo4jddun22ijbga617sedige4lsj9c8mc0r"
		}
	],
	"sslCertPath": "/home/user/.valet/Certificates/pasta-masta.app.crt",
	"sslKeyPath": "/home/user/.valet/Certificates/pasta-masta.app.key"
}
`

The problem is with host attribute. It works without "https://" prefix. But I need SSL.

**Comment by tlaverdure** [comment]
Is that immediately after startup? Or did you try and perform an action that caused that to occur?

**Comment by tlaverdure** [comment]
Your ssl files also don't match your host.

**Comment by pderiy** [comment]
It happens just after startup. 
Just try to add https prefix and you will have same problem.
Ssl files does match my host. I wanted to change my host url, but forget to change ssl files names.

**Comment by sgtaziz** [comment]
I'm experiencing the same problem as well. My host matches my crt and key. Using ```"host": "https://dev.horizonservers.net"```
Was working fine prior to updating to 1.0

**Comment by sgtaziz** [comment]
It also causes the same issue when writing http://. 
After looking into it, it seems like the http module doesn't like protocols in its options. I temporarily fixed it by removing "https://" and "http://" in options.host under the httpServer function in server.js.

**Comment by Thaars** [comment]
I'm using MAMP to manage my hosts, so a non-port-80-request is not handled by MAMP. That means, the host doesn't exist. But Node is checking for the existence and throws an error. 

The Server.serverProtocol() method is setting the secure flag by checking the host option. Without https:// in the host option, it will always start a http server. 

I changed the condition to (this.options.protocol == 'https') to determine if a http or a https server should be used. The https:// prefix is not needed in the host option anymore.

That works for me.

**Comment by jonnywilliamson** [comment]
@Thaars 

Just confirming you mean you changed this line https://github.com/tlaverdure/laravel-echo-server/blob/master/src/server.ts#L49

To 

```
if (this.options.protocol == 'https') {
```

Then you dropped using any protocol in the json file for the `host` key so it looks like this?

```
{
        "appKey": "",
        "authEndpoint": "/broadcasting/auth",
        "authHost": "http://example.com",
\\<snip>
        "devMode": false,
        "host": "example.com",
        "port": "6001",
}

```


Thanks!

**Comment by Thaars** [comment]
No, the protocol option is still needed, but you don't need the protocol in the host option anymore. This is a part of my json config.
```json
{
    "host": "example.local",
    "port": "6001",
    "protocol": "https"
}
```

**Comment by jonnywilliamson** [comment]
Although I wrote it wrong above, (now fixed) that's actually what I meant in the first place! 😆 

Thank you!

**Comment by pderiy** [comment]
@jonnywilliamson can you add PR?

**Comment by pderiy** [comment]
@tlaverdure [this](https://github.com/tlaverdure/laravel-echo-server/issues/26#issuecomment-246209590l) answer fixed my issue

**Comment by jonnywilliamson** [comment]
@pderiy Sure https://github.com/tlaverdure/laravel-echo-server/pull/46

**Comment by tlaverdure** [comment]
Merge. @pderiy let me know if that closes this.

**Comment by pderiy** [comment]
It works great. Thank you guys.

@tlaverdure , @jonnywilliamson

**Comment by kokokele** [comment]
you havenot host for '127.0.0.1 localhost'
