### ISSUE TITLE
Scaling echo server

### ISSUE THREAD

**Issue by gl3nda85** [tlaverdure/laravel-echo-server#260]
Hi can someone please point me in the right direction to scale this software package with nginx?

thanks

**Comment by catalinux** [comment]
can you share some details?

do you have many nginx instances and many laravel echo servers?

You could start using 
https://stackoverflow.com/questions/39310308/how-to-use-laravel-echo-on-production-server-with-https/43047046#43047046

**Comment by gl3nda85** [comment]
Hey, I have tried that using forge and it was slow to provision, I was hoping to setup a custom elastic beanstalk image or something. I don’t have any specifics but I am allowed to use what ever software stack is the easiest. I was just wondering if anyone has actually tried it

**Comment by lukepolo** [comment]
Its just a socket.io server, so you can follow this : https://socket.io/docs/using-multiple-nodes/

**Comment by gl3nda85** [comment]
you can mark this as closed, i have scaled it using AWS elasticbeanstalk with docker.
