### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by Jamesking56** [tlaverdure/laravel-echo-server#261]
Everytime I try and run `laravel-echo-server` I get:

`Error: Cannot find module '/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v59-darwin-x64/node_sqlite3.node'`

**Comment by rbourque** [comment]
I'm getting the same error.   It worked last week until I refreshed my libraries using 'npm upgrade'

**Comment by maokeyang** [comment]
make sure  node is  x64 , not x86

**Comment by rbourque** [comment]
Yes, it is the 64 bit installation.  $ which node.exe
/c/Program Files/nodejs/node.exe

**Comment by rbourque** [comment]
I deleted the `c:\Users\<userprofile>\AppData\Roaming\npm\node_modules\laravel-echo-server` directory and re-ran the command `npm install -g laravel-echo-server` and everything started to work again.

**Comment by tlaverdure** [comment]
Looks like sqlite doesn't have support for Node 8 yet. So for the time being, sqlite has been moved to a peer dependency and will need to be installed separately if you are using sqlite as a data store. Installing 1.3.6 should fix.
