### ISSUE TITLE
Laravel Echo Presence Channel + Sentinel authentication error 500

### ISSUE THREAD

**Issue by TacuaraTechnologies** [tlaverdure/laravel-echo-server#262]
Hi, i tried every possible combination of configs but i can't get the authentication to work

this is the error:

<table class="trace-details">
                                <thead class="trace-head"><tr><th>
                                    <h3 class="trace-class">
                                        <span class="text-muted">(1/1)</span>
                                        <span class="exception_title"><abbr title="ErrorException">ErrorException</abbr></span>
                                    </h3>
                                    <p class="break-long-words trace-message">preg_match(): Compilation failed: nothing to repeat at offset 1</p>
                                </th></tr></thead>
                                <tbody><tr><td><span class="block trace-file-path">in <a title="/var/www/monchis3/adminv2/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php line 96"><strong>Broadcaster.php</strong> (line 96)</a></span></td></tr>

and this is my setup:

{
	"authHost": "https://admin.monchis.com.py",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "09575d2d96d63a17",
			"key": "e22e1295e0bbeef02906b75e1c33efce"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {"host":"localhost","port":"6379"},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "admin.monchis.com.py",
	"port": "30100",
	"protocol": "https",
	"socketio": {},
	"sslCertPath": "echossl/monchis.com.py.crt",
	"sslKeyPath": "echossl/monchis.com.py.key"
}

Please i need help, thanks!

**Comment by eddiclin** [comment]
Check your channel route file: `routes/channels.php`. It looks like a route regular match error.

**Comment by TacuaraTechnologies** [comment]
If i remove this from channels
// Broadcast::channel('*', function ($user, $id) {
//     return true;
// });

Broadcast::channel('chat.{roomId}', function ($user, $roomId) {
  return ['id' => $user->id, 'name' => $user->name];
    // if ($user->canJoinRoom($roomId)) {
    //     return ['id' => $user->id, 'name' => $user->name];
    // }
});


i get this: 

<table class="trace-details">
                                <thead class="trace-head"><tr><th>
                                    <h3 class="trace-class">
                                        <span class="text-muted">(1/1)</span>
                                        <span class="exception_title"><abbr title="BadMethodCallException">BadMethodCallException</abbr></span>
                                    </h3>
                                    <p class="break-long-words trace-message">Call to undefined method Illuminate\Database\Query\Builder::getAuthIdentifier()</p>
                                </th></tr></thead>
                                <tbody><tr><td><span class="block trace-file-path">in <a title="/var/www/monchis3/adminv2/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php line 2445"><strong>Builder.php</strong> (line 2445)</a></span></td></tr>

**Comment by TacuaraTechnologies** [comment]
Now if i return false from the last method: 
Broadcast::channel('chat.{roomId}', function ($user, $roomId) {
  return true;
  return ['id' => $user->id, 'name' => $user->first_name];
    // if ($user->canJoinRoom($roomId)) {
    //     return ['id' => $user->id, 'name' => $user->name];
    // }
});
i get this:

[8:17:17 AM] - SiHxU1K-rPXxRiVoAAMK joined channel: orders-admin
[8:17:19 AM] - SiHxU1K-rPXxRiVoAAMK authenticated for: presence-chat.1
[8:17:19 AM] - SiHxU1K-rPXxRiVoAAMK joined channel: presence-chat.1
(node:1058) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'socketId' of undefined

**Comment by milosilic** [comment]
Hi @TacuaraTechnologies ,

Have you resolved this issue?
