### ISSUE TITLE
Supervisor spawnerr: can't find command '/usr/bin/laravel-echo-server'. Why? It works if I run it in /usr/bin directly

### ISSUE THREAD

**Issue by n0490b** [tlaverdure/laravel-echo-server#264]
I can't get supervisor to run the echo server on my Ubuntu 16.04 AWS EC2 instance but it runs fine on my Homestead Ubuntu 16.04 VM. The error I get it is can't find command '/usr/bin/laravel-echo-server. If I cd directly to `/usr/bin` and run `laravel-echo-server start` it starts up in dev mode just fine

I am running node V8.9.1

Here is what is inside my config file

```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)04d
command=/usr/bin/laravel-echo-server start --dir=/var/www/html/bcbAPI
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/html/bcbAPI/storage/logs/echoserver.log
stderr_logfile=/var/www/html/bcbAPI/storage/logs/echoserver-error.log
```

laravel-echo-server.json
```
{
	"authHost": "http://myip.com/b3",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "aa41c60c83ffa7f7",
			"key": "70e24d91c54f9f30d1fbdb2ed3f2cce8"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
				"port": "6379",
				"host": "localhost"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {
		"wsEngine": "uws"
	},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"apiOriginAllow": {
		"allowCors": true,
		"allowOrigin": "myiphere/b2",
		"allowMethods": "GET,POST,PUT",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
}
```

**Comment by ivuorinen** [comment]
This sounds like a `$PATH` problem, or related to it.

I would double check that `laravel-echo-server` is really in `/usr/bin`, or inside `/usr/local/lib/node_modules` where NPM installs global packages by default.

Please run `which laravel-echo-server` and report back what path it returns. `which` tells where the program you are running really resides. This is the path you should use in your Supervisor configuration.

Running `echo $PATH` returns all paths where your terminal of choice tries to find programs to execute.

**Comment by rbruhn** [comment]
I ran into a similar issue when using NVM. Laravel-echo-server was installed in
/home/vagrant/.nvm/versions/node/v8.11.2/bin/laravel-echo-server

I then had to create a symlink in /usr/bin
laravel-echo-server -> /home/vagrant/.nvm/versions/node/v8.11.2/bin/laravel-echo-server*

From that, my supervisord config worked:
```
[program:local-echo-server]
directory=/home/vagrant/sites/biospex/production
command=laravel-echo-server start
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisor/local/echoserver.log
redirect_stderr=true
logfile_maxbytes=50MB
logfile_backups=5
```
