### ISSUE TITLE
2 Echo-Server on one Server sharing channels

### ISSUE THREAD

**Issue by jastend** [tlaverdure/laravel-echo-server#267]
Hi,

I have two instances of Laravel Echo Server running on my root server (Dev and Live) and they work flawlessly. The problem is that when I send a message via one of the channels there is no separation between them. Here's an example of the unwanted behavior:

1. Dev is listening to presence-channel-1
2. Live is listening to presence-channel-1
3. Message via Live is send to the channel
4. I receive the message on my dev environment, even if the live site is not open and the user is not authenticated to that channel on live

I have setup the two echo server instances the following way:

- Separate ports
- Separate redis instances
- Different hosts (Domain and a sub-domain of it)
- Different appIDs
- Different echo keys
- Different laravel app keys
- One instance has dev mode turned on

I am expecting this to happen because both dev and live share the same naming policy for the channels and are on the same server. Viewing this from the perspective of the server, the client on live and dev authenticate successfully to their respective environments. The socket server then sends the info regardless of the port they are bound to.

I guess the best way to solve this is to prepend some kind of ID or Hash to the channel name. Is there a built in way in the laravel config or should I do this via a global Javascript variable that I define - and is there still a security concern when using prepended channel names?

**Comment by jastend** [comment]
For testing purposes, I've gone ahead and prepended "development" in front of every channel name. This should fix the issue, but I've noticed that I'm triggering both echo servers whenever there's an update.

So in PM2 this shows up like:

```
prod-laravel-echo-server > CHANNEL private-development-dashboard-channel                                                                                      dev-laravel-echo-server > CHANNEL private-development-dashboard-channel 
```

Is there a way to prevent this / only to trigger the echo server that is supposed to run?

**Comment by eddiclin** [comment]
Because the echo-server [psubscribe "*" channel](https://github.com/tlaverdure/laravel-echo-server/blob/master/src/subscribers/redis-subscriber.ts#L46) in Redis.
If you want to avoid it, I think the best way is one app one redis instance unless you can separate the channels' name between your apps by yourself.
Check this issue: #140

**Comment by jastend** [comment]
Hi @eddiclin,

They are already running on two different database instances (ID 1 and 2). So that's not it.

**Comment by eddiclin** [comment]
No. I mean that it's two different redis instances, not two redis databases.
As [this comment](https://github.com/tlaverdure/laravel-echo-server/issues/140#issuecomment-345149187) said, 

> Pub/Sub has no relation to the key space. It was made to not interfere with it on any level, including database numbers.
Publishing on db 10, will be heard by a subscriber on db 1.

**Comment by spmsupun** [comment]
@jastend well I've make laravel api project and start the laravel-echo-server on thet domain, then for the for each channel you have to rename with a secret key from the api (ex: channel-chat-1.sdf4ds545dsfsd).
but this is not safe for the client side, because user can know the secret key.

```
//laravel echo client side
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'https://ws.test.com:7001',
    auth:
        {
            headers:
                {
                    'secret': socket_secret
                  }
          }
  });

Echo.private('message-channel-' + socket_secret)
    .listen('.message-event', (data) => {

});

```
```
//php
   public function broadcastOn()
    {
        return new PrivateChannel('message-channel-'.env('SOCKET_SECRET'));
    }
    public function broadcastAs()
    {
        return 'message-event';
    }
```
laravel-echo-server.json
```
{
	"authHost": "https://ws.test.com",
	"authEndpoint": "/api/auth"
}
```

**Comment by jastend** [comment]
@spmsupun Thanks for your help. I've ended up using a very similar solution. It's not perfect but works for now in my setup.
