### ISSUE TITLE
{"error":"Unauthorized"} when trying to access the HTTP API

### ISSUE THREAD

**Issue by xscence** [tlaverdure/laravel-echo-server#268]
When i try to access some of the endpoints described here https://github.com/tlaverdure/laravel-echo-server#http-api i get error: {"error":"Unauthorized"}. I'm using the app id and the key as auth_key parameter like so: 
```
{
	"authHost": "http://laravel5.test",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "4e8ab2c4f7f32951",
			"key": "0e08c64a779309b7afcc17a2d8b9268d"
		}
	]
.....
}
```

then i make GET request to: http://laravel5.test:6001/apps/4e8ab2c4f7f32951/status?auth_key=0e08c64a779309b7afcc17a2d8b9268d and still doesn't work. where is my problem ? The documentation is soo bad ;/ there is no how to use just some flying examples.

**Comment by togomori2014** [comment]
Hello, 
your authHost is laravel5.test which means the api http call should be coming from that host, 
maybe you're trying to access it from your browser, if so change authHost to localhost

**Comment by muhammadali7768** [comment]
thanks togomori2014. it work for me.
