### ISSUE TITLE
Server Won't Start

### ISSUE THREAD

**Issue by RaymondWilkinson** [tlaverdure/laravel-echo-server#27]
The server doesn't seem to start. When I run the command:
`laravel-echo-server start`
I get this error
![echo server](https://cloud.githubusercontent.com/assets/13651854/18415285/b929351e-77ba-11e6-9e3b-adba9999a959.png)

My laravel-echo-server.json is as follows:
`{
	"appKey": "j6rb6p9jqibi05s8ljdioro5gptj78928bnuacj3qh2tl5i508qfg6hsok2t",
	"authEndpoint": "/broadcasting/auth",
	"authHost": null,
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "http://127.0.0.1"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": false,
	"host": "http://dashboard.app",
	"port": "6001",
	"referrers": [],
	"sslCertPath": "",
	"sslKeyPath": ""
}`

**Comment by pdellepiane** [comment]
I have the same problem!

**Comment by aliselcuk** [comment]
What is your node version? Must be 6+

**Comment by RaymondWilkinson** [comment]
My node version is 6.2.2
![node v](https://cloud.githubusercontent.com/assets/13651854/18418015/7917b4d0-780c-11e6-8e35-454475c5fbee.png)

**Comment by RaymondWilkinson** [comment]
Docs are wrong. i had node v6.2.2 and it didn't work. Upgraded to 6.5.0 and works fine.

**Comment by jonnywilliamson** [comment]
@tlaverdure 

I'm having the same issue, do we really have to update the the most cutting edge version of node to get this to work?

I took a look at the code, briefly.

Removing `.F_OK` from the end of the second parameter here https://github.com/tlaverdure/laravel-echo-server/blob/master/src/cli/cli.ts#L125


gets around the problem, (allow it to run on Node 5), but I don't know what adverse effects that will have.

**Comment by jonnywilliamson** [comment]
More comments. This could be a homestead vs production server thing

https://laracasts.com/discuss/channels/general-discussion/laravel-echo-server-on-homestead?page=1

**Comment by tlaverdure** [comment]
That line is supposed to make sure that there is a json file in the cwd. Supposed to work since v0.11.15 (Looks like I was deceived). I'm going to omit the second parameter and see if that helps.

https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback

**Comment by tlaverdure** [comment]
Please test the latest to see if that helps.

**Comment by jonnywilliamson** [comment]
@tlaverdure 

Please see https://github.com/tlaverdure/laravel-echo-server/commit/1e41fbfad7ebc8c8a66e2e469ffca8a7f2c44b1c#commitcomment-18978492

Perhaps you can use it still...

**Comment by jonnywilliamson** [comment]
CONFIRMED.

Change `fs.constants.F_OK` to `fs.F_OK`

Bad documentation at node.js
