### ISSUE TITLE
Laravel echo not recieving an event. Event is visible in pusher app debug console

### ISSUE THREAD

**Issue by kobimilan995** [tlaverdure/laravel-echo-server#272]
I m having a problem implementing a chat app.
//this is my event
`<?php

namespace Sportyfriends\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Message;

class NewMessage implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message, $conversationId;
    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($data)
    {
        $this->message = $data['message'];
        $this->conversationId = $data['conversation_id'];
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('messages.'.$this->conversationId);
    }
}

//this is my BroadcastServiceProvider
`<?php

namespace Sportyfriends\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Broadcast;

class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes();

        /*
         * Authenticate the user's personal channel...
         */
        Broadcast::channel('messages.{convoId}', function ($user, $convoId) {
            return true;
        });
    }
}
`
this is how i listen to events (i hardcoded the id, its always 1)
`Echo.private('messages.1')
            .listen("NewMessage", (e) => {
              console.log('TEST');
            });`

this is how i create an event
`$message = Message::create([
                    'conversation_id' => $conversation_id,
                    'from_id' => auth()->user()->id,
                    'to_id' => $user_id,
                    'message' => $message
                ]);
                $message->from_name = auth()->user()->firstName;
                $message->conversation_id = $conversation_id;
                event(new NewMessage([
                  'conversation_id' => $conversation_id,
                  'message' => $message
                ]));`

I m not receiving anything on my front end. Please help!

**Comment by dimer22zhc** [comment]
help us tlaverdure evryone is not you
