### ISSUE TITLE
Listen to events with Socket.io client library

### ISSUE THREAD

**Issue by b4nghh** [tlaverdure/laravel-echo-server#276]
Hi! I'm working on a chat app. My app works well with Laravel Echo but for some cases, I need to use Socket.io default client library. For example, I want to listen to events on a mobile app.

Here's my event:
```
<?php

namespace App\Events;

use App\Message;
use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class MessageCreated implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(Message $message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('room_1');
    }
}
```

On the client side, I can use Laravel Echo to listen to the event like this:
```
Echo.channel('room_1')
.listen('MessageCreated', (data) => {
          console.log(data)
});
```
The code above works well, I can receive the event on the client side.

But if I use Socket.io client library instead of Laravel Echo, it doesn't work anymore. Here's my code:
```
var socket = io('http://localhost:6001');
socket.on('room_1:App\\Events\\MessageCreated', function (data) {
        console.log(data);
});
```
What is the problem in this case? Is the event name correct? How can I solve it? And if it's a private event, how to listen to it?

Home somebody can help me in this case. Thank you!

**Comment by b4nghh** [comment]
I already found the solution for this:
https://laracasts.com/discuss/channels/laravel/using-laravel-broadcasting-without-laravel-echo/replies/405136
Thanks!

**Comment by mitajunior** [comment]
@b4nghh really helped
