### ISSUE TITLE
Unable to start Server. Get Error: listen EADDRNOTAVAIL

### ISSUE THREAD

**Issue by skatetdieu** [tlaverdure/laravel-echo-server#277]
I'm having an issue deploying to a staging server. 

This package works fine on a local vm but once deployed and started, the /apps/ and /socket.io/ sub directories don't work. 

Everything looks good on the command line window. It receives redis events just fine. 

In the browser, it tries to make a socket connection but fails because https://domain.com:6001/socket.io/?EIO=3&transport=polling&t=M87JahD fails to connect since the location doesn't exist. 

Anyone else has this issue or a solution? 

Thank you!

**Comment by skatetdieu** [comment]
Looking further I realized I hadn't set up the host value in my json file, which worked locally. So I set it correctly and now I get this error. 

![image](https://user-images.githubusercontent.com/1899636/37177569-dd4e89d2-22ed-11e8-8bb0-717905e82308.png)

Not sure what's going on.

**Comment by jakewtaylor** [comment]
Probably something else already running on the port.

Run `sudo netstat -lpn | grep 6001` to see what else is there.

**Comment by skatetdieu** [comment]
@jakewtaylor thank you for the response. It was actually a network configuration on the server. 

I don't actually know what the issue was since the system's admin took care of it and said it was just network "stuff". 

Thanks for the reply!

**Comment by lostncg** [comment]
@jakewtaylor thank you, you save my day!
@tlaverdure as a suggestion, is it possible to throw a clear error message if port was taken?
