### ISSUE TITLE
It is impossible to get into devMode

### ISSUE THREAD

**Issue by aliselcuk** [tlaverdure/laravel-echo-server#28]
[` options.devMode = yargs.argv.dev || false;`](https://github.com/tlaverdure/laravel-echo-server/blob/bac4822fda97dcb549fbad13e7485d3f276c0f19/src/cli/cli.ts#L133)

this makes setting devMode to true from config file impossible.

**Comment by tlaverdure** [comment]
Not yet. Eventually when in dev mode events will get logged so you can observe them.

**Comment by tlaverdure** [comment]
This has been fixed and there is now events logged in dev mode on join and leave of channels.
