### ISSUE TITLE
Upgrade Laravel Error

### ISSUE THREAD

**Issue by 13dev** [tlaverdure/laravel-echo-server#286]
before anything,
I tested this package with laravel 5.3 and it worked perfectly.
But i need to upgrade laravel to version 5.6
and this package give-me this error:
```
⚠ [11:54:50] - 5QMHdjBBPJRmUkL2AAAA could not be authenticated to private-test
{
    "message": "preg_match(): Compilation failed: nothing to repeat at offset 1",
    "exception": "ErrorException",
    "file": "/var/www/html/broadcast/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php",
    "line": 97,
    "trace": [
        {
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/var/www/html/broadcast/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php",
            "line": 97,
            "function": "preg_match"
        }
    ]
}
Client can not be authenticated, got HTTP status 500

```
line 97 contains this:
` preg_match('/^'.preg_replace('/\{(.*?)\}/', '(?<$1>[^\.]+)', $pattern).'/', $channel, $keys);`

is this problem of php, package or laravel ?

**Comment by skatetdieu** [comment]
I believe, though not sure, in Laravel 5.3 the routes files were a little all over. Check to make sure that in your new upgraded system you have a routes folder in the root of your project like this:

![image](https://user-images.githubusercontent.com/1899636/38889776-a958de8c-424d-11e8-8699-889027037037.png)

channels.php is used to connect to private and presence channels by Laravel.
