### ISSUE TITLE
Can anybody tell me how to make this work faster?

### ISSUE THREAD

**Issue by Evertt** [tlaverdure/laravel-echo-server#288]
I'm building a market place website where people can bid on auctions. I want the price to update instantly in every browser that's looking at an auction whenever someone places a bid.

Right now there is a long delay, something like 10 seconds, between someone placing a bid and the rest being notified. Can you maybe tell me what I can do to make that process faster?

**Comment by Evertt** [comment]
Never mind, my mistake was that my queue worker was set to sleep for 10 seconds whenever there's nothing to do...

**Comment by ExamediaSoftware** [comment]
Can you provide some reference how to develop this auction type system?
