### ISSUE TITLE
Generated json options don't match docs. (AuthEndpoint vs AuthPath)

### ISSUE THREAD

**Issue by jonnywilliamson** [tlaverdure/laravel-echo-server#29]
The json file created by the CLI doesn't match the docs on the homepage for AuthEndpoint / AuthPath)

Which should it be?

Sorry for the very large images. Not sure how to scale them down smaller.

![image](https://cloud.githubusercontent.com/assets/2513663/18420906/c639d392-7875-11e6-8c9e-e61f5769d3f2.png)

Heres the docs:

![image](https://cloud.githubusercontent.com/assets/2513663/18420917/dd4c16f8-7875-11e6-85be-c4dde9977bde.png)

**Comment by tlaverdure** [comment]
The auth host is not necessary unless your echo server is on a different host than you app server.

**With just host:**

host - http://new.dn.dev:6001
authEndpoint - http://new.dn.dev/broadcasting/auth

**With authHost:**

host - http://new.dn.dev:6001
authHost - http://auth.dn.dev
authEndpoint - http://auth.dn.dev/broadcasting/auth

Not sure if that helps, or is there is an issue ?

**Comment by jonnywilliamson** [comment]
The docs show the config key `authPath`

The json generated file has only a config key `authEndpoint`

Is this a mistake/typo?

**Comment by tlaverdure** [comment]
Ah the docs are wrong. Updated
