### ISSUE TITLE
Big latency

### ISSUE THREAD

**Issue by JILeXanDR** [tlaverdure/laravel-echo-server#297]
When I emit event `event(new \App\Events\Ping())` and before the client received message there is a **latency from 1 to 3 seconds**. It is not like realtime. I want to user receive messages immediately as possible.

In logs of "laravel-echo-server" event is also appeared **after 1-3 seconds**.
![Image of Yaktocat](https://i.paste.pics/b998a63dca1d6e63425b28bdb2dab6a3.png)

`// laravel-echo-server.json`
```
{
  "authHost": "http://api.local",
  "authEndpoint": "/auth/broadcasting",
  "clients": [
    {
      "appId": "xxxxxxxxxxx",
      "key": "xxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "database": "redis",
  "databaseConfig": {
    "redis": {},
    "sqlite": {
      "databasePath": "/database/laravel-echo-server.sqlite"
    }
  },
  "devMode": true,
  "host": null,
  "port": "8002",
  "protocol": "http",
  "socketio": {},
  "sslCertPath": "",
  "sslKeyPath": "",
  "sslCertChainPath": "",
  "sslPassphrase": "",
  "apiOriginAllow": {
    "allowCors": true,
    "allowOrigin": "http://localhost:80",
    "allowMethods": "GET, POST",
    "allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
  }
}
```

What is a problem can be here?

**Comment by JILeXanDR** [comment]
I've found the way to fix it. 
To avoid latencies event class **should implements ShouldBroadcastNow** instead of ShouldBroadcast!

**Comment by oussama123-alt** [comment]
@JILeXanDR  thank you , i had a latency of 1-3 secondes with shouldbroadcast, but with shouldbroadcastnow there is no latency
