### ISSUE TITLE
Laravel Echo Server is not receiving events broadcasted by laravel

### ISSUE THREAD

**Issue by darki73** [tlaverdure/laravel-echo-server#302]
Good time of the day!  
I've encountered pretty strange error lately.
I have 2 machines, dev and prod. Here are the configurations:

**Dev Machine:**  
**OS:** Windows 10 Pro  
**Apache:** 2.4.29  
**PHP:** 7.2.5  
**MySQL:** 5.7 CE   
**NodeJS:** 9.8.0  
**NPM:** 5.6.0  
**Laravel Echo Server:** 1.3.6  
**Redis:** Latest Compiled From Sources

**Prod Machine:**  
**OS:** Debian 9  
**Apache:** 2.4.25  
**PHP:** 7.2.5  
**MySQL:** 5.7 CE   
**NodeJS:** 9.11.1  
**NPM:** 5.6.0  
**Laravel Echo Server:** 1.3.6  
**Redis:** Latest Compiled From Sources

So the problem is that on the local server Laravel Echo Server (LES) is working just fine. Client is able to join the rooms, receive the events, leave rooms, etc.   
However, on the production server, LES is showing that client is connected and joined the room, but the events broadcasted by the Laravel itself are not received by the LES server. 

Here is a small excerpt from the **.env** file:   
```
    BROADCAST_DRIVER=redis
    CACHE_DRIVER=redis
    SESSION_DRIVER=redis
    SESSION_LIFETIME=120
    QUEUE_DRIVER=redis
```
And here are the laravel.log file content regarding the broadcasted events:  

```
[2018-05-27 00:32:12] production.INFO: Broadcasting [application.updated] on channels [application] with payload:
{
    "socket": null
}  
[2018-05-27 00:33:39] production.INFO: Broadcasting [application.updated] on channels [application] with payload:
{
    "socket": null
}  
```
This event should trigger the code (it works on dev machine) which will display a snackbar that "Application has been updated, please reload the page".

**laravel-echo-server configuration is done in this way:**
```
    {
		"authHost": "https://api.host.example",
		"authEndpoint": "/broadcasting/auth",
		"clients": [
			{
				"appId": "applicationIDKey",
				"key": "applicationKey"
			}
		],
		"database": "redis",
		"databaseConfig": {
			"redis": {},
			"sqlite": {
				"databasePath": "/database/laravel-echo-server.sqlite"
			}
		},
		"devMode": true,
		"host": null,
		"port": "3000",
		"protocol": "https",
		"socketio": {},
		"sslCertPath": "/var/www/path-to-the-certificates/host_le1.crt",
		"sslKeyPath": "/var/www/path-to-the-certificates/host_le1.key",
		"sslCertChainPath": "/var/www/path-to-the-certificates/host_le1.ca",
		"sslPassphrase": "",
		"apiOriginAllow": {
			"allowCors": true,
			"allowOrigin": "https://application.example",
			"allowMethods": "GET, POST",
			"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
		}
	}
```
Event Code (triggered by the console command upon new application version deployment via Envoy)
```
    <?php namespace App\Events\Application;

    use Illuminate\Broadcasting\Channel;
    use Illuminate\Queue\SerializesModels;
    use Illuminate\Broadcasting\PrivateChannel;
    use Illuminate\Broadcasting\PresenceChannel;
    use Illuminate\Foundation\Events\Dispatchable;
    use Illuminate\Broadcasting\InteractsWithSockets;
    use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
    use Illuminate\Support\Facades\Event;

    /**
     * Class ApplicationUpdatedEvent
     * @package App\Events\Application
     */
    class ApplicationUpdatedEvent extends Event implements ShouldBroadcast {

        use Dispatchable, InteractsWithSockets, SerializesModels;

        /**
         * Create a new event instance.
         *
         * @return void
         */
        public function __construct() {
            //
        }

        /**
         * Get the channels the event should broadcast on.
         *
         * @return \Illuminate\Broadcasting\Channel|array
         */
        public function broadcastOn() {
            return new Channel('application');
        }

        /**
         * Get the broadcast event name
         * @return string
         */
        public function broadcastAs() : string {
            return 'application.updated';
        }

    }
```

Both queue server (supervisord) and LES running at the same time under the user **deployer**. Application is also deployed into the "web" folder by the same user, this user also has rwx permissions to any folder which is necessary for the project to work.   

I really don't see the possible problem with the configuration, since the only thing which is not working is the broadcasting of the events themselves.

**Comment by Chris-AT** [comment]
Hey there!
I think I might have found the problem in your code. In your laravel-echo-server.json your "redis" is empty, thus not configured and might not be able to connect. Maybe worth a try.
`
"databaseConfig": {
			"redis": {},
			"sqlite": {
				"databasePath": "/database/laravel-echo-server.sqlite"
			}
		},
`

**Comment by elbojoloco** [comment]
So? What was the solution?
