### ISSUE TITLE
laravel-echo-server not listening all notification

### ISSUE THREAD

**Issue by JinalSomaiya** [tlaverdure/laravel-echo-server#307]
I want to make real time notification in my app. I am using Laravel Broadcast Notification, Laravel Echo and Laravel Echo Server.in my app in local notification listen for all user but in server if notification added for 5 users then listen for 2 to 3 users and else users log save in laravel.log file.
**CODE**
// controller file
`$users = User::whereHas('dealerRoles', function ($query) {
 $query->where('name', DealerRole::DEALERSHIP_DIRECTOR);
                    $query->orWhere('name', DealerRole::DEALERSHIP_PRINCIPAL);
                    $query->orWhere('name', DealerRole::DEALERSHIP_MANAGER);
                })->whereHas('dealerships', function ($query) use ($listing) {
                    $query->where('dealerships.id', $listing->owner_id);
                })->get();
                \Notification::send($users, (new ListingDecline($listing)));`

// notification file(ListingApproved.php)
`class ListingApproved extends Notification implements ShouldQueue
{
    use Queueable;

    private $listing;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct(Listing $listing)
    {
        $this->listing = $listing;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['database', 'broadcast'];
    }
    public function toArray($notifiable)
    {
        return [
            'listing_id' => $this->listing->id,
            'message' => 'Your Listing has been approved Successfully.'
        ];
    }
}`

// laravel-echo-server.json

`{
	"authHost": ["http://dealers.cc/", "http://admin.videocarsales.cc/"],
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "31071dab508dc1bb",
			"key": "8262eb7c6589432f457ad25b83d4cb5a"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "7878",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"apiOriginAllow": {
		"allowCors": true,
		"allowOrigin": "http://localhost:80",
		"allowMethods": "GET, POST",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
}`

// front end for listen notification
`Echo.private('App.Domain.User.User.' + '{{ auth()->user()->id }}')
                .notification((notification) => {
                    console.log('yes');
                    $.notify(notification.message, {type: 'success'});
                });`
//laravel.log

`[2018-06-13 10:11:49] production.INFO: Broadcasting [Illuminate\Notifications\Events\BroadcastNotificationCreated] on channels [private-App.Domain.User.User.49] with payload:
{
    "listing_id": 1,
    "message": "Your Listing has been approved Successfully.",
    "id": "9fd790d8-1271-4e53-8b1b-7a2407bd8384",
    "type": "App\\Notifications\\ListingApproved",
    "socket": null
}`

Please help me.
Thanks in advance!

**Comment by skatetdieu** [comment]
I may be wrong, but this only works with Events, not Notifications. So the root of the problem might just be that you have to use Events to broadcast. 

Also, I maybe be wrong again, but I don't think there's chainable function after the `Echo.join` of `notification()`. I think that should be `listen()`.

**Comment by skatetdieu** [comment]
Might also want to look at this tutorial:

https://medium.com/@dennissmink/laravel-echo-server-how-to-24d5778ece8b

**Comment by JinalSomaiya** [comment]
@skatetdieu  Echo.notification() function working in local perfectly and in server also works but not listen by all users.

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
