### ISSUE TITLE
SSL + Private Channels - 405 Error

### ISSUE THREAD

**Issue by mdobrenko** [tlaverdure/laravel-echo-server#309]
I am able to run laravel-echo-server on my local environment using HTTP settings just fine. However, it seems that there is an issue on my production server (which is Forge-based) when using HTTPS:

    Client cannot be authenticated, got HTTP status 405

The only real difference between my development and production environment is the SSL. It appears that the issue is as a result of having a private channel and SSL enabled. I was able to test the private channel locally via HTTP, and it worked fine. Furthermore, production worked fine with SSL + a public channel. 

Just to make sure it isn't my authentication method, I had it return 'true' in my channel config:

```
Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});

Broadcast::channel('channelReceiveLiveData.{id}', function ($user, $id) {
	return true;
});

Broadcast::channel('channelReceiveTestState.{id}', function ($id) {
    return true;
});

```
 Here is the version of my echo listener that listens to the private channel:

    Echo.private('channelReceiveLiveData.' + this.$route.params.testID)
    .listen('liveDataTrigger', (e) => {
        if (!that.state.hasPulledInitialData) {
            console.log('Receiving data before initial pull done');
        }

My laravel-echo-server.json file:

     "authHost": "https://app.test.com",
     "authEndpoint": "/broadcasting/auth",
     "clients": [
                {
                        "appId": "....",
                        "key": "...."
                }
        ],
        "database": "redis",
        "databaseConfig": {
                "redis": {},
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
        "devMode": false,
        "host": null,
        "port": "6001",
        "protocol": "https",
        "socketio": {},
        "sslCertPath": "/etc/nginx/ssl/app.test.com/ssl/server.crt",
        "sslKeyPath": "/etc/nginx/ssl/app.test.com/ssl/server.key",
        "sslCertChainPath": "",
        "sslPassphrase": "",
        "apiOriginAllow": {
                "allowCors": false,
                "allowOrigin": "",
                "allowMethods": "",
                "allowHeaders": ""
        }
    }

Any ideas on what the issue may be, or where I can start looking?

**Comment by nguyenphuocnhatthanh** [comment]
I same error... pls help me

**Comment by tlaverdure** [comment]
This seems like an issue with your setup. A 405 error indicates that where the POST request is being sent to authorize a private channel, that method is not allowed.

**Comment by satriaajiputra** [comment]
Don't forget to uncomment this line at ``app/config.php``
``App\Providers\BroadcastServiceProvider::class``
After that execute this command
```
php artisan config:cache
php artisan route:cache
```

And make sure that /broadcast/auth is listed in route list
``php artisan route:list``

**Comment by malik430** [comment]
I have soled my issue. I am using guard "api" I have changed guard "web" to "api" in config/websockets.php 
and in 
app\Providers\BroadcastServiceProvider.php

Broadcast::routes(['middleware' => ['auth:api']]);
