### ISSUE TITLE
Allow options to be passed to socket.io

### ISSUE THREAD

**Issue by petecoop** [tlaverdure/laravel-echo-server#31]
Socket.io has some useful options: https://github.com/socketio/engine.io#methods-1

It'd be nice if we could specify these options in the config to be passed through.

One example use-case is to swap out socket.io's websocket engine with `uws`: https://github.com/uWebSockets/uWebSockets, which claims to be 10-300x faster than socket.io's default engine (`ws`)

**Comment by tlaverdure** [comment]
Thanks for sharing. uWebsockets looks pretty interesting, I'll have to check it out. Options for socket.io are on the list.

**Comment by tlaverdure** [comment]
This has been added under the option `databaseConfig `. See https://github.com/tlaverdure/laravel-echo-server#redis-1

**Comment by petecoop** [comment]
This might allow passing options to the database, but still can't pass options to socket.io which is my issue.

Options would need to be passed here: https://github.com/tlaverdure/laravel-echo-server/blob/master/src/server.ts#L93

**Comment by tlaverdure** [comment]
Oh sorry! Misread this.

**Comment by petecoop** [comment]
nice!
