### ISSUE TITLE
Not connect SSL

### ISSUE THREAD

**Issue by nguyenphuocnhatthanh** [tlaverdure/laravel-echo-server#313]
L A R A V E L  E C H O  S E R V E R

version 1.3.6

⚠ Starting server in DEV mode...

✔  Running at localhost on port 9090
✔  Channels are ready.
✔  Listening for http events...
[10:12:12 AM] - Error authenticating zx0PgS4PGjRKtOiwAAAA for private-chatroom
{ Error: getaddrinfo ENOTFOUND gallery.local gallery.local:443

My option
{
 "authHost": "https://gallery.local",
  "protocol": "https",
"port": 9090
}

Pls help me
![screenshot from 2018-06-20 17-21-54](https://user-images.githubusercontent.com/10797131/41652828-738cc65e-74ae-11e8-8852-4e868230ac81.png)

**Comment by tlaverdure** [comment]
Add you ssl file paths to your config.
