### ISSUE TITLE
Not getting a leave event on page refresh

### ISSUE THREAD

**Issue by exwizzard** [tlaverdure/laravel-echo-server#315]
I am using presence channels with laravel echo and listening for leave events in order to trigger some code.

The leave event fires when I close the tab or browser, it also fires when I browse to a new page. But for some reason it does not fire when I refresh the page, it just rejoins the presence channel and it causes my code to add extra listeners. Every time the page is refreshed it adds another listener and then I get an error that there are too many listeners after about 11 refreshes. 

I was looking at the echo server log file and I noticed one thing, this event fires when I refresh the page:

`[10:43:54] - C6bO4RT7uRJE54mAAAIL left channel: presence-channel.10 (unsubscribed)`

When I close the browser or go to a new page it does this instead:

`[10:43:45] - 7XuNd5NAZl9-LmSnAAI7 left channel: presence-channel.10 (transport close)`

How can I listen for this "unsubscribed" event when its not getting picked up by the .leaving listener?

**Comment by exwizzard** [comment]
I have solved this issue by starting a unique connection to the echo server for every channel, instead of reusing the same connection for the whole app.

**Comment by MGAyoub** [comment]
what do you mean "unique connection" ?!

**Comment by youyi1314** [comment]
any guide line for this? i got this problem too
