### ISSUE TITLE
multiple applications on the same server

### ISSUE THREAD

**Issue by delia-curiel** [tlaverdure/laravel-echo-server#319]
Hi,
is it possible to keep just one instance of the Laravel Echo Server serving multiple applications in the same machine?    Or is it necessary to run one instance per application (and on different ports)?

We have multiple applications in the same server, and we want to use the same Laravel Echo Server listening on port 6001 for all of them

**Comment by zedentox** [comment]
You cant use one instance for multiple apps if you are using private and presence channels. Because there is only one app which is contacted for authentication. (Only one auth endpoint)

**Comment by delia-curiel** [comment]
@zedentox you are right, thanks!   
So, if I only used public channels, would it be possible to configure just one instance of the Laravel Echo Server?  How should I configure it?

**Comment by delia-curiel** [comment]
@zedentox thanks, it works now!

**Comment by delia-curiel** [comment]
@zedentox hi again,  I am not sure how to configure the laravel-echo-server.json file in this case.... I have left the **authHost** and **authEndpoint** empty...but, what should I enter in the **sslCertPath** and **sslKeyPath** params, when using the **https** protocol?  Can I leave empty too?

**Comment by zedentox** [comment]
No you can't. They are paths to your certificate files. (usually a .key file for the key and a .crt, .cert or .pem file for the other path) Have you a certificate already ?

**Comment by delia-curiel** [comment]
@zedentox well, I had installed my applications on forge, using this tutorial https://laracasts.com/discuss/channels/forge/laravel-echo-server-installation-on-forge-with-ssl-enabled-with-the-redis-broadcast-driver.
So the certificate files are related to each application domain......... 

Should I have to create a specific domain for the Laravel Echo Server then?  And create certificate files for this domain?

**Comment by zedentox** [comment]
If your Echo Server is installed on the same server as an existing application, simply use its certificate.
If it is on another server, generate a certificate for it. You need one certificate per domain.

**Comment by delia-curiel** [comment]
@zedentox ok, many thanks!!

**Comment by delia-curiel** [comment]
@zedentox  hi again, I've almost have this ready, but now it appears this error message in the javascript console:

Refused to connect to 'wss://<<my-site>>:6001/socket.io/?EIO=3&transport=websocket&sid=2M5bXi9tJxe-aKSOAAAE' because it violates the following Content Security Policy directive: "connect-src https:".

Do you know how to solve this?

Thanks in advance!
