### ISSUE TITLE
Remove log when devMode false

### ISSUE THREAD

**Issue by KAMAELUA** [tlaverdure/laravel-echo-server#320]
https://github.com/tlaverdure/laravel-echo-server/blob/cb85b60fa712884ab18defe193499bde3fbc06a8/src/subscribers/redis-subscriber.ts#L40

Can you disable that log when devMode set to false, or create another option that disables realtime log. Because it cause a huge size of a log file in a big system.

**Comment by tlaverdure** [comment]
This has been addressed.
