### ISSUE TITLE
Error when installing laravel-echo-server

### ISSUE THREAD

**Issue by tojoaijo** [tlaverdure/laravel-echo-server#321]
Hello to all,

Someone can help me because today I have this error when installing laravel-echo-server:

"> spawn-sync@1.0.15 postinstall /root/.npm-global/lib/node_modules/laravel-echo-server/node_modules/spawn-sync
> node postinstall

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/.npm-global/lib/node_modules/laravel-echo-server/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
"
or last day, it's work

**Comment by tojoaijo** [comment]
problem solved

**Comment by arturcesarmelo** [comment]
how?

**Comment by skeeith** [comment]
how?
