### ISSUE TITLE
Is there anyway to make this work with CloudFlare?

### ISSUE THREAD

**Issue by quangvision** [tlaverdure/laravel-echo-server#329]
Hello buddies,
   My laravel-echo-server.json file is as below:
  {
        "authHost": "https://mysite.com",
        "authEndpoint": "/broadcasting/auth",
        "clients": [],
        "database": "redis",
        "databaseConfig": {
                "redis": {},
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
        "devMode": true,
        "host": "0.0.0.0",
        "port": "6001",
        "protocol": "https",
        "socketio": {},
        "sslCertPath": "/etc/letsencrypt/live/mysite.com/cert.pem",
        "sslKeyPath": "/etc/letsencrypt/live/mysite.com/privkey.pem",
        "sslCertChainPath": "",
        "sslPassphrase": "",
        "apiOriginAllow": {
                "allowCors": false,
                "allowOrigin": "",
                "allowMethods": "",
                "allowHeaders": ""
        }
}

    My main bootstrap.js file: 
    window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
  })

  The problem is when I turn "yellow" to "grey" cloud on A name record on CloudFlare then laravel-echo-server working fine but when I turn yellow cloud on then not working anymore.
  Anyone went through this, please drop me some guidelines.
  Thank buddies :)

**Comment by d-pollard** [comment]
Yes and its a really simple fix.

The problem is you're trying to use a port that cloudflare doesn't allow access to.

[According to this link](https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-), these are the ports cloudflare allows requests through:

> Cloudflare can only proxy traffic going over the HTTP/HTTPS ports listed below. If your traffic is on a different port, you should create a subdomain for that record and then add it as a record in your Cloudflare DNS zone file as something we don't proxy (gray cloud = no Cloudflare proxy or caching on a record).
> 
> For requests made via HTTP:
> 80
> 8080
> 8880
> 2052
> 2082
> 2086
> 2095
> 
> For requests made via HTTPS:
> 443
> 2053
> 2083
> 2087
> 2096
> 8443

**Comment by quangvision** [comment]
Hi @d-pollard 
I tried to use port 8443 because requests made via HTTPS and enabled yellow cloud on CloudFlare.
After open port 8443, use this port on laravel-echo-server.json and bootstrap.js then run laravel-echo-server start. 
I got this:
`⚠ Starting server in DEV mode...

✔  Running at 0.0.0.0 on port 8443
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!`

No error returned and nothing works.
Can you advise me further on this?
Thank buddy :)

**Comment by d-pollard** [comment]
Here is a copy of my working laravel-echo-server.json:

```json
{
   "authHost":"https://mysite.com",
   "authEndpoint":"/broadcasting/auth",
   "database":"redis",
   "databaseConfig":{
      "redis":{
         "port":"6379",
         "host":"127.0.0.1",
         "password":"123pass"
      },
      "sqlite":{
         "databasePath":"/database/laravel-echo-server.sqlite"
      }
   },
   "devMode":false,
   "host":null,
   "port":"2053",
   "protocol":"https",
   "socketio":{
      "wsEngine":"uws"
   },
   "sslCertPath":"/server.crt",
   "sslKeyPath":"/server.key",
   "sslCertChainPath":"",
   "sslPassphrase":"",
   "apiOriginAllow":{
      "allowCors":true,
      "allowOrigin":"https://mysite.com",
      "allowMethods":"GET, POST",
      "allowHeaders":"Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
   }
}
```
I think your issue is also your host. Set it to null, like mine

**Comment by d-pollard** [comment]
Also @quangvision - remember to change the port in your javascript too:

```javascript
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':2053'
})
```

If the problem still persists, depending on your host (AWS, for example), you might have to allow access to the specific port (in my case, 2053). If you're using https://forge.laravel.com (highly recommended, especially for development), they have a clean interface for setting up rules to the port

**Comment by quangvision** [comment]
Hi @d-pollard 
Thank for your quick help and support. I tried to edit params like you suggested but unfortunately things still not working. Below are configs that I set:

For laravel-echo-server.json:
```
{
        "authHost": "https://quangvision.blog",
        "authEndpoint": "/broadcasting/auth",
        "clients": [],
        "database": "redis",
        "databaseConfig": {
                "redis": {},
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
        "devMode": false,
        "host": null,
        "port": "2053",
        "protocol": "https",
        "socketio": {},
        "sslCertPath": "/etc/letsencrypt/live/quangvision.blog/fullchain.pem",
        "sslKeyPath": "/etc/letsencrypt/live/quangvision.blog/privkey.pem",
        "sslCertChainPath": "",
        "sslPassphrase": "",
        "apiOriginAllow": {
                "allowCors": true,
                "allowOrigin": "https://quangvision.blog",
                "allowMethods": "GET, POST",
                "allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
        }
}
```
For bootstrap.js file:
```
window.Echo = new Echo({
broadcaster: 'socket.io',
host: window.location.hostname + ':2053'
```
My CloudFlare DNS config screenshot:
[](https://imgur.com/4z4XCw2)
My VULTR VPS config: CentOS 7.1, Nginx...
I tried to use firewall-cmd to open port 2053 for zone public as you can check here to port already opened:
http://ping.eu/port-chk/
Can you please provide me some information further on this?
  Thank again, @d-pollard

**Comment by quangvision** [comment]
Hello
 I figured out the way to make laravel-echo-server working with CloudFlare.
 Except my above configuration params, I added below block to mydomain.conf file then restart nginx:
```
 location ~* \.io {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass http://localhost:6001;
      proxy_redirect off;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
```
  If your server is running apache then use this:
```
 RewriteEngine On
RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
RewriteCond %{QUERY_STRING} transport=websocket    [NC]
RewriteRule /(.*)           ws://localhost:6001/$1 [P,L]
ProxyPass        /socket.io http://localhost:6001/socket.io
ProxyPassReverse /socket.io http://localhost:6001/socket.io
```
  I hope this would work for somebody confronting this problem.
  All thanks should go to this thread #251

**Comment by BenaddiRar** [comment]
> Yes and its a really simple fix.
> 
> The problem is you're trying to use a port that cloudflare doesn't allow access to.
> 
> [According to this link](https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-), these are the ports cloudflare allows requests through:
> 
> > Cloudflare can only proxy traffic going over the HTTP/HTTPS ports listed below. If your traffic is on a different port, you should create a subdomain for that record and then add it as a record in your Cloudflare DNS zone file as something we don't proxy (gray cloud = no Cloudflare proxy or caching on a record).
> > For requests made via HTTP:
> > 80
> > 8080
> > 8880
> > 2052
> > 2082
> > 2086
> > 2095
> > For requests made via HTTPS:
> > 443
> > 2053
> > 2083
> > 2087
> > 2096
> > 8443
> 
> So, change `6001` to one of the above ports and it should work like a charm!

2053 work for me
