### ISSUE TITLE
New release is binding to localhost not all adapters.

### ISSUE THREAD

**Issue by jonnywilliamson** [tlaverdure/laravel-echo-server#33]
Hi,

Firstly I'm going to admit I'm not 100% knowledgeable in this area, however I think there's been some biggish change in the latest release with regards to what network adapter the echo server binds to when it is started.

I've been hitting my head against the wall for the past 3 hours until I finally "cracked it". But I'm looking for feedback.
- I'm currently using homestead to do all the development work. Nothing is being run on my "local" machine.
- I tested using the old v0.9.65 and the latest 1.10.11
- I have had to tweak the source files to get around https://github.com/tlaverdure/laravel-echo-server/issues/26

This is not the order in which I discovered everything, but it's the most logical easy to follow order to explain.
## Using v 0.9.65

First I check that nothing is running on port 6001 on my server.

```
vagrant@homestead  ~/Code/new.wn.dev   sudo netstat -tulnp | grep 6001
vagrant@homestead  ~/Code/new.wn.dev  
```

Nothing is returned.

Then I start my node server (this is my server.js file):

``` js
var echo = require('laravel-echo-server');
var options = {
    authHost: 'http://new.wn.dev',
    authPath: '/broadcasting/auth',
    host: 'http://new.wn.dev',
    port: 6001,
};
echo.run(options);
```

Now lets take a look at what is listening on port 6001

```
vagrant@homestead  ~/Code/new.wn.dev   sudo netstat -tulnp | grep 6001
tcp6       0      0 :::6001                 :::*                    LISTEN      8337/node
```

Notice the `0:::` before the 6001, I think that means all adapters. I stand to be corrected.

I was able to get public, private and presence channels all working with this setup with no issues.
## Now Upgrade to 1.0.11

Lets create the json file:

``` json
{
    "appKey": "k<snip>fh",
    "authEndpoint": "/broadcasting/auth",
    "authHost": "http://new.wn.dev",
    "database": "redis",
    "databaseConfig": {
        "redis": {},
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        }
    },
    "devMode": false,
    "host": "http://new.wn.dev",
    "port": "6001",
    "protocol": "http",
    "referrers": [],
    "sslCertPath": "",
    "sslKeyPath": "",
    "verifyAuthPath": true,
    "verifyAuthServer": false
}
```

trying to run this causes an immediate error due #26.

![image](https://cloud.githubusercontent.com/assets/2513663/18456647/8c373cc2-794a-11e6-8607-fd4d55c97fca.png)

This seems to be because passing `http` or `https` to the `http.listen` method is not valid. So lets hard code the host to a string without `http`

Editing the `laravel-echo-server/dist/server.js` file near the bottom:

![image](https://cloud.githubusercontent.com/assets/2513663/18456679/d6eb0226-794a-11e6-8eb0-7df1fb6be51e.png)

Lets run the server again.

![image](https://cloud.githubusercontent.com/assets/2513663/18456693/eaf920c2-794a-11e6-94be-b986f3299700.png)

Seems to be working. Now lets see what is listening on port 6001

```
vagrant@homestead  ~/Code/new.wn.dev   sudo netstat -tulnp | grep 6001
tcp        0      0 127.0.1.1:6001          0.0.0.0:*               LISTEN      9781/laravel-echo-s
```

A-ha! This time the server is only listening to port 6001 on `localhost/127.0.1.1` so even though I have my ports forwarded from 6001 on the host to 6001 on this guest, I can never contact this server on port 6001 because it only accepts connections on the local loopback adapter. Not from "external" connections.

![image](https://cloud.githubusercontent.com/assets/2513663/18456779/8d16803e-794b-11e6-886c-1f2063dc4544.png)

So that got me thinking, what if I set my server address to ALL adapters (0.0.0.0).

I REMOVED the file edit in the `laravel-echo-server/dist/server.js` file as well.

```
{
//<snip>
    "devMode": false,
    "host": '0.0.0.0',
    "port": "6001",
    "protocol": "http",
    "referrers": [],
    "sslCertPath": "",
    "sslKeyPath": "",
    "verifyAuthPath": true,
    "verifyAuthServer": false
}
```

And start the sever again:

![image](https://cloud.githubusercontent.com/assets/2513663/18456817/01a5282e-794c-11e6-830e-dc52505ede58.png)

Well that's working. Lets see whats using the port

```
 vagrant@homestead  ~/Code/new.wn.dev   sudo netstat -tulnp | grep 6001
tcp        0      0 0.0.0.0:6001            0.0.0.0:*               LISTEN      9155/laravel-echo-s
```

Well that looks much closer to the original one in version `0.9.65`.

Lets see if it works in the browser:

![image](https://cloud.githubusercontent.com/assets/2513663/18456846/42fde50e-794c-11e6-8416-3aed748b7b78.png)

Perfect!

Now everything is working again!

So a few thoughts:
1. Have I found a bug?
2. Should we be connecting to local host or all adapters in production?
3. Has there been a change in the code that would affect this between 0.9 and 1.0 ?
4. Whats the difference between `:::6001` and `0.0.0.0:6001`
5. Have you a time machine so I can get the past few hours back! Haha. 

Thank you.

**Comment by jonnywilliamson** [comment]
One final one

Leaving the host key in the json completely blank produces this:

```
	"devMode": false,
	"host": "",
	"port": "6001",
```

```
vagrant@homestead  ~/Code/new.wn.dev   sudo netstat -tulnp | grep 6001
tcp6       0      0 :::6001                 :::*                    LISTEN      11422/laravel-echo-
```


Which also works perfectly, and is exactly the same result as the old `0.9.65` version.

**Comment by jonnywilliamson** [comment]
I know the first post is long....but anyone else have any thoughts on how this library should bind to the network device?

**Comment by tlaverdure** [comment]
I think this should be fixed. Let me know if not.
