### ISSUE TITLE
not working channels are ready in laravel echo

### ISSUE THREAD

**Issue by callemac88** [tlaverdure/laravel-echo-server#331]
I have a problem i could not resolve.

when I use the program in localhost work perfect but when I move it to the server production it does not work.

I saw when i run laravel-echo-server start in localhost it shows:
✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

but in production it shows:
✔  Running at localhost on port 6001
✔  Listening for http events...
✔  Listening for redis events...

What could be happening??? why the option Channels are ready. is not working??? thank you

**Comment by erlangp** [comment]
it show just in dev mode, sir.. you can see at line: https://github.com/tlaverdure/laravel-echo-server/blob/96e8a93757109ac0b7cc66cbb789edf03428d9fe/src/channels/channel.ts#L42

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
