### ISSUE TITLE
Client can not be authenticated, got HTTP status 400

### ISSUE THREAD

**Issue by nguyenphuocnhatthanh** [tlaverdure/laravel-echo-server#336]
I test with my local was authenticated
 but my server is receive : Client can not be authenticated, got HTTP status 400

my config
 {
    "appKey": process.env.ECHO_KEY,
    "authHost": "https://local.dev:9090",
    "authEndpoint": "/broadcasting/auth",
    "database": "redis",
    "databaseConfig": {
        "redis": {
            "port": 6379,
            "host": "localhost"
        },
        "sqlite": {
            "databasePath": process.env.ECHO_SQLITE_PATH
        }
    },
    "devMode": true,
    "host": "",
    "protocol": "https",
    "port": 6001,
    "referrers": [],
    "socketio": {},
    "sslCertPath": process.env.ECHO_SSL_CERT_PATH,
    "sslKeyPath": process.env.ECHO_SSL_KEY_PATH,
    "verifyAuthPath": true,
    "verifyAuthServer": true
};

**Comment by erlangp** [comment]
please show me the console error message

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
