### ISSUE TITLE
Laravel echo server start fine but does not listen any events being broadcasted

### ISSUE THREAD

**Issue by kallekulp** [tlaverdure/laravel-echo-server#339]
I am having problem with socket.io as a broadcaster with laravel echo.

What have I tried:

```
    php artisan cache:clear
    php artisan config:clear
```

I can see users connecting within the logs:

```
    0|Socket-Connection  | [11:17:00 AM] - ********** joined channel: test-channel
    0|Socket-Connection  | [11:17:01 AM] - ********** authenticated for: private-user.1
    0|Socket-Connection  | [11:17:01 AM] - ********** joined channel: private-user.1
```

My queue is running and is logging all the events properly.

I can see events and database notifications perfectly in the redis console.

But no events are broadcasted and I am not seeing them in the laravel-echo-server console. Everything is working in my localhost, but not in the production and I am losing my mind.

Here's my laravel echo JS:

```
    if (typeof io !== 'undefined') {
    	console.log(window.location.origin);
    	window.Echo = new Echo({
    		broadcaster: 'socket.io',
    		host: window.location.origin + ':6001',
    		auth: {
    			headers: {
    				Authorization: 'Bearer ' + bearerToken,
    			},
    		}
    	});
    	window.Echo.private('user.' + user_id).notification((notification) => {
    		console.log(notification);
    	});
    }
```

On my user model I have defined this:

```
    /**
	* @return string
	*/
	public function receivesBroadcastNotificationsOn()
	{
		return 'user.' . $this->id;
	}
```

And in my channels I have this:

```
    Broadcast::channel('user.{id}', function ($user, $id) {
		return (int)$user->id === (int)$id;
	});
```

This is my echo server config where all the paths are correct. I tested the same file on my localhost and everything is working:

```
    var echo = require('laravel-echo-server/dist');
    
    echo.run({
    	"appKey": "myappkey",
    	"authHost": "https://www.app.riskomed.com",
    	"authEndpoint": "/broadcasting/auth",
    	"database": "redis",
    	"clients": [
    		{
    			"appId": "myappid",
    			"key": "mykey"
    		}
    	],
    	"databaseConfig": {
    		"redis": {
    			"port": "6379",
    			"host": "myhost",
    			"password": "mysupersecretpassword"
    		},
    		"sqlite": {
    			"databasePath": "/database/laravel-echo-server.sqlite"
    		}
    	},
    	"devMode": true,
    	"host": "www.app.riskomed.com",
    	"port": "6001",
    	"protocol": "https",
    	"referrers": [],
    	"sslCertPath": "/path/to/certificate.pem",
    	"sslKeyPath": "/path/to/key",
    	"verifyAuthPath": true,
    	"verifyAuthServer": false
    });
```

My redis log shows this when published a database notification

`    1534840681.110359 [0 "IP ADDRESS HERE"] "PUBLISH" "private-user.2" "{\"event\":\"Illuminate\\\\Notifications\\\\Events\\\\BroadcastNotificationCreated\",\"data\":{\"title\":\"Ravim CONVULEX 50MG\\/ML  staatust muudeti\",\"notification_type\":\"element-soft-delete\",\"message\":\"Ravimi CONVULEX 50MG\\/ML  staatust muutis kasutaja Kalle Kulpson\",\"url\":\"https:\\/\\/www.app.riskomed.com\\/admin\\/brands\\/all\",\"id\":\"30c37d0d-c39b-41bf-93fc-afa0c78ca9db\",\"type\":\"App\\\\Notifications\\\\API\\\\Management\\\\Medical\\\\Brands\\\\BrandSoftDeleteNotification\",\"socket\":null},\"socket\":null}"`

**Comment by erlangp** [comment]
maybe need to run `php artisan queue:listen`

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
