### ISSUE TITLE
How to setup laravel-echo-server

### ISSUE THREAD

**Issue by mistre83** [tlaverdure/laravel-echo-server#34]
Hi to all,
i'm a bit confused on how setup this server with Laravel.
Right now i have a working configuration with Pusher, and i would like to test this server.

laravel-echo-server can use sqlite and redis. In `.env` the `BROADCAST_DRIVER` should be `redis` in both case ?

I have setup all, when i visit the page with server up the connection is established (i notice that because if i stop the server, Chrome Dev tools log errors), but when i try to send messages.. that are not dispatched. And, with pusher the configuration works fine (i'm just trying to change the server).

Can someone tell me how to configure server and how to setup Laravel ?

Thanks a lot

**Comment by ctf0** [comment]
1- the broadcast driver is redis in both cases yes
2- the database used to store data that should persist, like presence channel members , so using sqlite or redis is up to you
3- to send msgs , first try to use the public channel in the event check https://laravel.com/docs/5.3/broadcasting#concept-overview 
4- make sure u restart the queue to pick up the new event , i had the same issue and this step fixed it for me.
5- if u got issue with echo check this https://github.com/tlaverdure/laravel-echo-server/issues/40

**Comment by tlaverdure** [comment]
There have been some improvements made, please try again with the CLI tool.
