### ISSUE TITLE
cannot authenticate private channel

### ISSUE THREAD

**Issue by nicolasvahidzein** [tlaverdure/laravel-echo-server#340]
Hello, i tried everything and there is something missing. I really need your help.

i changed the route for passport authentication like so:

`Broadcast::routes([ "middleware" => "auth:api" ]);`

I set the checking for the private channel:

`Broadcast::channel('bouffon', function ($user) {
	return true;
});`

i'm listening to the proper channel in my vue.js front end(not inside laravel, it is seperate):
`                               window.io = require('socket.io-client');
                                window.Echo = new Echo({
					broadcaster: 'socket.io',
					host: socketServerURL,
					auth: {headers: {Authorization: 'Bearer ' + Vue.auth.getToken() }}
				});`

`                               window.Echo.private('bouffon').listen('NewContactCreated', event => {
					console.log('event returned on private contacts channel listening:')
					console.log(event)
				})`

Your help would be greatly appreciated. Thank you.

Anything else is working great.

**Comment by nicolasvahidzein** [comment]
I got it to work by changing the channel name from something generic to something different like so but it's still static so it makes no sense to me:

"bouffon" channel became "bouffon.5"

i made this change only in the channel.php page and on the front end to listen where it obviously gets checked for subscription. Is this normal or is it a bug? i can send you my code.

**Comment by hogus2037** [comment]
config/auth.php
'defaults' => [
        //'guard' => 'web',
        'guard' => 'api',
        'passwords' => 'users',
    ],
you can try it

**Comment by nicolasvahidzein** [comment]
thank you. I was able to get it to work by changing the routes in laravel and adding the headers to my request.
