### ISSUE TITLE
Getting an error "Could not send authentication request." when trying to listen on a private channel

### ISSUE THREAD

**Issue by allantatter** [tlaverdure/laravel-echo-server#35]
When trying to make a simple example of using Laravel and Laravel Echo Server, I get an error "Could not send authentication request."

![screen shot 2016-09-14 at 20 33 12](https://cloud.githubusercontent.com/assets/386999/18522995/f5272c58-7aba-11e6-9a30-73457e8eef17.png)

What did I do:

* I created a new fresh Laravel 5.3 project `$ laravel new laravel53`. Laravel app is served on `http://laravel53.dev`
* `$ npm install`
* `$ npm install --save laravel-echo laravel-echo-server pusher-js socket.io-client` (for some reason `laravel-echo` needs `pusher-js` although I'm not using Pusher)
* `$ laravel-echo-server init` with a config below

![screen shot 2016-09-14 at 20 39 47](https://cloud.githubusercontent.com/assets/386999/18523109/77b01fa4-7abb-11e6-9e35-b1d8e1159d52.png)

* uncommented `App\Providers\BroadcastServiceProvider::class,` in `config/app.php`
* appended the following code to `resources/assets/js/app.js`

```javascript
import Echo from 'laravel-echo';
window.io = require('socket.io-client');

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost:6001'
});

window.Echo.private('user.1')
    .listen('NewMessageSent', (e) => {
        console.log(e.update);
    });
```

* added the following code to `BroadcastServiceProvider`

```php
Broadcast::channel('user.*', function ($user, $userId) {
    return true;
});
```

* `$ laravel-echo-server start`
* `$ gulp`
* `$ touch database/database.sqlite`
* set sqlite as DB driver in `.env`
* `$ php artisan make:auth`
* `$ php artisan migrate`
* visited `http://laravel53.dev/register`, created account and landed on `http://laravel53.dev/home` as authenticated user
* `Could not send authentication request.` shows up in the terminal

**Comment by enniel** [comment]
laravel echo server and laravel php server must use one host name.

```js
...
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost:6001'
});
...
```

```json
{
	"appKey": "9te930q989itok355krkfrs95j92ais01iim3i5sjs1k93g87kt8qdd0ur91",
	"authEndpoint": "/broadcasting/auth",
	"authHost": "http://localhost:8000",
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "localhost",
	"port": "6001",
	"protocol": "ws",
	"referrers": [],
	"sslCertPath": "",
	"sslKeyPath": "",
	"verifyAuthPath": true,
	"verifyAuthServer": false
}
```

**Comment by allantatter** [comment]
Thanks. Maybe it could have a better error message or smth to show what's probably wrong.

**Comment by shijunti19** [comment]
I am also the problem, how to repair

**Comment by asvechkar** [comment]
some problem

**Comment by gdbhosale** [comment]
I am also facing same problem.

My code is on https://github.com/gdbhosale/laravel-5.3-socket-io-vue.js

Any way out  ?

**Comment by barryvdh** [comment]
The problem happend to me. Make sure you check the following:
 - No error occured, for example with the broadcast check; check your logs
 - Check if the result returns true. When false, it fails but gives the error `null - Could not send authentication request.`

Would be nice if it just said the response failed with status 500 or the actual message, and showed when the request is rejected.

**Comment by stoneworld** [comment]
I am also facing same problem.
Any way out ?

**Comment by anwardote** [comment]
any solution yet

**Comment by barryvdh** [comment]
Did you try what I said?

**Comment by anwardote** [comment]
Apoloze,... I am totally new in the matter. Thats why I am quite confused on your last solution... Can you indicate the changes with files name?

**Comment by barryvdh** [comment]
I mean in your Laravel application. This error could indicate that your user is not correctly authenticated. So either you get an error while trying to verify this, or the user is not authenticated.

So check your laravel logs (storage/logs/laravel.log) to see if an error occured. Or set some logging in your broadcast provider, to log the status.

And don't forget to enable the provider of course:

```
class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes();

        /*
         * Authenticate the user's personal channel...
         */
        Broadcast::channel('App.User.*', function ($user, $userId) {
            return (int) $user->id === (int) $userId;
        });
    }
}
```

**Comment by anwardote** [comment]
Thanks for your faster replying....

**Comment by kkomelin** [comment]
Also, please make sure you don't have any redirects for the /broadcasting/auth route. Any status except 200 will cause an error in Laravel Echo Server. It can be language redirects like /en/broadcasting/auth or some others.

**Comment by barryvdh** [comment]
FYI, I created a PR (#101) to show the difference between invalid configuration and just not getting authenticated. That should be more clear to see what's actually wrong here.

**Comment by kkomelin** [comment]
Thank you @barryvdh. Useful improvement. Voted for it.

**Comment by bodonb** [comment]
I have same problem. storage\laravel.log is clean.
If i use only `Broadcast::routes()` I will get status: 403
If i use this `Broadcast::routes(['middleware' => ['auth', 'web']]);` "unauthorized" status: 401
I use laravel-echo-server/redis/socket.io,
I tried jwt-auth because of csrf token and got same errors.
Any solution?

**Comment by barryvdh** [comment]
You need to explicitly authorize all private /presence channels, did you do that?

**Comment by bodonb** [comment]
What does that mean?

**Comment by barryvdh** [comment]
https://laravel.com/docs/5.3/broadcasting#defining-authorization-callbacks

**Comment by bodonb** [comment]
Yeah. It was defined.
```
Broadcast::channel('message-received', function ($user, $userId) {
            return true;
        });
```

**Comment by barryvdh** [comment]
And are you using default authorization? (sessions with cookies), or something else?

**Comment by bodonb** [comment]
I use default authorization.

**Comment by barryvdh** [comment]
These are the headers that are sent by the request: https://github.com/tlaverdure/laravel-echo-server/blob/95d6a111cf5c3a5fb307a1d837c67f12de50439a/src/channels/private-channel.ts#L71-L82

So if you're using custom headers, they're not sent. We should probably send all custom headers.
How are you defining your Echo config client-side?

**Comment by bodonb** [comment]
this is my client side code:
```
import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost:6001',
});


window.Echo.private('message-received')
    .listen('MessageWasReceived', (e) => {
        console.log(e.statusMessage);
    });
```

**Comment by barryvdh** [comment]
Sorry, the auth headers are correctly sent. Strange that you are not authorized.

**Comment by bodonb** [comment]
Yeah, no problem, I don't understand also.

**Comment by bodonb** [comment]
I solved it. I just a mistake. 
laravel-echo-server.json:
```
"authHost": "http://test.dev",
"host":"test",
```
on the client side use localhost that is the problem:
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://**localhost**:6001',
});
change **localhost** to **test.dev**.
Now It works.

**Comment by xscence** [comment]
It doesn't work for me http://prntscr.com/dxwb4o my BroadcastServiceProvider is enabled. I got this:

`<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Broadcast;

class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes();

        /*
         * Authenticate the user's personal channel...
         */
        Broadcast::channel('check-channel', function () {
            return true;
        });
    }
}
`
and

` window.Echo = new Echo({
     broadcaster: 'socket.io',
     host: 'http://127.0.0.1:6001'
 });

window.Echo.private('check-channel')
    .listen('Message', (e) => {
        console.log('HERE', e);
    });`

and my laravel-echo-server config
`{
	"authHost": "127.0.0.1",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "APP_ID",
			"key": "93cca48913d0b9590070bb8784b9052e"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "127.0.0.1",
			"password": "mypassword"
		},
		"sqlite": {}
	},
	"devMode": true,
	"host": "127.0.0.1",
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}`

for public channels work but for private doesnt please give me some advice. Thanks

**Comment by xscence** [comment]
Fixed. I've forgot to put this meta on top of the document.
```
<meta name="csrf-token" content="{{ csrf_token() }}">
```

**Comment by kkomelin** [comment]
@xscence It appears to me that your original issue was related to the fact that authHost requires an absolute address of the Laravel site and not just a hostname. Your screenshot tells us exactly that. 
You may read more [here](https://komelin.com/articles/realtime-apps-laravel-echo-tips-and-tricks#host-settings).

**Comment by olhasliusar** [comment]
Hi! I'm using your laravel-echo-server with socket.io in my project on Silex. 
I tested authentication with cookie and it works. But i don't use sessions, so i need to add header with token for authentication request.
I've seen your answer with link for private-channel.ts file. But i don't understand where i can customize request?
