### ISSUE TITLE
Client can not be authenticated, got HTTP status 401

### ISSUE THREAD

**Issue by chiporgar7** [tlaverdure/laravel-echo-server#352]
hello I'm trying to connect to a private channel I've even put everything static but it still does not work

`⚠ [01:26:00] - vuRoO1iQUt7qZwmBAABl could not be authenticated to private-ventas-channel.5
{"message":"Unauthenticated."}
Client can not be authenticated, got HTTP status 401`

**Comment by tlaverdure** [comment]
You'll need to make sure that everything is setup properly using the docs https://laravel.com/docs/5.7/broadcasting
