### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by gbdematos** [tlaverdure/laravel-echo-server#353]
I can't make it work in production... 

Server is running ok (I'm testing with dev set to true).

```
✔  Running at localhost on port 6004
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!
```

This is my config:

```
{                                                                            
        "authHost": "https://mydomain.com",                                    
        "authEndpoint": "/broadcasting/auth",                                
        "clients": [                                                         
                {                                                            
                        "appId": "...",                         
                        "key": "..."            
                }                                                            
        ],                                                                   
        "database": "redis",                                                 
        "databaseConfig": {                                                  
                "redis": { "port": "6379", "host": "localhost" },            
                "sqlite": {                                                  
                        "databasePath": "/database/laravel-echo-server.sqlite
                }                                                            
        },                                                                   
        "devMode": true,                                                     
        "host": null,                                                        
        "port": "6004",                                                      
        "protocol": "https",                                                 
        "socketio": {},                                                      
        "sslCertPath": "/etc/nginx/ssl/mydomain.com/421049/server.crt",        
        "sslKeyPath": "/etc/nginx/ssl/mydomain.com/421049/server.key",         
        "sslCertChainPath": "",                                              
        "sslPassphrase": "",                                                 
        "subscribers": {                                                     
                "http": true,                                                
                "redis": true                                                
        },                                                                   
        "apiOriginAllow": {                                                  
                "allowCors": false,                                          
                "allowOrigin": "",                                           
                "allowMethods": "",                                          
                "allowHeaders": ""                                           
        }                                                                    
}       
```

But I can't access https://mydomain.com:6004/socket.io/socket.io.js

I already added the firewall rule (ports 6004 and 6379)!

I have laravel horizon running for queues.

Any idea what I might be facing?

**Comment by gbdematos** [comment]
Hey thanks for the suggestion, it may help someone! I just ended up using the alternative proxy config, because I couldn't make it work in the default way.

**Comment by jhoanborges** [comment]
> I was also facing the same issue but finally I made it. My production server configuration is : php 7.1, laravel 5.5, nginx 1.15.5, mysql 5.7, Ubuntu 18.04. Following are the steps which I followed to make it work. Hope it will help you.
> 
> 1. Create an Event using `php artisan make:event YourEventName`
> 2. `YourEventName.php` :
>    Change these 2 lines with these :
>    `use Illuminate\Contracts\Broadcasting\ShouldBroadcastNow;`
>    `class YourEventName implements ShouldBroadcastNow`
> 
> `public function broadcastOn() { return new Channel('ChannelName'); }`
> 
> 1. Trigger this event the way you want. (using command, using route etc)
> 2. In your project under `resources/assets/js/bootstrap.js` add these lines,
> 
> `import Echo from "laravel-echo" window.io = require('socket.io-client'); window.Echo = new Echo({ broadcaster: 'socket.io', host: window.location.hostname + ':6001' });`
> 
> 1. If you are using laravel blade for you front-end, add these line under `body tage`. And if you are using any other front-end framework like Anguler or React etc, then look for how to add these piece of code.
>    inside `head` : `<script src="{{ asset('js/app.js')}}"></script>`
>    inside `body` : `<script> Echo.channel('ChannelName') .listen('YourEventName', (e) => { console.log(e); }); </script>`
> 2. `npm install -g laravel-echo-server`
> 3. `laravel-echo-server init`
>    configuration :
>    `{ "authHost": "https://localhost", "authEndpoint": "/broadcasting/auth", "clients": [], "database": "redis", "databaseConfig": { "redis": {}, "sqlite": { "databasePath": "/database/laravel-echo-server.sqlite" } }, "devMode": true, "host": null, "port": "6001", "protocol": "https", "socketio": {}, "sslCertPath": "/etc/nginx/ssl/DomainName/431841/server.crt", "sslKeyPath": "/etc/nginx/ssl/DomainName/431841/server.key", "sslCertChainPath": "", "sslPassphrase": "", "subscribers": { "http": true, "redis": true }, "apiOriginAllow": { "allowCors": true, "allowOrigin": "https://DomainName:443", "allowMethods": "GET, POST", "allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id" } }`
> 
> 1. check if port 6001 is added or not in you server firewall rules : `sudo ufw status`
> 2. If not, the add `sudo ufw allow 6001/tcp`
> 3. `npm install`
> 4. `npm install --save laravel-echo`
> 5. `npm install --save socket.io-client`
> 6. `npm run dev`
> 7. `.env` configuration :
> 
> `BROADCAST_DRIVER=redis CACHE_DRIVER=file SESSION_DRIVER=file SESSION_LIFETIME=120 QUEUE_DRIVER=database REDIS_HOST=127.0.0.1 REDIS_PASSWORD=null REDIS_PORT=6379`
> 
> 1. `php artisan cache:clean`
> 2. `php artisan config:clean`
> 3. `php artisan config:cache`
> 4. `laravel-echo-server start`
> 5. `php artisan queue:listen --tries=1`
> 
> Then visit your front-end and trigger the event from back-end. You will be able to see your message on front-end console.

You made my day. This should be part of the documentation.
