### ISSUE TITLE
Echo and Laravel Passport

### ISSUE THREAD

**Issue by AlexeyTcapaev** [tlaverdure/laravel-echo-server#354]
It can be work?
i try,but get

⚠ [18:04:19] - 7UHynBzc1WSShc0mAAAB could not be authenticated to private-chat.5<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Object not found!</title>
<link rev="made" href="mailto:%5bno%20address%20given%5d" />
<style type="text/css"><![CDATA[/*></style>
</head>

<body>
<h1>Object not found!</h1>
<p>

    The requested URL was not found on this server.

    If you entered the URL manually please check your
    spelling and try again.

</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:%5bno%20address%20given%5d">webmaster</a>.

</p>

<h2>Error 404</h2>
<address>
  <a href="/">localhost</a><br />
  <span>Apache</span>
</address>
</body>
</html>

Client can not be authenticated, got HTTP status 404

**Comment by skatetdieu** [comment]
This package only seems to work with `web` authenticated users. It doesn't seem to work with Passport authenticated users that typically just hit api routes.

**Comment by tlaverdure** [comment]
You can make this change in your app/Providers/BroadcastServiceProvider.php file.

```php
Broadcast::routes([
    'middleware' => ['auth:api'],
]);
```
