### ISSUE TITLE
run laravel-echo-server on startup 

### ISSUE THREAD

**Issue by SirCumz** [tlaverdure/laravel-echo-server#36]
After updating this package today my site stopped working.

When reading the laravel-echo-server docs i went crazy because it did not tell me how to start the damn thing, after reading the issues i found out that i should use "laravel-echo-server start" to run.

Oke it works fine now!

But int the previous version i could run a server,js file, i used https://github.com/coreybutler/node-windows to start the server.js on windows start, but with the updated version i cannot do this anymore (i think) does someone know how i can run "laravel-echo-server start" command when windows has started?

**Comment by tlaverdure** [comment]
You should still be able to use your server.js file with `echo.run(options);` in it. Just make sure you have the right options included.

**Comment by Jonybang** [comment]
Explanation for noobs(like me):
Create laravel-echo-server.js (for example), then place inside this code:
```
var echo = require('laravel-echo-server/dist');

echo.run({
    "appKey": "[app-key]",
    "authEndpoint": "/broadcasting/auth",
    "authHost": null,
    "database": "redis",
    "databaseConfig": {
        "redis": {},
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        }
    },
    "devMode": false,
    "host": "localhost",
    "port": "6001",
    "protocol": "http",
    "referrers": [],
    "sslCertPath": "",
    "sslKeyPath": "",
    "verifyAuthPath": true,
    "verifyAuthServer": false
});
```
Then you can start server by command `node laravel-echo-server.js`
