### ISSUE TITLE
Can't authenticate private channel, problem with Windows authentication

### ISSUE THREAD

**Issue by Crinsane** [tlaverdure/laravel-echo-server#37]
I'm trying to use this package, but I can't get private channels to work.
I've the latest version of both this package as Laravel running, node updated etc.

I keep getting this error:

```
Error: Invalid URI "intranet.dev/broadcasting/auth"
Could not send authentication request.
```

My laravel-echo-server.json file:

```
{
    "appKey": "nkmn0uh71d1s3mhdlqq5kqkp16mg3rup4rho97t13qj3ghag30i8q1j3egr2",
    "authEndpoint": "/broadcasting/auth",
    "authHost": "http://intranet",
    "database": "redis",
    "databaseConfig": {
        "redis": {},
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        }
    },
    "devMode": false,
    "host": "intranet",
    "port": "6001",
    "protocol": "http",
    "referrers": [],
    "sslCertPath": "",
    "sslKeyPath": "",
    "verifyAuthPath": true,
    "verifyAuthServer": true
}
```

Client JavaScript code:

```
import Echo from 'laravel-echo'

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://intranet:6001'
});
```

What am I doing wrong?

Okay... I think I found out what the problem might be. The intranet website uses Windows-Authentication and so IIS is blocking the request before it even gets to the Laravel app...

Is there any way to specify Windows credentials to use for the request?

**Comment by gaillafr** [comment]
Hi @Crinsane,

I faced the same issue and resolved it by manually adding 'http://' in 'authHost' & 'host'.

Hope it helps !

**Comment by rijensky** [comment]
I'm facing the same problem, I think with you it's just a typo.

This is your code:
 "authHost": "http://intranet",

And it shoud be:
 "authHost": "http://intranet.dev",

Hope that helps. I'm going to look for typos in my code.
If anyone sees anything wrong here, please help :(

{
	"appKey": "base64:qVtWajlvBUnCpzddFueY/bXM1U34BmqtbPYTtyqxbRM=",
	//"appKey": "r8fiq6hbtk7fo5aa9s1o0h29nbeuq5pd1c1ngsimu99kciebado8m1dbs506",
	"authEndpoint": "/broadcasting/auth",
	"authHost": null,
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": false,
	"host": "nevermind.dev",
	"port": "6001",
	"protocol": "http",
	"referrers": [],
	"sslCertPath": "",
	"sslKeyPath": "",
	"verifyAuthPath": true,
	"verifyAuthServer": false
}

**Comment by rijensky** [comment]
Solved it.
The authHost should include http and the host must not include http.
For example, on the nevermind.dev laravel-echo-server.json, it should look like this:

"authHost": "http://nevermind.dev",
"host": "nevermind.dev",

**Comment by shijunti19** [comment]
if "authHost": "http://nevermind.dev",
null
Could not send authentication request.

if "authHost": "nevermind.dev",
Error: Invalid URI "nevermind.dev/broadcasting/auth"
Could not send authentication request.

**Comment by pfeiferchristopher** [comment]
+1

**Comment by khaledelmahdi** [comment]
Same results as @shijunti19

**Comment by Crinsane** [comment]
This issue is closed @tlaverdure But it's actually not solved.
When you have Windows Authentication activated on IIS, it's impossible to use this, because there are no Windows credentials send for the NTLM authentication. Is there a way to specify those?

**Comment by pfeiferchristopher** [comment]
I'm getting the results listed above running this in my development
environment running on Ubuntu thru vagrant so Windows is not in between
there for me.

**Comment by jonnywilliamson** [comment]
Yes, this is something I get a lot of as well.

Still trying to do more debugging

**Comment by jonnywilliamson** [comment]
@Crinsane @rijensky 

Hey guys don't use `.dev` for your urls

I've been badly bitten with this!

https://github.com/tlaverdure/laravel-echo-server/issues/57

**Comment by pfeiferchristopher** [comment]
https://github.com/tlaverdure/laravel-echo-server/issues/53#issuecomment-254037254

**Comment by jaceju** [comment]
I had the same problem too, but I found the response from laravel-echo-server had this error:

```
RedisBroadcaster->auth(object(Request)) in BroadcastManager.php line 306
```

And `RedisBroadcaster` would throw exception when:

```
if (Str::startsWith($request->channel_name, ['private-', 'presence-']) && ! $request->user())
```

The `$request->user()` will be null if the session is not authenticated. So it should add `auth` middleware to web routes before you using Echo.

FYR.

**Comment by pfeiferchristopher** [comment]
My issue was that I had the server running on a different host than my app was running on. So the laravel auth cookies weren't being sent along the websocket so it could be used to auth.

**Comment by asvechkar** [comment]
still have this problem

**Comment by stoneworld** [comment]
still have this problem

**Comment by tlaverdure** [comment]
Not sure if this is still happening, but if it is, please open a new issue.

**Comment by rauschmerscen** [comment]
Soultion to Common Problems faced by many users while setting up Laravel Echo
https://gist.github.com/rauschmerscen/2f2265976d59267f3bfccb339b27be44
