### ISSUE TITLE
Default Laravel 'auth' guard with sessions returns 401 for private channels?

### ISSUE THREAD

**Issue by osha7apps** [tlaverdure/laravel-echo-server#377]
Hmmm, so I do not have a jwt token to pass to the authorization header bearer. Instead, my app uses the default laravel authentication `auth` with sessions for authentication. My app and laravel echo server are on the same domain, everything in the same project.

Instead of a header Authorization Bearer token, I make an ajax request using 3 headers, `X-Requested-With`, `X-CSRF-TOKEN`, and `X-Socket-Id`, but that results in a 401 unauthenticated response from laravel-echo-server:
```
["subscription_error","private-users.username",401]
```

I have this as part of the `laravel-echo-server.json`:
```
"apiOriginAllow": {
    "allowCors": false,
    "allowOrigin": "",
    "allowMethods": "",
    "allowHeaders": ""
}
```
and the `BroadcastServiceProvider` uses the `auth` guard, as opposed to `auth:api` since the app only uses the default laravel `auth` guard as mentioned above:
```
Broadcast::routes(['middleware' => ['auth']]);
```

Any idea what's the correct setup for same domain private channel authentication with the default laravel auth guard using sessions?

**Comment by lonycc** [comment]
why you guys close this issue, did you solve the problem?

**Comment by Adizbek** [comment]
@osha7apps  @lonycc  you can set `debug:true` to logs issues to screen, I have solved some errors using debug
