### ISSUE TITLE
Ack Message [question]

### ISSUE THREAD

**Issue by alexmontoanelli** [tlaverdure/laravel-echo-server#38]
Imagine that the Laravel Event/Broadcast system has fired a event, and has sended
to Redis, to be broadcasted on channel  user.1234.

But, at this time, the user 1234 is not logged in, so it is not listening on channel user.1234.

laravel-echo-server will pick-up the redis message, and "discard", as the message will
be sented to a channel with no one.

Laravel-echo-server could hold  this message for a period of time,
maybe a paramenter on payload, for a time?

Mayble, laravel-echo-server could check if there is at least one user in that channel,
and if there is no one, try latter, or maybe queue for delivery when someone join in
that channel.

**Comment by tlaverdure** [comment]
Thanks for the idea, but this project is only intended for real-time events. You can store messages in you app database.
