### ISSUE TITLE
Apache Settings for transparent Socket.Io [trick]

### ISSUE THREAD

**Issue by alexmontoanelli** [tlaverdure/laravel-echo-server#39]
Here is my trick to make apache forward requests to laravel-echo-server/socket.io 
in a transparent way.

With this approach, we can setup you laravel-echo-server to listen just on localhost - in this example port 3001, and set you laravel js side like [this](http://pastebin.com/uMPWj5MC).

When you fireup you browser, a websocket connection will be tried on same host
and same port as your app is running, and then forwarded internally by apache to laravel-echo-server.

Problem with firewalls..no more...
You need the modules proxy_http e proxy_wstunnel up.

The code above must be insider your virtual-host [paste-bin](http://pastebin.com/jkUw30m5)

**Comment by jonnywilliamson** [comment]
This is brilliant!

I use nginx and so I wanted to do the same for it. Lots of benefits to this, like no worries about having another port open in your firewall etc!

After some testing this is what you need to do to make this work with nginx.

Open your nginx conf file for the website you want to use the websockets on, it's normally found in `/etc/nginx/sites-available/<yoursite.com>`

```
server {
    listen 80;
    listen 443 ssl default_server;
    server_name example.com;
    root "/home/vagrant/example.com/public";

    index index.html index.htm index.php;

    charset utf-8;

### Add this section for websockets reverse proxy
### Assumes you want to run your laravel-echo-server on localhost with a port of 6001

    location /socket.io {
        proxy_pass http://127.0.0.1:6001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

###END OF WEBSOCKETS SECTION

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
<snip>
```

Don't forget to restart nginx `sudo service nginx restart`.

Now you can set your `laravel-echo-server.json` to have the following:

```
<snip>
	"devMode": false,
	"host": "127.0.0.1",
	"port": "6001",
	"protocol": "http",
	"referrers": [],
```

And finally in your JS `bootstrap.js` file (or where ever you define Echo):

```js
import Echo from "laravel-echo"
window.echo = new Echo({
    broadcaster: 'socket.io',
    host: { path: '/socket.io' }
});
```


That's the setup complete.

Just start the echo server (use the instructions) and then ensure that the page you load on your website has the JS loading ok. Your system is setup to receive broadcasts!

Thanks @alexmontoanelli - that's really cool!

**Comment by barryvdh** [comment]
Does this use apaches ssl certificates, or do you still need to setup those in the config?

**Comment by alexmontoanelli** [comment]
You can set ssl on apache side in the usual way...will works ( I use here)

**Comment by antoniopaisfernandes** [comment]
Don't you have problems with the number of apache processes/threads that remain active/open because of the sockets?

**Comment by prince30** [comment]
I am not able to setup on amazon ec2 using apache

**Comment by solancer** [comment]
I get an errror

 {
"code": 0,
"message": "Transport unknown"
}

![screen shot 2017-12-08 at 1 37 17 am](https://user-images.githubusercontent.com/800668/33736368-5d37cf0a-dbb8-11e7-9baf-c786f7958dec.png)

**Comment by marcorivm** [comment]
@solancer did you find a solutions? facing the same issue here

**Comment by createoop** [comment]
With config :

<location /socket>
                RewriteEngine On
                RewriteCond %{QUERY_STRING} transport=websocket    [NC]
                RewriteRule /(.*)           ws://localhost:3001/socket.io/%{QUERY_STRING} [P,L]
                ProxyPass http://localhost:3001
                ProxyPassReverse http://localhost:3001
</location>

i am getting error:

**Error during WebSocket handshake: Unexpected response code: 400**

**Comment by createoop** [comment]
When i am using debug mode i see that thing:

engine bad request: unexpected transport without upgrade
