### ISSUE TITLE
Connecting from remote App with Socket.IO-Client

### ISSUE THREAD

**Issue by lipiniak** [tlaverdure/laravel-echo-server#397]
Hi,
Im trying to connect to my Laravel Echo Server private channels on my laravel app. 
Im using Socket.io-client since im writing a small phone app for reciving events from my website. 
Im stuck at this that after excluding broadcasting/auth from CRSF protection i have AccessDeniedHttpException when trying to log user to the private channel. Im probably missing something when loging in to laravel echo server by socket.io
Here is my code for this:
`const io = require('socket.io-client')

var options = {
    auth: {
      headers: {'Authorization': 'Bearer token'}
    }
  }
  var socket = io("https://bazagraczy.pl"+ ':6001', options);
  
  socket.emit('subscribe', {
    channel: 'private-room-9000008',
    auth: options.auth
  }).on('App\\Events\\unReadMessage', function(channel, data) {
    console.log(data);
  });`

Its connecting to laravel echo server but cant connect to my laravel private channels.

**Comment by ProgramadorDeValor** [comment]
Same here. @lipiniak , did you find a solution ?

**Comment by lipiniak** [comment]
Oh wow. 
It was long time ago. 
I think it was problem in my channels routing. I changed it then and it helped.
