### ISSUE TITLE
Uncaught TypeError: _laravelEcho2.default.channel is not a function

### ISSUE THREAD

**Issue by ctf0** [tlaverdure/laravel-echo-server#40]
any idea ?

**Comment by sugeng** [comment]
Instead `Echo.channel` try `window.Echo.channel`

**Comment by ctf0** [comment]
@sugeng that fixed it , thanx but now i dont know how to view the data, there is no examples and the official doc have only for pusher , have u came by any tutorials using redis & echo ?
