### ISSUE TITLE
Works fine if I enter "authHost": "http://mywebsite.test" but doesn't work when I use "authHost": "http://localhost"

### ISSUE THREAD

**Issue by aFluxx** [tlaverdure/laravel-echo-server#404]
Hello there,

I can't grasp why this isn't working.

if I use 
`"authHost": "http://mywebsite.test" `
everything works fine, but when I change that line to:

`"authHost": "http://localhost" `I suddenly get these console messages:

` app.js:22819 GET http://localhost:6001/socket.io/?EIO=3&transport=polling&t=MfvwRwx net::ERR_CONNECTION_REFUSED`

I'm using browsersync in my workflow so that's why I want localhost to work. Also localhost get's auto https validation so it's easy to work & test around with service workers. I don't have that if I develop on the http://mywebsite.test domain.

Any ideas?

**Comment by clugg** [comment]
It sounds like you're using homestead or a similar virtualized environment based on the mywebsite.test domain - by default, port 6001 isn't forwarded from that environment to your local machine.

If you take a look at the [Homestead documentation](https://laravel.com/docs/5.8/homestead#ports), you can see that it is possible to forward additional ports. In your case, you probably want to add the following to your `Homestead.yaml`:

```yaml
- send: 6001
  to: 6001
  protocol: tcp
```

**Comment by aFluxx** [comment]
Hello there,

I didn't thest this out yet,  thanks for the information!
