### ISSUE TITLE
Why does this show that we have different channels?

### ISSUE THREAD

**Issue by shijunti19** [tlaverdure/laravel-echo-server#409]
![image](https://user-images.githubusercontent.com/5392211/58065800-772b3f80-7bb9-11e9-9bda-6b03dcfd43e2.png)
Why does this show that we have different channels?

At the moment, it's normal, but we can't get any information.

laravel 5.8
REDIS
L A R A V E L  E C H O  S E R V E R
version 1.5.4
Anything else is the latest version.

**Comment by shijunti19** [comment]
That's why, how should I set up laravel-echo-server?

**Comment by tlaverdure** [comment]
Check your laravel database config file for a prefix. This prefix gets added to all redis data. https://github.com/laravel/laravel/blob/master/config/database.php#L126
