### ISSUE TITLE
error on re-running the server when using sqlite as db

### ISSUE THREAD

**Issue by ctf0** [tlaverdure/laravel-echo-server#41]
``` bash
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_ERROR: index key_index already exists
    at Error (native)
```

if i removed the sqlite file and re-added it again, the error goes away.

**Comment by barryvdh** [comment]
Does this fix it?

**Comment by barryvdh** [comment]
https://github.com/tlaverdure/laravel-echo-server/pull/96

**Comment by ctf0** [comment]
I hvnt tested it, but if all good from ur side i can close this issue :)
