### ISSUE TITLE
This site can’t be reached, Error:  net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by rolandalla** [tlaverdure/laravel-echo-server#421]
Hello Everyone, 

I have a strange problem only on live server using **laravel-echo-server**, **redis**, **ssl** .

Error:
`GET https://dev.my_domain.com:6001/socket.io/?EIO=3&transport=polling&t=Ml1g-Fq net::ERR_CONNECTION_TIMED_OUT`

Below you can find my configs:
laravel-echo-server.json
```
{
	"authHost": "https://dev.my_domain.com",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
      		        "host": "127.0.0.1"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "https",
	"socketio": {},
	"sslCertPath": "/etc/letsencrypt/live/dev.my_domain.com/fullchain.pem",
	"sslKeyPath": "/etc/letsencrypt/live/dev.my_domain.com/privkey.pem"
}
```

Bootstrap.js
```
import Echo from 'laravel-echo';

window.io = require('socket.io-client');

window.Echo = new Echo({
	broadcaster: 'socket.io',
	host: window.location.hostname + ':6001'
});
```

Port 6001 is enabled:
`tcp6       0      0 :::6001                 :::*                    LISTEN      10728/laravel-echo- `

It is working correctly on my localhost without ssl configuration.

Let me know if someone has a solution for this problem ,

Thanks to everyone in advance

**Comment by rolandalla** [comment]
Hey , Found a solution for  my problem :  [](https://stackoverflow.com/questions/56901401/laravel-echo-server-neterr-connection-timed-out/56968217#56968217)

**Comment by sallaoui** [comment]
> Hey , Found a solution for my problem : https://stackoverflow.com/questions/56901401/laravel-echo-server-neterr-connection-timed-out/56968217#56968217

Hello,

I'm facing the same problem, I did the same, I did everything you mentioned in your post on Stackoverflow, but only in default-ssl.conf, because I don't have a file with Mydomain.conf, should I create it ? 

Thank you in advance for your answer.
Regard!
