### ISSUE TITLE
please bump the 1.5.6 also on the npmjs.com

### ISSUE THREAD

**Issue by ibrainventures** [tlaverdure/laravel-echo-server#429]
Hi, thanks for this great package.

As i saw, you made some changes for the release 1.5.6 on 11th of June . 

This Version is not bumped to the npmjs.com ..  (there is still the 1.5.5)

https://www.npmjs.com/package/laravel-echo-server

Thanks in advance
Jochen

**Comment by tlaverdure** [comment]
Thanks! Could have sworn that I did. It's up now.
