### ISSUE TITLE
cannot set up ssl correctly

### ISSUE THREAD

**Issue by johndoe2509** [tlaverdure/laravel-echo-server#44]
{
        "appKey": "9asdfasdfasdfasdf70kfojbcdos6tujq8f10celag0a9s0",
        "authEndpoint": "/broadcasting/auth",
        "authHost": null,
        "database": "redis",
        "databaseConfig": {
                "redis": {},
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
        "devMode": false,
        "host": "mydomain.com",
        "port": "6001",
        "protocol": "https",
        "referrers": [],
        "sslCertPath": "/etc/letsencrypt/live/mydomain.com/cert.pem",
        "sslKeyPath": "/etc/letsencrypt/live/mydomain.com/privkey.pem",
        "verifyAuthPath": true,
        "verifyAuthServer": false
}

![image](https://cloud.githubusercontent.com/assets/15901445/18859170/3da8f284-84a4-11e6-8c03-e04b17e7fcb7.png)

everything work well if when using http , but if use https even the js file cannot be load in client side,
do i need to config nginx (port forwarding?) for it to work

**Comment by johndoe2509** [comment]
seems can be fixed by modifying
Server->serverProtocol()  :

if(this.options.protocal == 'https')

**Comment by tlaverdure** [comment]
Fixed - https://github.com/tlaverdure/laravel-echo-server/pull/46
