### ISSUE TITLE
Facing issue of Privacy Error in Https with laravel-echo-server

### ISSUE THREAD

**Issue by ishan013** [tlaverdure/laravel-echo-server#447]
Thank you in advance!

**The Problem**

I have used the Laravel echo server for real time notifications. I am facing a weired problem, when I am working with it in Http request it works fine and also responding as we expected.

But when we want to work with it in https request, it gives some privacy error
I am running my laravel echo server on port no 2053 with https

**My laravel-echo-server.json file is**

{
        "authHost": "https://yoursitename.com ",
        "authEndpoint": "/guard/broadcast/auth",
        "clients": [
                {
                        "appId": "01043a0df36689f4",
                        "key": "1739bf763403d2b7022d858575fa6340"
                }
        ],
        "database": "redis",
        "databaseConfig": {
                "redis": {
                   "port":"6379",
                   "host":"127.0.0.1"
                },
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
        "devMode": true,
        "host":"yoursitename.com ",
        "port": "2053",
        "protocol": "https",
        "socketio": {},
        "sslCertPath": "/etc/ssl/certs/ssl-cert-snakeoil.pem",
        "sslKeyPath": "/etc/ssl/private/ssl-cert-snakeoil.key",
        "sslCertChainPath": "",
        "sslPassphrase": "",
        "subscribers": {
                "https": true,
                "redis": true
         },
        "apiOriginAllow": {
                "allowCors": false,
                "allowOrigin": "yoursitename.com ",
                "allowMethods": "GET, POST",
                "allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
        }
}

Here is the error which is been shown

**Your connection is not private**
Attackers might be trying to steal your information from yoursitename.com (for example, passwords, messages or credit cards). Learn more

NET::ERR_CERT_AUTHORITY_INVALID
Help improve Safe Browsing by sending some system information and page content to Google. Privacy Policy
This server could not prove that it is instawrex.com; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection.
Proceed to yoursitename.com (unsafe)

**The output of laravel-echo-server start**

L A R A V E L  E C H O  S E R V E R
version 1.5.7
⚠ Starting server in DEV mode...

✔  Running at yoursitename.com on port 2053
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

**What I am using**
    1. Laravel 5.6
    2. Laravel Echo Server 1.5.7

Please help me for the above issue.

Thanks

**Comment by shafter** [comment]
https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate

**Comment by ishan013** [comment]
@shafter  Its working with a real ssl certificate. I have referenced wrong ssl certificate. Thank you!
