### ISSUE TITLE
Change laravel-echo-server.json path (Laravel deployer)

### ISSUE THREAD

**Issue by Imtiyaz-CHOUJAI** [tlaverdure/laravel-echo-server#465]
Hey guys,

Awesome job on the package 👏👏, I'm currently using [Laravel Deployer](https://github.com/lorisleiva/laravel-deployer) to handle deployment to production I'm having issues with having to generate the `laravel-echo-server.json` file each time I deploy as it's in the root directory.

Is there any option to specify where to store the config file? I have a shared folder that I can use, was wondering if it's possible to change the location of the config file.

**Comment by tlaverdure** [comment]
Hey give this a try.

https://github.com/tlaverdure/laravel-echo-server#setting-the-working-directory
