### ISSUE TITLE
hello, "laravel-echo-server init" stop here 

### ISSUE THREAD

**Issue by leonzai** [tlaverdure/laravel-echo-server#469]
hello, when I run laravel-echo-server init, it stuck here :
**What do you want this config to be saved as? laravel-echo-server.json**
Even I ctrl + c, it doesnt do anything, still stuck here.

**Comment by nguyentranchung** [comment]
Only way is to kill the terminal

**Comment by lypsisrudiansyah** [comment]
You Can Kill the terminal / close the terminal

or You Can try another command line / terminal
i was stuck on the same problem, and i close my cmd(windows)
and try init the laravel-echo-server by using git bash command line, this case is solved, there is no more stuck issue
