### ISSUE TITLE
How to notify the server that the user who left.

### ISSUE THREAD

**Issue by keval6706** [tlaverdure/laravel-echo-server#474]

**Comment by litvinenkow** [comment]
server knows it as it fires in server logs like this
[18:19:56] - cvq5UTuV204sRfQhAAAA left channel: private-App.User.5 (transport close)

**Comment by keval6706** [comment]
@litvinenkow  thank you but how can i catch this from my laravel side?

**Comment by litvinenkow** [comment]
oh, I haven't checked this point yet) 
thought it's pretty simple, in fact, and I need to process it, and I don't know how too)

**Comment by keval6706** [comment]
@litvinenkow  
please check : https://github.com/tlaverdure/Laravel-Echo-Server#readme
hooks no longer available now.

**Comment by litvinenkow** [comment]
no, you don't understand this is not "undocumented function" of official release, this was made in fork by other guys

**Comment by jexme** [comment]
@keval6706 
https://github.com/tlaverdure/laravel-echo-server#presence-channels

you can listen to redis through the server, and then process it as you wish

**Comment by keval6706** [comment]
okay @jexme
