### ISSUE TITLE
Broadcasting not working with laravel/framework v6.11.0 (released 2020-01-14)

### ISSUE THREAD

**Issue by litan1106** [tlaverdure/laravel-echo-server#477]
Broadcasting not working with v6.11.0. I had to reverted back to laravel/framework 6.10.1

v6.11.0 (2020-01-14)

Added
Added Illuminate\Database\Eloquent\Builder::firstWhere() method (#31089)
**Redis Broadcaster: Broadcast to multiple channels at once (#[31108](https://github.com/laravel/framework/pull/31108))**

**Comment by josiasmontag** [comment]
Which Redis server version are you running?
Do you see the Events when you are running `PSUBSCRIBE *` in the Redis console?

**Comment by litan1106** [comment]
> Which Redis server version are you running?

Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=fbc6fab733127977

> Do you see the Events when you are running `PSUBSCRIBE *` in the Redis console?

1579194848.789953 [4 172.19.0.8:51680] "EVAL" "for i = 2, #ARGV do\n  redis.call('publish', ARGV[i], ARGV[1])\nend" "0" "{\"event\":\"App\\\\Events\\\\PDFGenerated\",\"data\":{\"orderId\":test-1234,\"submitId\":\"test-id\",\"ptemp-pdf-test.pdf\"},\"socket\":null}" "private-test.pdf.test-1234.test-id"
1579194848.790053 [4 lua] "publish" "private-test.pdf.test-1234.test-id" "{\"event\":\"App\\\\Events\\\\PDFGenerated\",\"data\":{\"orderId\":test-1234,\"submitId\":\"test-id\",\"pdfLink\":\"temp-pdf-test.pdf\"},\"socket\":null}

**Comment by timoschwarzer** [comment]
I can confirm this. Reverting https://github.com/laravel/framework/pull/31108 fixes the problem. Investigating...

**Comment by timoschwarzer** [comment]
Found the issue. Submitting PR...

**Comment by timoschwarzer** [comment]
Fixed in https://github.com/laravel/framework/pull/31261

**Comment by litan1106** [comment]
I noticed the redis publish was different between these version.

**laravel/framework 6.10.1 logs**
"SELECT" "4"
"PUBLISH" "redis_prefix_test_channel.1234" "{\"event\":\"App\\\\Events\\\\Broadcast\\\\TestEvent\",\"data\":{\"orderId\":1234},\"socket\":null}"

**laravel/framework 6.13 logs**
"SELECT" "4"
"EVAL" "for i = 2, #ARGV do\n  redis.call('publish', ARGV[i], ARGV[1])\nend" "0" "{\"event\":\"App\\\\Events\\\\Broadcast\\\\TestEvent\",\"data\":{\"orderId\":1234},\"socket\":null}" "redis_prefix_test_channel.1234"
[4 lua] "publish" "redis_prefix_test_channel.1234" "{\"event\":\"App\\\\Events\\\\Broadcast\\\\TestEvent\",\"data\":{\"orderId\":1234},\"socket\":null}"
