### ISSUE TITLE
Private channels, token mismatch on /broadcasting/auth route

### ISSUE THREAD

**Issue by s3rg3** [tlaverdure/laravel-echo-server#48]
Hello,

i can send message on normal channel, but can't get private channel to work because of a token mismatch.

isn't laravel-echo-server or laravel-echo are supposed to automatically pass x-csrf-token and x-socket-id to the /broadcasting/auth route?

If so it's not working for me and if not what i'm missing and how can i pass them to laravel-echo-server or laravel-echo?

**here is my view:**

@extends('layouts/template')

@section('js')
	script src="https://cdn.jsdelivr.net/vue/1.0.27/vue.js"></script>
	script src="https://cdn.jsdelivr.net/vue.resource/1.0.3/vue-resource.min.js"></script>
        script src="{{url('/')}}:8443/socket.io/socket.io.js"></script>
	script src="{{url('/js/laravelecho.js')}}"></script>
@endsection

@section('contenu')
	div id="app" class="col-lg-12 col-md-12 diffusion">
		li>
			div>
				img class="img-rounded" src="{{url('/images/avatars/'.$avatar)}}">
				div style="width:7px;display:inline-block;"></div>
				div class="bulle3 right5 inline-block align-top">
					input v-model="chat_input" @keyup.enter="handleIt" placeholder="Entrez votre message ici ..." maxlength="140"/>
				/div>
			/div>
		/li>
		ul id="chatMessages"></ul>
	/div>

	<script type="text/javascript">	
		new Vue(
		{
			el: '#app',
			
			ready()
			{
				this.listen();
			},
			
			data:
			{
			  chat_input: '',
			  room: '{{Auth::user()->name}}',
			},
			
			methods:
			{
				handleIt: function()
				{
					this.$http.post('{{url('/')}}/msg',{message: this.chat_input, room: this.room});
					$("#chatMessages").prepend(this.chat_input);
					$("#chatMessages").scrollTop($("#chatMessages")[0].scrollHeight);
					this.chat_input = '';
				},
				
				listen: function()
				{
					Echo.private('room.{{Auth::user()->name}}')
					.listen('ChatMessageWasReceived', (e) => {
						$("#chatMessages").prepend('<p>'+e.user+':&nbsp;'+e.chatMessage+'</p>');
						$("#chatMessages").scrollTop($("#chatMessages")[0].scrollHeight);
					});
					
					Echo.join('room.{{Auth::user()->name}}')
					.here((users) => {
						//
					})
					.joining((user) => {
						console.log(user.name);
					})
					.leaving((user) => {
						console.log(user.name);
					});
				}
			}
		})	
	</script>
		
</section>
@endsection

**here is the content of /assets/js/laravelecho.js**

window._ = require('lodash');

/**
 * We'll load jQuery and the Bootstrap jQuery plugin which provides support
 * for JavaScript based Bootstrap features such as modals and tabs. This
 * code may be modified to fit the specific needs of your application.
 */

window.$ = window.jQuery = require('jquery');
require('bootstrap-sass');

/**
 * Vue is a modern JavaScript library for building interactive web interfaces
 * using reactive data binding and reusable components. Vue's API is clean
 * and simple, leaving you to focus on building your next great project.
 */

window.Vue = require('vue');
require('vue-resource');
Vue.use(VueResource);

/**
 * We'll register a HTTP interceptor to attach the "CSRF" header to each of
 * the outgoing requests issued by this application. The CSRF middleware
 * included with Laravel will automatically verify the header's value.
 */

Vue.http.interceptors.push((request, next) => {
    request.headers['X-CSRF-TOKEN'] = Laravel.csrfToken;

    next();
});

/**
 * Echo exposes an expressive API for subscribing to channels and listening
 * for events that are broadcast by Laravel. Echo and event broadcasting
 * allows your team to easily build robust real-time web applications.
 */

import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'https://example.com:8443'
});

**here is laravel-echo-server.json:**

{
	"appKey": "e713e9en1ojlrnadm4ffftqqa7a2isqg6n260obm44n1lc269q5m4sd4g5qc",
	"authHost": "https://example.com",
	"authEndpoint": "/broadcasting/auth",
	"database": "redis",
	"databaseConfig": {
		"redis": {}
	},
	"devMode": false,
	"host": "example.com",
	"port": "8443",
	"protocol": "https",
	"referrers": [],
	"sslCertPath": "/etc/letsencrypt/live/example.com/fullchain.pem",
	"sslKeyPath": "/etc/letsencrypt/live/example.com/privkey.pem",
	"verifyAuthPath": true,
	"verifyAuthServer": true
}

**Comment by jonnywilliamson** [comment]
Not sure if it will help you but in my webpage I have this in my template

```html
<html>
<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

```

And everything worked out of the box, I didn't have to add any other code to deal with the csrf token.

**Comment by s3rg3** [comment]
I also have this in my template but this is not working :(

```
<meta name="csrf-token" content="{{ csrf_token() }}">
<script type="text/javascript"> window.Laravel = <?php echo json_encode(['csrfToken' => csrf_token(),]); ?></script>
<script type="text/javascript">$.ajaxSetup({headers: { 'X-CSRF-Token' : $('meta[name=csrf-token]').attr('content') }});</script>
```

Thank you for your help jonnywilliamson

**Comment by jonnywilliamson** [comment]
You say your public ones are working but the private ones are not?

Does it say you are getting a token mismatch?

Here's a helpful way to debug what is being sent in the websocket. Use google chrome, and open your webpage and open the developer tools (windows F12).

Refresh the page and look at the network menu item. Then click on the WS tab towards the right and look to see if your app make a websocket in the colum.

Select the websocket and then you'll be able to click on the frames tab and watch any and all data being passed from you app to the echo server and vice versa.

Here's a picture of mine in action, you can see the request being sent out with the token included. Perhaps you should check if yours is doing that too....

https://github.com/tlaverdure/laravel-echo-server/issues/53#issuecomment-252237311


Perhaps it might help

**Comment by s3rg3** [comment]
> You say your public ones are working but the private ones are not?

Yes, public are working fine because you can suscribe to the channel without requesting authorization to laravel.

But in private you can't suscribe to the channel because you have to request authorization to laravel and it don't work, the csrf token is not added to the request neither the socket-id.

i can send private message, but no one can suscribe on the channel for listenning to them.


> Does it say you are getting a token mismatch?

After the launch of the laravel-echo-server in a terminal, for each attempt to subscribe to a private channel i get this error:
 
null
Could not send authentication request.
(node:8686) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object

in laravel-echo-server/src/channels/private-channel.ts, on line 63 you have :

Log.error(error);

if you change this to:

Log.error(JSON.stringify(body));

you can have the request body of this error, wich is about  token mistmatch.


> Here's a picture of mine in action, you can see the request being sent out with the token included. Perhaps you should check if yours is doing that too....

i only got 2probe, then 3probe, then 5, then 2, then 3, and it's keep reppeatting 2 and 3.

i'm on https, i should try it with http.

**Comment by s3rg3** [comment]
i just found why i couldn't have the csrfToken on the websocket.

if you put your app.js in the header laravel-echo can't extract the csrfToken from the view, app.js must be at the end of the view.

**Comment by ahmetugur91** [comment]
> <script type="text/javascript"> window.Laravel = <?php echo json_encode(['csrfToken' => csrf_token(),]); ?></script>


this one worked for me.
