### ISSUE TITLE
Is there a connection limit? We seem to be getting errors when the load is high

### ISSUE THREAD

**Issue by mwleinad** [tlaverdure/laravel-echo-server#480]
We run a big server and although the socket server is standalone we still run into this
Is there any configuration on the server/json that we can do to allow more connections/channels?

Thanks

**Comment by bobdobs** [comment]
I am about to launch a new version of my site with laravel-echo-server and got a little concerned after reading your message. How busy is your site? 

I have also been thinking that raising ulimit and maybe optimzing network in sysctl.conf could be important for busy sites that run websockets.

**Comment by jinseokoh** [comment]
Try increasing # of file descriptors as described in the following link.

[https://docs.beyondco.de/laravel-websockets/1.0/faq/deploying.html](https://docs.beyondco.de/laravel-websockets/1.0/faq/deploying.html)

**Comment by mwleinad** [comment]
Just FYI, increasing # of file descriptors worked @bobdobs
