### ISSUE TITLE
Multi subdomain support

### ISSUE THREAD

**Issue by MilosR** [tlaverdure/laravel-echo-server#49]
What configuration is needed in case of multi subdomain client app? 
Cant figure out those referrers...

**Comment by hfalucas** [comment]
Is there any answer or official recommendation for this? :)

**Comment by barryvdh** [comment]
Referrers are only need for the http subscriber, right? Not for the default Redis method or client connection I think.

**Comment by tlaverdure** [comment]
This feature has landed. https://github.com/tlaverdure/laravel-echo-server/pull/190
