### ISSUE TITLE
how to receive from .net c# winform program

### ISSUE THREAD

**Issue by nomedia** [tlaverdure/laravel-echo-server#492]
I want to build a windows socket client.  how to use C# language to receive echo's socket.
this is my c# code. but it didn't work.

` 

try
            {

              //  IPHostEntry hostInfo = Dns.GetHostEntry("47.100.46.2");
           //     IPAddress ipAddress = hostInfo.AddressList[0];

             //   txt_IP = "superpao.aiweber.com/socket";
             //   txt_Port = "80";
                socketSend = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
                IPAddress ip = IPAddress.Parse("47.130.46.12");
                socketSend.Connect(ip, 3333);
                //实例化回调
                setCallBack = new SetTextCallBack(SetValue);
                receiveCallBack = new ReceiveMsgCallBack(SetValue);
                // this.Label.Invoke(setCallBack, "连接成功");

                this.label1.Text = "receive  successful"+ receiveCallBack.ToString();
            //    MessageBox.Show("lianjieco:" + setCallBack.ToString());
                //开启一个新的线程不停的接收服务器发送消息的线程
                threadReceive = new Thread(new ThreadStart(Receive));
                //设置为后台线程
                threadReceive.IsBackground = false;
                threadReceive.Start();
            }
            catch (Exception ex)
            {
                MessageBox.Show("连接服务端出错:" + ex.ToString());
            }
}
`

**Comment by ssatz** [comment]
@nomedia 

check out the  [StackExchange Redis](https://stackexchange.github.io/StackExchange.Redis/)

below is the sample code which i am using to connect Laravel and .Net

```
subscriber.Publish(campaginProcess, JsonConvert.SerializeObject(new Channel
                        {
                            @event = "Status",
                            data = new Data
                            {
                                uid = JObject.Parse(this.campaignId).GetValue("uid").ToString(),
                                status = Convert.ToInt32(CampaignStatus.Processing)

                            }
                        })).ToString();
```
