### ISSUE TITLE
Allow clients to alter authEndpoint

### ISSUE THREAD

**Issue by adm-bome** [tlaverdure/laravel-echo-server#498]
See pull request #497

**Comment by adm-bome** [comment]
@tlaverdure Can u review this PR?

**Comment by pfaffenrodt** [comment]
@adm-bome thanks, that feature is what we also need.

@tlaverdure We use sanctum and session auth together. 

```
        Broadcast::routes();
        Broadcast::routes(['prefix' => 'api', 'middleware' => ['api', 'auth:sanctum']]);
```

## Workaround  
Workaround would be to switch full on sanctum auth.

```
        Broadcast::routes(['middleware' => ['api', 'auth:sanctum']]);
```

**Comment by adm-bome** [comment]
It looks like no features are approved/reviewed.
Only fixes are reviewed and merged.

Its better to run multiple instances than adaptable code by config. But he is right. You could do a setup with multiple instances. And when you need more resources expand your setup with x times more instances...
Obviously @tlaverdure has a big wallet :+1:

**Comment by pfaffenrodt** [comment]
@tlaverdure this is cleary expensive, what @adm-bome tried to point out. Your decision makes me sad, because @adm-bome pull-request works fine.

**Comment by adm-bome** [comment]
Yes, the solution provided to run multiple instances is expensive, both in resources as in costs. 
And when it comes to the costs. I rather put my money into redis-, database- or laravel instances.

Laravel can support multiple strategies to authenticate, wher the client only supports 1 strategy.
When writing a client/app, developers know the strategy so why not configure this optionaly in the client when needed.

> side note: within pusher this is already an accepted way.
