### ISSUE TITLE
error running on live https server

### ISSUE THREAD

**Issue by ctf0** [tlaverdure/laravel-echo-server#50]
- Laravel v5.3.15
- laravel-echo-server v1.0.12
- node v6.7.0

``` bash
L A R A V E L  E C H O  S E R V E R

Starting server...

✔ Running at something.com on port 6001
✔ Channels are ready.
✔ Listening for redis events...
✔ Listening for http events...

Server ready!

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 104.31.85.98:6001
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1239:19)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```

here is the init info aswell

``` js
{
    "appKey": "xxx",
    "authEndpoint": "/broadcasting/auth",
    "authHost": "",
    "database": "redis",
    "databaseConfig": {
        "redis": {},
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        }
    },
    "devMode": false,
    "port": "6001",
    "referrers": [],
    "verifyAuthPath": true,
    "verifyAuthServer": true,
    "host": "something.com",
    "protocol": "https",
    "sslCertPath": "/etc/nginx/ssl/something.com/server.crt",
    "sslKeyPath": "/etc/nginx/ssl/something.com/server.key"
}
```

and here is the console error

``` js
socket.io.js:3511 GET https://something.com:6001/socket.io/?EIO=3&transport=polling&t=LUD08rI net::ERR_CONNECTION_REFUSED
```

**Comment by tlaverdure** [comment]
Looks like an error with the port. You sure that you don't have an instance already running on the same port?

**Comment by ctf0** [comment]
nop :(, i double checked for the port number and this one is free

**Comment by jonnywilliamson** [comment]
That ip address is a cloud flare ip address.

It's likely cloudflare is getting in the way of your connection in some manner.

**Comment by ctf0** [comment]
i stoped cf, and back to my public ip but nothing changed

**Comment by IamSwap** [comment]
Any updates on this? Facing same issue!

**Comment by rorymcdaniel** [comment]
Just a thought, I had this same issue, I was trying to run laravel-echo-server on my computer, but instead I should have been running it on the Vagrant host. That resolved it for me.

**Comment by ctf0** [comment]
@rorymcdaniel its working fine on vagrant but on live https server sadly its not :(

**Comment by IamSwap** [comment]
any updates on this?

**Comment by ctf0** [comment]
i used pusher instead but it takes almost 10 seconds on each page load just to connect to the service.

**Comment by ctf0** [comment]
@tlaverdure any news over this ?

**Comment by marcospaulomc** [comment]
Try to change host to 127.0.0.1.
I've had the same error, but it worked for me.

**Comment by tlaverdure** [comment]
This works perfectly fine for me with a similar configuration. Only thing that I ran to is that I needed to run the command to start with `sudo` since the certificate files are located in the `etc` directory.

**Comment by mahdi4187** [comment]
`kill -9 $(lsof -t -i:PORT)`
