### ISSUE TITLE
Disconnect current connection when not authenticated

### ISSUE THREAD

**Issue by haunterpokem** [tlaverdure/laravel-echo-server#51]
I am currently using laravel passport for oauth2 as my authorization for my broadcast auth.I have a short-lived access token and will expire every 1 hour. When I try to pass an invalid or expired access token, echo server would log an error that it can't authenticate request "_Could not send authentication request_" but the connection from the client is still alive. Client can't determine if it was successfully connected and can listen to channels or not.

**Comment by liaosankai** [comment]
@haunterpokem

Before feature implement I try modify line 107 in `laravel-echo-server/src/channels/channel.ts` and `npm run compile` 

```js
/**
 * Join private channel, emit data to presence channels.
 *
 * @param  {object} socket
 * @param  {object} data
 * @return {void}
 */
joinPrivate(socket: any, data: any): void {
	this.private.authenticate(socket, data).then(res => {
		socket.join(data.channel);

		if (this.isPresence(data.channel)) {
			this.presence.join(socket, data.channel, res.channel_data);
		}

		this.onJoin(socket, data.channel);
	}, error => {
		socket.emit('echo:error', data.channel, 'unauthorized');
	});
}
```

"error" is a reserved event in socket.io (https://github.com/socketio/socket.io/issues/2285) , so I replace with "echo:error". The following are examples of Client:

```js
Echo.join('chat.' + roomId)
	.on('echo:error', (err) => {
		console.log(err);
	})
	.here((users) => {
		//
	})
	.joining((user) => {
		console.log(user.name);
	})
	.leaving((user) => {
		console.log(user.name);
	});
```

**Comment by haunterpokem** [comment]
Thanks @liaosankai, when are you going to send a pull request for this? If you wouldn't mind. Maybe we could put some status code for other types of error that might occur?

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
