### ISSUE TITLE
Laravel Sanctum annd laravel echo

### ISSUE THREAD

**Issue by radudiaconu0** [tlaverdure/laravel-echo-server#511]
how can i configure laravel echo with sanctum and laravel-echo-server in a vue project? i get error 419 csrf token missmatch.I set the referer header with laravel domain  and vue doamin and same result. i tried to set authorization header with the csrf token from cookie still same result. How can i accomplish this?

**Comment by silasrm** [comment]
You solve this question? If yes, how?
