### ISSUE TITLE
Change Path

### ISSUE THREAD

**Issue by allaniftrue** [tlaverdure/laravel-echo-server#512]
Add feature to change path.  Example `/socket.io` to `/ws`

**Comment by tlaverdure** [comment]
In your laravel-echo.server.json use `socket.io` parameter to change. https://github.com/tlaverdure/laravel-echo-server#configurable-options

**Comment by allaniftrue** [comment]
I actually tried it but still resulted in a CORS issue

`socketio: {
   attach: { path: '/echo' }
}`
