### ISSUE TITLE
Add support for multiple nodes with socket.io-redis

### ISSUE THREAD

**Issue by radudiaconu0** [tlaverdure/laravel-echo-server#514]
**Is your feature request related to a problem? Please describe.**
Add support for multiple nodes with socket.io-redis. It is good for scalability;)
**Describe the solution you'd like**
i've seen a pull request from 2017 with review tag wich has not merged or reviewed yet...
https://github.com/tlaverdure/laravel-echo-server/pull/229

**Comment by tlaverdure** [comment]
Aware of the PR will be reviewing when I have time to test.
