### ISSUE TITLE
laravel-echo-server on port 6001 gives This site can’t be reached with apache and SSL

### ISSUE THREAD

**Issue by imdhemy** [tlaverdure/laravel-echo-server#518]
**Description**
I'm running a Laravel application using *apache server* , after initializing laravel-echo-server and completing its configuration with Supervisor, I could not access the public `my-site.com:6001` from my browser.

When I run `curl HTTP://127.0.0.1` I get
```
curl: (52) Empty reply from server
```

**BUT** when I run `curl https://127.0.0.1:6001 -k` I get
```
OK
```
which is the proper expected response.

**Additional information**
- I'm using Let's Encrypt + certbot
- The log shows the following:
```
L A R A V E L  E C H O  S E R V E R

version 1.6.2

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

```

**Comment by imdhemy** [comment]
Since I'm running Centos 7, I used `firewall-cmd` to enable the port 6001

**Comment by halberio** [comment]
+1
