### ISSUE TITLE
Socket ID

### ISSUE THREAD

**Issue by pfeiferchristopher** [tlaverdure/laravel-echo-server#54]
With Pusher.io Laravel Echo will send the current user's socket id to the session so that Laravel doesn't broadcast events to the current user in some situations. 

Is this functionality non-existent with redis/socket.io setup?

**Comment by tlaverdure** [comment]
Should work. Looks like it needed to be updated and has been fixed here:
https://github.com/tlaverdure/laravel-echo-server/pull/55
