### ISSUE TITLE
prexfix for routes endpoints for socket.io/socket.io.js (AWS ALB) 

### ISSUE THREAD

**Issue by marafee1243** [tlaverdure/laravel-echo-server#540]
**Is your feature request related to a problem? Please describe.**
This app ports the ports, I want to do a proxy by adding a prefix name to all routes.

Current : <script src="//app.dev:6001/socket.io/socket.io.js"></script>
Featured : <script src="//app.dev:6001/new-prefix-url/socket.io/socket.io.js"></script>

**Additional context**
I am running this app on EC2 using pm2 and ALB for proxy

**Comment by nikhilo6july** [comment]
handle proxy on TargetGroup Level
