### ISSUE TITLE
Feature Request: authPort in configuration

### ISSUE THREAD

**Issue by notliable** [tlaverdure/laravel-echo-server#56]
Hi there!

Would it be possible to add a configuration option that allows us to set the port of the Laravel instance used for auth?
I'm currently using Cloud9 as my editor and Apache is running on port 8080. I tried specifying the port in the "authHost" config option, but to no avail.
```json
{
  "authHost": "127.0.0.1:8080"
}
```

Thanks!

**Comment by notliable** [comment]
I found a workaround. As it seemed like the authHost option was being parsed as an URI, I specified the protocol AND port. That worked.

```json
{
  "authHost": "http://127.0.0.1:8080"
}
```

**Comment by tlaverdure** [comment]
Thanks closing this then.
