### ISSUE TITLE
Client app connected to laravel echo server

### ISSUE THREAD

**Issue by abdosaeedelhassan** [tlaverdure/laravel-echo-server#575]
Hi, my client app is

`
 <script src="//tyqn.test:3001/socket.io/socket.io.js"></script>
    <script>
        var socket = io('tyqn.test:3001');
        socket.on('app-events:1', function (data) {
            console.log(data);
        });
        socket.on('connect', () => {
            console.log('socket.io successfully connected')
        });
    </script>
`
i received that successfully connected, but i can't receive data from fired event, inside laravel it worked as follow

window.Echo.channel('Tyqnapp-events')
        .listen('.app-events:' + user_id, (data) => {
});

i need help to receive data in client app

**Comment by krosh961** [comment]
try version socket.io-client: 2.4

**Comment by abdosaeedelhassan** [comment]
Thank you
