### ISSUE TITLE
Laravel Echo Server work and client side error only at server

### ISSUE THREAD

**Issue by Thihasoehlaing** [tlaverdure/laravel-echo-server#597]
I use laravel echo server and socket.io-client and running at localhost is work at port 6001 and I config at server and use port 8443. Events and laravel echo server work. When client side connect, got 200 success and got Remote Address: ip:443 instead of ip:8443.

laravel 7.0 
laravel-echo-server 1.6.3 
socket.io-client 2.3.0

Here is [link](https://stackoverflow.com/questions/73018402/laravel-echo-server-and-socket-io-client-doest-work-on-server) at stackoverflow

**Comment by parallels999** [comment]
https://github.com/tlaverdure/laravel-echo-server/issues/584#issuecomment-962614453

**Comment by Thihasoehlaing** [comment]
I found solution that is a little code in nginx config. Thanks.
