### ISSUE TITLE
Connecting to a socket behind an SSL

### ISSUE THREAD

**Issue by bostinait** [tlaverdure/laravel-echo-server#6]
Hi, are there any immediate or not so immediate plans to support SSL protected sockets?

Many thanks,

Tim

**Comment by tlaverdure** [comment]
Hey, yeah let me check on this. There is a [PR](https://github.com/tlaverdure/laravel-echo-server/pull/7) submitted and I also have a couple ideas.

**Comment by tlaverdure** [comment]
Support for SSL has been added. Please check the docs.

**Comment by bostinait** [comment]
Excellent! Thank you very much!
