### ISSUE TITLE
Events being duplicated

### ISSUE THREAD

**Issue by pfeiferchristopher** [tlaverdure/laravel-echo-server#60]
So even though I have `$this->dontBroadcastToCurrentUser();` in the constructor for a public event it is still being sent to the current user. I've checked and my Echo client is sending the `X-Socket-Id` header so that `laravel-echo-server` should be able to filter out events for the current user's socket id but I'm not sure where to start debugging this.

**Comment by tlaverdure** [comment]
When you post to your laravel application with the X-Socket-Id, ensure that it matches the socketID that is being broadcasted to Redis. Maybe try a dd in your broadcasting event.

Here is the relevant code on laravel-echo-server.
https://github.com/tlaverdure/laravel-echo-server/blob/master/src/echo-server.ts#L148-L165

**Comment by pfeiferchristopher** [comment]
It is indeed exactly the same.

Here's showing the post request that triggers the event, and I've dd'd the event and you can see the socket id is apart of the event object.

![image](https://cloud.githubusercontent.com/assets/9256168/19585736/8b482910-9714-11e6-863e-e1d094ad4cec.png)

Then in the tooltip you can see it is the same as the current socket id but I'm still getting the event.

**Comment by pfeiferchristopher** [comment]
@tlaverdure any ideas?

**Comment by tlaverdure** [comment]
Think you may be implementing this wrong on the Laravel side. If both socket ids match on both laravel and laravel echo server then you should be good to go.

When the message is broadcasted to redis is should contain the socket id. With that in hand laravel echo server can broadcast a message as that socket:

``` js
socket.broadcast.to(channel).emit(message.event, channel, message.data);
```

I believe `$this->dontBroadcastToCurrentUser();` was depreciated and you need to use `->toOthers()` on your `broadcast()` method.


Example from docs:

https://laravel.com/docs/5.3/broadcasting#only-to-others
``` php
broadcast(new ShippingStatusUpdated($update))->toOthers();

```

Hope that helps.

**Comment by pfeiferchristopher** [comment]
Well, I just reread the documentation and I still feel is functioning incorrectly.

The point as I can read is that `->toOthers()` is to *not* broadcast to the current users socket vs broadcasting specifically on that socket like it looks like your code does. And from what you just said, "contain the socket id. With that in hand laravel echo server can broadcast a message as that socket."

Wouldn't broadcasting a message as "that socket" mean *only* the current user would get it?

**Comment by pfeiferchristopher** [comment]
I do understand I could be understanding how socket.io works.

**Comment by pfeiferchristopher** [comment]
@tlaverdure 

https://github.com/laravel/framework/blob/6cf003ae02582cf716c10a723ef6bc19690969e7/src/Illuminate/Broadcasting/PendingBroadcast.php#L46-L58

`toOthers()` just runs `dontBroadcastToCurrentUser()` haha I'm so confused now..

**Comment by pfeiferchristopher** [comment]
@jonnywilliamson perhaps you could shine some light on this for me.

**Comment by pfeiferchristopher** [comment]
@tlaverdure so looking through the `socket.io` client library I see that by using `.broadcast()` on a `socket` instance it broadcasts to all other sockets, except the one sending it. Odd usage for it but I see it is indeed not an issue with your package.

Although I still don't know why events are going to the current user as well.

**Comment by Xationch** [comment]
@pfeiferchristopher I've exactly the same issue with Laravel 5.5 and Vue / Axios You found a solution ?

**Comment by pfeiferchristopher** [comment]
Sorry, haven't worked on this project since a few weeks after my last comment.

**Comment by lin4you** [comment]
You have to use the trait InteractsWithSockets. Than the call of dontBroadcastToCurrentUser() method makes sense.

**Comment by ctf0** [comment]
incase someone is having the same issue, 
- check https://laravel.com/docs/5.6/broadcasting#only-to-others
- for laravel defaults to work you have to register `echo` after `axios` or add the headers manually.

**Comment by eddyson1006** [comment]
Same problem for me.
All socket authentication, broadcast and others are working for me, except for "toOthers()". Somehow, it still broadcast the content to the sender. Let's say the event triggered is by API, how should we link the API to use their X-Socket-ID?

a) Client side
bootstrap.js
`import Echo from "laravel-echo"`
`window.io = require('socket.io-client');`
`// Have this in case you stop running your laravel echo server`
`if (typeof io !== 'undefined') {`
`  window.Echo = new Echo({`
`    broadcaster: 'socket.io',`
`    host: 'http://mysite.test:6001',`
`    encrypted: true`
`  });`
`}`

welcome.blade.php
`window.Echo.connector.options.auth.headers['Authorization'] = 'Bearer ' + 'xxxxxxxxxxxxx';`
`var channel = '5c36ca48fa6f3f2f280030bf';`
`console.log('Joining channel: ' + channel + '...');`
`console.log('Listening to ConversationActivity...');`
`                window.Echo.private(channel)`
`                    .listen('ConversationActivity', (e) => {`
`                        console.log('New Conversation: ' + e.data.message);`
`});`
_______________________________
b) Server side
`............`
`use Illuminate\Broadcasting\InteractsWithSockets;`
`..........`

`class ConversationService`
`{`
`    ......`
`    use InteractsWithSockets;`
`    broadcast(new ConversationActivity($conversation))->toOthers();`
`    ......`
`}`
