### ISSUE TITLE
Is the cors configuration even working?

### ISSUE THREAD

**Issue by mwleinad** [tlaverdure/laravel-echo-server#602]
Well, what I'm trying to actually do is to send the https cookies on the websocket request, but I've not been able to do it.
But I'm just playing around with the json configuration and it looks like the cors config is not even working or doesn't have any effect at all.

Using laravel-echo-server 1.6.0 (Maybe I need to upgrade?)

**To Reproduce**
Here's part of my json file (the important part is the socketio piece

{
    "authHost": "https://dev.ilosvideos.com",
    "devMode": true,
    "host": "0.0.0.0",
    "port": "3000",
    "protocol": "http",
    "socketio": {
         "cookie": { "sameSite": "none", "secure": true },
         "cors": {
             "origin": "http://google.com",
             "method": ["DELETE"],
             "allowedHeaders": ["Authorization, Cookie"],
             "credentials": true
         }
     },
}

**Expected behavior**
I expect this to fail, cors is all wrong and this is connecting from localhost to a different host

**Additional context**
Connection to private channel is successful
![image](https://user-images.githubusercontent.com/15146158/195673868-347e9ac7-8375-40f9-b816-c49ed25c25fa.png)

**Comment by jose123v** [comment]
This package is abandoned
