### ISSUE TITLE
Best Practice Running Laravel Echo Server as Background Service

### ISSUE THREAD

**Issue by bendo01** [tlaverdure/laravel-echo-server#65]
hi, i want to ask
are there any best practice using Laravel Echo Server On Production Server as background service
like queue process on laravel documentation suggestion using supervisord,
is Laravel Echo Server can be run with pm2 or nodaemon?
thanks a lot

**Comment by pfeiferchristopher** [comment]
I'm running it with supervisor right now. Working perfectly for me, on my production server I've done the same except I had to use an absolute path to `node` in order to get the global installation of this package to fire up properly but it works great now.

**Comment by bendo01** [comment]
@pfeiferchristopher Thank You, I Will Try It With Supervisor

**Comment by jonnywilliamson** [comment]
Here's a copy of the supervisor config file I have for my echo server for a rough guideline (on a vagrant machine)

```
[program:echo-server]
directory=/home/vagrant/path/to/your/project
command=/usr/bin/laravel-echo-server start
autostart=true
autorestart=true
user=vagrant
redirect_stderr=true
stdout_logfile=/home/vagrant/path/to/your/project/storage/logs/echoserver.log
```

**Comment by andkom** [comment]
example pm2 configuration:

echo.json:
```
{
  "name": "echo",
  "script": "laravel-echo-server",
  "args": "start"
}
```

command:

`pm2 start echo.json`

**Comment by jonnywilliamson** [comment]
@andkom Just to clarify though, using PM2 doesn't help with regard restarting the process if it exits? You'd still need supervisor/upstart etc?

**Comment by trip-somers** [comment]
Is there a way to kill/restart the Laravel Echo Server when/if a new configuration goes live? This would be something akin to how Laravel allows you to restart your queue workers: ```php artisan queue:restart```

**Comment by trip-somers** [comment]
Does no one ever need to restart their Echo server?

**Comment by andkom** [comment]
@jonnywilliamson 
pm2 restart will restart echo process

**Comment by barryvdh** [comment]
You can also just restart with supervisor. Don't know if there is a 'graceful' restart, but with the latest echo, the clients should just reconnect when the server is back.

**Comment by trip-somers** [comment]
Thanks, @barryvdh. I finally had time to look into that. I probably should have looked there first.

**Comment by ThunderBirdsX3** [comment]
@andkom How to call with config file `laravel-echo-server.json`

**Comment by catalinux** [comment]
That json config file it will be loaded by default. You need to run the server in the directory where the config file is placed

**Comment by wa05** [comment]
I cant set PM2 (2.6.1) on Windows 7 with Node v8.1.4

PM2 Log:

C:\USERS\WALTER\APPDATA\ROAMING\NPM\LARAVEL-ECHO-SERVER.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (C:\Users\Walter\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:70:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)


I'll try to run laravel-echo-server from a .bat and start the .bat with the Windows task scheduler or try to make work Supervisord on Windows creating a service with cygwin and python..  :/

**Comment by jartaud** [comment]
Same as @wa05 [comment](https://github.com/tlaverdure/laravel-echo-server/issues/65#issuecomment-329679558)

`Node: v8.9.1`
`Npm: 5.5.1`
`Win10`

**Comment by wa05** [comment]
@jartaud tell me if you can run the daemon with this https://github.com/coreybutler/node-windows

**Comment by anddyyao** [comment]
Same as @wa05  
why

**Comment by wa05** [comment]
Finally Im running it with windows task manager..

**Comment by peters305** [comment]
> You can also just restart with supervisor. Don't know if there is a 'graceful' restart, but with the latest echo, the clients should just reconnect when the server is back.

Hey Barry if you don't mind  its little bit late but i was asking i want to start laravel-echo-server but i have dist folder after running npm build which includes index.html file how can start this
