### ISSUE TITLE
Running this inside Docker

### ISSUE THREAD

**Issue by rafalglowacz** [tlaverdure/laravel-echo-server#66]
I can't get it to work inside a Docker container. If I do this:

`docker-compose exec app curl http://localhost:6001/socket.io/socket.io.js`

then it works, but if I do this:

`curl http://localhost:6001/socket.io/socket.io.js`

then the connection is "reset by peer".

The port 6001 is open, if I put anything else on it then I can access it.

I think I might be confused regarding what a referrer is here. If it's inside Docker and all the server names are "localhost", do I need to use `laravel-echo-server referrer:add` anyway? I tried it with a few different values ("localhost", the IP of the container, the service name of the container) but none of them worked for me.

**Comment by rafalglowacz** [comment]
Ok, after some more fiddling I was able to make it work. I changed host to 0.0.0.0 in `laravel-echo-server.json`:

```
{
...
	"host": "0.0.0.0",
...
}
```

Now it works, I'm not sure why, but it does.

**Comment by jonnywilliamson** [comment]
This post is long but it might help provide you with some answers.

Basically if you use localhost/127.0.0.1, then the script binds to localhost which may have been set up to only allow connections from INSIDE your container....

Hence when you try to connect to it from your webpage thats OUTSIDE the container, it won't work.

When you use 0.0.0.0 you are telling the library to bind to ALL devices and so an outside connection WILL get to your echo server.

Here's much more detail:

https://github.com/tlaverdure/laravel-echo-server/issues/33

**Comment by rafalglowacz** [comment]
@jonnywilliamson Thanks for the link, I like your breakdown of the issue. I'll have to check if leaving the host blank will work for me too, looks like that gets you the default behavior for Node.js servers and it might be preferred for production. But I'll look into that at some other time, for now I'm just happy I can try Echo in a docker container.
