### ISSUE TITLE
Laravel-echo-server running in docker, resolve the local address as IP !

### ISSUE THREAD

**Issue by toby1991** [tlaverdure/laravel-echo-server#72]
here are my **laravel-echo-server.json**
```javascript
{
	"appKey": "o7gq6d4m56rkm3ipaphd1cqagj2lsacogbo25bgfhra05n847jcu5li68jbc",
	"authHost": "http://app.local",
	"authEndpoint": "/broadcasting/auth",
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"host": "redis",
			"port": "6379",
			"db": "0"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "0.0.0.0",
	"port": "6001",
	"referrers": [],
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}
```  
![5c7647c7-1150-4b48-ad9f-06b01f1c6573](https://cloud.githubusercontent.com/assets/5897356/20002655/e381fa76-a2bc-11e6-9565-1e330b5c8a6b.png)

It says ```ECONNREFUSED```. It's lookup DNS from app.local from ```/etc/hosts```.  And it uses 127.0.0.1 as the DNS lookup result for authHost. **That's the problem !**
  
I've change the authHost to ```http://www.google.com```, that's the result:  
![image](https://cloud.githubusercontent.com/assets/5897356/20003080/45275292-a2bf-11e6-8c4e-7d0cc2113637.png)

 So I change the authHost to my LAN IP like ```http://10.1.199.204```, and bind all my project entrance to ```http://10.1.199.204```,  **problem solved.**
![0caef49e-1738-4246-85b1-1326ee1ebf17](https://cloud.githubusercontent.com/assets/5897356/20003096/6d89fba4-a2bf-11e6-9c48-774fe7153afc.png)

**Comment by toby1991** [comment]
https://github.com/tlaverdure/laravel-echo-server/issues/11

**Comment by toby1991** [comment]
https://github.com/tlaverdure/laravel-echo-server/issues/11

**Comment by toby1991** [comment]
https://github.com/tlaverdure/laravel-echo-server/issues/11

**Comment by toby1991** [comment]
https://github.com/tlaverdure/laravel-echo-server/issues/11

**Comment by toby1991** [comment]
https://github.com/tlaverdure/laravel-echo-server/issues/11

**Comment by toby1991** [comment]
why does the client left the channel after join with nothing output ?

**Comment by toby1991** [comment]
>

**Comment by ModernArtisan** [comment]
@toby1991 Ok, but what if my application locates not on default server root(http://10.1.199.204), what if I have different domain name like `http://example.dev`?
