### ISSUE TITLE
{"error":"Unauthorized"}

### ISSUE THREAD

**Issue by hbj418** [tlaverdure/laravel-echo-server#75]
I have success install the laravel-echo-server by:
 npm install -g laravel-echo-server

and configure the socket server by:
laravel-echo-server init
laravel-echo-server referrer:add v5.3.laravel.com

and also list the configure file:

{
	"appKey": "mm9tmq9splj3lssh6ear5ieplqmckf2kjg754js39hm2l66gjabor3crh1qq",
	"authHost": "laravel_echo_server.com",
	"authEndpoint": "/broadcasting/auth",
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "laravel_echo_server.com",
	"port": "6001",
	"referrers": [
		{
			"host": "v5.3.laravel.com",
			"apiKey": "d26smjrboqgo93e9733ro7l7209r92hq9lsimgqkgiabe7h16llkf5e2kmrf"
		}
	],
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}

I have pointed the laravel_echo_server.com to 127.0.0.1

launch the server by:

$: laravel-echo-server start

L A R A V E L  E C H O  S E R V E R

⚠Starting server in DEV mode...

✔ Running at laravel_echo_server.com on port 6001
✔ Channels are ready.
✔ Listening for http events...
✔ Listening for redis events...

Server ready!

I create a page in my test project with url: http://v5.3.laravel.com/socket

the code of view is here:

@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    test in socket

                    <form class="form-horizontal" name="formSocket" id="formSocket" action="http://laravel_echo_server.com:6001/broadcast?api_key=d26smjrboqgo93e9733ro7l7209r92hq9lsimgqkgiabe7h16llkf5e2kmrf" method="post">
                        <span>姓名：</span>
                        <input class="form-control" name="name" id="name" value="">
                        <br>
                        <span>消息：</span>
                        <textarea class="form-control" name="message" id="message"></textarea>
                        <br>
                        <input class="form-group" type="submit" value="submit">
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

I also added the "<script src="http://laravel_echo_server.com:6001/socket.io/socket.io.js"></script>" in the app.blade.php which I can access the included "socket.io.js" file successfully.

But the issue is when I submit the form, the result is :"{"error":"Unauthorized"}".

The laravel document recommend the packet as websocket server.

Does any know who to fix this or does anyone can recommend a tutorial for "Laravel echo+redis+iosocket" usage?

Thank you

**Comment by clee231** [comment]
The server is requiring the referrer to match where your request is coming from.

For testing, try replacing the `host` line in your `laravel-echo-server.json` file with `*`.  In your example, it would be:
```
"referrers": [
{
"host": "*",
"apiKey": "d26smjrboqgo93e9733ro7l7209r92hq9lsimgqkgiabe7h16llkf5e2kmrf"
}
],
```
This will allow your request to come from any origin.  Of course, you should restrict this again once you move this code into any type of production environment.

Let me know if this helps.

**Comment by tlaverdure** [comment]
Please refer to Laravel documentation on how to setup properly.
