### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by zajinx** [tlaverdure/laravel-echo-server#76]
Hello,
I have a laravel application build around docker (containers: mariadb, php-fpm, nginx, haproxy)
Can anyone help me run laravel-echo-server this inside a docker container? I haven't found to much info around this subject.

Thank you

**Comment by fiveanddone** [comment]
I was able to get this working!

Here's a few pointers for anyone that might still be looking.

My docker-compose file contains this for node container:

> 

    node:
        image: 5ndn/node:7.0
        ports: 
            - 8888:8888
        volumes:
            - .:/usr/src/app
        links:
            - redis
            - web
        command: 'npm start'


You can use whatever you need for your image, but what's important to note is the links and the command.

In your laravel-echo-server.json, you'll want to make sure that "authHost" is set to "http://web/" and if you're using Redis like me, "redis": { "host": "redis" }.  This changes based on the links you provided in your docker-compose file.

My package.json file contains the start script

> 
      "scripts": {
            "start": "laravel-echo-server start"
      }, 

And one more thing...

I ran into was a sqlite error.  The echo server has different dependencies based on if you're running it on a Mac or Linux.  I had to install the proper dependencies via the new container

> 
    docker run -it --rm --name my-running-script -v "$PWD":/usr/src/app 5ndn/node:7.0 npm install sqlite3 --save

I sure hope this helps somebody.
