### ISSUE TITLE
Private Channels not working

### ISSUE THREAD

**Issue by MadScripter** [tlaverdure/laravel-echo-server#8]
Hello, I'm using this package with Redis. When I use normal channels like  `Echo.channel('users').listen('UserSignedUp')` I do receive the event client side, but when I use private channels, nothing happens. Even though I see that the event was fired in the Redis console.

I'm not sure if this is a problem with this package or with Echo itself. I wonder if someone else is having the same issue?

**Comment by tlaverdure** [comment]
Are you using the private() method?

https://laravel.com/docs/5.3/broadcasting#listening-for-events

**Comment by MadScripter** [comment]
Yes I am.

**Comment by hakima** [comment]
My server console shows 

> (Error): 404

>  { url: 'http://homestead.app/broadcasting/auth',
>   form: { channel_name: 'private-chat.1' },
>   headers: { 'X-CSRF-TOKEN': 'viOhMUN9kuKi3o7I8VumOHmwN6fClyx6TJ0BBcnz' } }

**Comment by tlaverdure** [comment]
@MadScripter are you setting up your broadcasting authentication properly in Laravel? The event will be emitted in the Redis console, but you won't be able to listen if you aren't properly authenticated to the private channel.

**Comment by MadScripter** [comment]
Yes I doubled checked everything and it should all be setup correctly. The NodeJS server throws a 302 error everytime I try to broadcast to the private channel :/ The host and the authPath are correct in the options, I even tried to reinstall laravel, but nothing works..

**Comment by jonnywilliamson** [comment]
I know this doesn't help you @MadScripter but I definitely have private channels working using this script, a laravel 5.3 installation and node 5 (see my other comments about this). 

There's obviously just some very small detail that needs to be tweaked.

**Comment by tlaverdure** [comment]
1.0 is now released, please test that version and if this issue exists reopen. Thanks
