### ISSUE TITLE
Laravel Echo Auth With multiple user tables

### ISSUE THREAD

**Issue by rahul-8590** [tlaverdure/laravel-echo-server#81]
Hello,

We have implemented Laravel-echo and tested with public channel it is working perfectly. Using with the private channel it works fine with the default users table. But we need to authenticate the private channel with a different table having different set of users with different table name.  

When using default table as users table it gives and broadcast works perfectly:

>  vt563_4DlitmeC5vAAAH joined channel: private-YoThisIsChannel

If we want to authenticate the users of the different table for the channel it gives:

> Bs3mfFYrKjnO06_7AAAC left channel: private-YoThisIsChannel
> null
> Could not send authentication request.

Broadcastserviceprovider.php
```
Broadcast::routes( [ 'middleware' => [ 'api', 'jwt.auth' ] ] );

        Broadcast::channel('YoThisIsChannel', function ($user) {
            // return (int) $user->id === (int) $userId;
            return $user;
        });
```

**Comment by tlaverdure** [comment]
This seems like something that needs to be handled in your Laravel app. This server has no recollection of the application auth mechanism being used besides a the response that comes back from the Laravel app to verify authentication.

**Comment by msonowal** [comment]
@tlaverdure can you help to right directions what needs to be done in terms of laravel side

**Comment by tlaverdure** [comment]
If you are trying to use a different table for users, the auth guard that you are using needs to be setup to use a different user provider. 

https://laravel.com/docs/5.4/authentication#adding-custom-user-providers

**Comment by msonowal** [comment]
@tlaverdure thanks for your fast reply, actually my mistake that I have not able to describe my question properly.
So I have the below auth guards that is defined for my app `admins, users, other`
and I want every guard to have his own private channel.
So I am defining it in my `channel.php`  with multiple entries for each like below

```
Broadcast::channel('private.admins.{id}', function ($admin, $id) {
    Log::info(class_basename($admin));
    //return (int) $user->id === (int) $id;
});
```
But this is always binding with `User` model class so my question is how do I tell that to use `Admin` model or different model instead of `User`
I am unable to find it anywhere. So can you point me in to right direction

**Comment by ArcadiaS** [comment]
I found my own solution as follows. I hope that will help anyone else.

In App\Providers\AuthServiceProvider.php I coded my own Auth Guard Check function.

```
public function boot()
    {
        $this->registerPolicies();
        Auth::resolveUsersUsing(function ($guard = null) {
            if( is_null($guard) ){
                if( Auth::guard('admin')->check()) return Auth::guard('admin')->user();
                else if( Auth::guard('user')->check()) return Auth::guard('user')->user();
            }
            return Auth::guard($guard)->user();
        });
    }
```

That will return of which 'guard' is that we currently logged but there is a problem here. If there is multiple sessions then the order will be important, Admin > User. You should only have one session at a time.

in Routes\Channels.php;

```
Broadcast::channel('Your_Channel_Name.{parameter}', function ($user, $parameter) {
    Log::info(class_basename($user));  // local.INFO: Admin  
    return true;
});
```

If you have any questions, welcome.

**Comment by devsrv** [comment]
@ArcadiaS thanks a lot, its the best answer for such situation & for little safety I think checking the `user` class is not bad
```
//where App\Admin represent the admin model
Broadcast::channel('some.admin.channel.{id}', function ($user, $id) {
    if(get_class($user) === 'App\Admin' && ((int) $user->id === (int) $id)) {
        return true;
    }
    return false;
});

//where App\User represent the user model
Broadcast::channel('user.channel.{id}', function ($user, $id) {
    if(get_class($user) === 'App\User' && ((int) $user->id === (int) $id)) {
        return true;
    }
    return false;
});
```
you can check by `class_basename($user)` too but I prefer the `get_class($user)` it returns the namespace too
