### ISSUE TITLE
How to use this package just for notification?

### ISSUE THREAD

**Issue by xparthx** [tlaverdure/laravel-echo-server#83]
Hello,

I have a simple blog site. User can comment on blog. I just want to show a simple popup notification to the blog author when someone comments on his blog. 

I have already read this:
https://laravel.com/docs/5.3/broadcasting#introduction

Here is what I did to achieve the task:
1) Setup an event, which gets fired upon new comment
2) Imported: <script src="https://cdn.socket.io/socket.io-1.4.5.js"></script> in blade template
3) Added in, resources\assets\js\bootstrap.js: (as per the Laravel documentation says)
import Echo from "laravel-echo"
window.Echo = new Echo({
    broadcaster: 'socket.io',
    key: 'http://blog.local:6001'
});
4) I have setup this package as per the: https://github.com/tlaverdure/laravel-echo-server#laravel-echo-server
5) Fired command: laravel-echo-server start

When, I open the web browser and check console, I'm continuously getting this errors:
socket.io-1.4.5.js:1 GET http://blog.local/socket.io?EIO=3&transport=polling&t=LZkVvZQ 404 (Not Found)

Here is my "laravel-echo-server.json"
{
	"appKey": "7k2g9nlm6i492ckorlmp35ng4frusfmt4uq1n68usn3re5lcl4sfg3gibi5d",
	"authHost": null,
	"authEndpoint": "/broadcasting/auth",
	"database": "sqlite",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": false,
	"host": "blog.local",
	"port": "",
	"referrers": [],
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}

I think some issues with socket connection.

Any help would be appreciated.

Thanks,
Parth vora

**Comment by tlaverdure** [comment]
Looks like the javascript file is missing the port # in the url which would cause a 404.

**Comment by xparthx** [comment]
Can you please give some more detail?

Are you talking about the javascript file which contains Echo instance? If yes then port is already there as I written above: (i.e 6001)

import Echo from "laravel-echo"
window.Echo = new Echo({
broadcaster: 'socket.io',
key: 'http://blog.local:6001'
});

Or are you talking about the json file(laravel-echo-server.json)? I have tried all the possible permutation I could in both the files but still giving the same error.

Thanks
