### ISSUE TITLE
Any PUBLISH command in Redis from other program broke laravel-echo-server

### ISSUE THREAD

**Issue by kashtanoff** [tlaverdure/laravel-echo-server#85]
Any PUBLISH command in Redis from other program broke laravel-echo-server

```
SyntaxError: Unexpected token d in JSON at position 0
    at Object.parse (native)
    at Redis.<anonymous> (C:\Users\Иван\AppData\Roaming\npm\node_modules\laravel-echo-server\dist\subscribers\redis-subscriber.js:13:32)
    at emitThree (events.js:116:13)
    at Redis.emit (events.js:194:7)
    at Redis.exports.returnReply (C:\Users\Иван\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\ioredis\lib\redis\parser.js:110:14)
    at ReplyParser.replyParser.sendReply (C:\Users\Иван\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\ioredis\lib\redis\parser.js:25:10)
    at ReplyParser.execute (C:\Users\Иван\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\ioredis\lib\parsers\javascript.js:175:14)
    at Socket.<anonymous> (C:\Users\Иван\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\ioredis\lib\redis\event_handler.js:94:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

**Comment by vesper8** [comment]
having the same issue.

So I made sure that the other parts of my application that are publishing to redis are doing so on a different database then the one laravel-echo-server listens to.

I've confirmed that this is working too using RedisDesktopManager. All my other redis publishes are doing on db1 and laravel-echo-server is set to work with db0 only

```
        "databaseConfig": {
                "redis": {
                        "host": "localhost",
                        "port": 6379,
                        "db": 0
                }
        },
```

Yet even after those changes.. and confirming that nothing is being pushed on db0.. it still crashes every time a publish is made to db2

why is that?

Also on another note... I wanted to have laravel-echo-server work on db1 (or dbX)  but I don't actually have any idea how to make regular event broadcasting push to another connection other than "default". If anyone can shed light on how to do that I would appreciate it. But this is unrelated to the issue above.

**Comment by kashtanoff** [comment]
I use Redis Keyspace Notifications in this database for observe changes in redis keys (for observe online users on channels and run callback if user offline). Redis generate no JSON events and broke laravel-echo-server.

**Comment by vesper8** [comment]
I DO publish non-json to redis channels in my application and I believe this is what's breaking laravel-echo-server.

There's a pull request to wrap that part in a try/catch to prevent this kind of breakage
https://github.com/tlaverdure/laravel-echo-server/pull/86

However there's an underlying problem which is that laravel-echo-server should not break when something gets pushed on db1 if it is set to listen to db2

I think I am setting the configuration json incorrectly.

```
        "databaseConfig": {
                "redis": {
                        "host": "localhost",
                        "port": 6379,
                        "db": 2
                }
        },
```

This seems to do nothing.

Looking at https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options

It seems that the db should be under it's own "options" object.. so something like this?

```
	"databaseConfig": {
		"redis": {
			"host": "localhost",
			"port": 6379,
			"options": {
				"db": 2
			}
		}
	},
```

That still isn't working.. still breaks when I publish something to db1

**Comment by vesper8** [comment]
hrm.. I understand that the try/catch will prevent events lacking json from breaking the server. But isn't there an underlying problem here that was causing it to listen on ALL redis databases even though it should only have been listening on the one the config specified?

I am in the process of creating a 2nd instance of redis running on a different port to avoid this issue. Seems like the try/catch hotfix will just become a performance hit as laravel-echo-server will continue to listen where I think it shouldn't be listening. Unless I'm missing something here.. I never did get laravel-echo-server to work because I can't get it to listen to db2 only

**Comment by kashtanoff** [comment]
This is no laravel-echo-server problem.

Laravel use redis Pub/Sub for broadcast events(https://redis.io/topics/pubsub).

In redis docs: 

```
Pub/Sub has no relation to the key space. It was made to not interfere with it on any level, including database numbers.
Publishing on db 10, will be heard by a subscriber on db 1.
If you need scoping of some kind, prefix the channels with the name of the environment (test, staging, production, ...).
```

Fo resolve this problem you can try change `this._redis.psubscribe('*', (err, count) => {` to 
`this._redis.psubscribe(___SOME_PREFIX_FROM_CONFIG__'*' in /src/subscribers/redis-subscriber.ts , (err, count) => {` and use ___SOME_PREFIX_FROM_CONFIG__ as prefix fo all you channels in laravel application

**Comment by vesper8** [comment]
@kashtanoff Thanks for the explanation! That makes complete sense now. I am going to just use different instances with different IPs to prevent this from happening.

However now that we've narrowed down the problem and have described a solution. Maybe it would be good to add an optional "channel prefix" option to laravel-echo-server so that there isn't a need to modify a vendor file?
