### ISSUE TITLE
Ios/android auto reconnect? 

### ISSUE THREAD

**Issue by barryvdh** [tlaverdure/laravel-echo-server#90]
I'm not sure if this is an socket.io issue or echo, but I can't seem to get reliable connections after even a short time of being idle, eg on a mobile app and going to standby or a different app. 

Is there something I need to change or something you can recommend? Otherwise it's working great, but I need to reconnect (directly) on getting back online to receive new messages..

**Comment by tlaverdure** [comment]
I'll need to test this out to be certain but socket.io is supposed to reconnect automatically. So this may be a scenario where the authentication process from echo needs to happen again when your app goes from background to foreground.

**Comment by barryvdh** [comment]
But that would be just for private channels, right?
I tested, but it doesn't seem to make a difference if it's public or private.

Android does seem to behave a bit better, at least for short idle time, but iOS just doesn't seem to reconnect, at least not within a minute.

**Comment by barryvdh** [comment]
So this is what I can see happening after I set my iPad to standby, using the socket.io debug info

- WebSocket connection failed; failed to send frame (correct, iOS stops this in standby)
- engine.io: transport error
- socket.io client manager: onclose, cleanup, close (transport error), reconnect attempt.
- Opens http://..:6001, does XHR poll, get 'xhr data null'
- Sets tansport polling, socket is open, reconnect success event.
- More xhr polls with data null, receive data "0" type "message" from socket.
- Opened transport "websocket", pong, polling, waiting, got ArrayBuffer, received type "noop", data "undefined"
- Al lot of pongs received, flushing 1 packets etc, but no events.

So it seems that the connection is indeed restored, but it just doesn't receive any events after reconnect. Any thoughts on why this could happen? Do we need to subscribe again?

**Comment by barryvdh** [comment]
Same happens the other way around. When I just quit the server and restart it, it does see the Events but no clients reconnect again. 

Am I doing something wrong or do I need to configure something?

**Comment by jonnywilliamson** [comment]
I can't offer any help to you to solve this, but just registering here as being very interested in this issue.

**Comment by barryvdh** [comment]
Do you experience the same behavior?

**Comment by jonnywilliamson** [comment]
At the moment the app I'm making is still at the start/developing phase and all my testing has been on computer (which hasn't shown any of these issues), about to start testing on mobile devices later on this week or next week.

I just spotted this issue and wanted to mark it in case I come across the same problem.

**Comment by DigitalCakeNZ** [comment]
On multiple mobile browsers this is the case for me also.

**Comment by barryvdh** [comment]
@jonnywilliamson You can try it simple with:

Testcase Server disconnect
 - Run the server
 - Open the webpage, see that events are working
 - Kill the server (ctrl+c), wait 30 sec
 - Restart the server

Testcase Client disconnect
 - Run the server
 - Open the webpage in Safari on iPad
 - Go to standy, wait 30 sec
 - Turn back on

In my case it didn't show any new connections and didn't receive events anymore.

**Comment by barryvdh** [comment]
Okay I've also enabled server debug info (`DEBUG=* /usr/local/bin/laravel-echo-server start`) and saw that on reconnects, the subscribe isn't done. This is happening on the client-side, so might be an Echo issue?

This seems to work (with above testcases, not extensively tested)

```js
var socket = window.Echo.connector.socket.io;
var channel = window.Echo
                .channel('test')
                .listen('StatusUpdated', function (e) {
                    console.log(e);
                })

socket.on('reconnect', function(){
    console.log('reconnect');
    channel.subscribe();
})
```

This will emit a subscribe event to the server using the (new) socketId. Not really sure if I should also unsubscribe from the old one.

Is this an issue with the laravel/echo (client-side) package and do I need to open an issue there? Or do you need to detect the reconnect on the server and subscribe automatically?

**Comment by tlaverdure** [comment]
I'm seeing the same thing. Think we need to add a reconnect event handler that reconnects with Laravel.

**Comment by barryvdh** [comment]
Here on or Laravel? I can create a PR with this:
https://github.com/laravel/echo/commit/b2443516b599057ff3a623e7d2fc2ce5b892b10c

**Comment by tlaverdure** [comment]
I think that should do it. Looks like the reconnect event is client side.

**Comment by barryvdh** [comment]
PR submitted, please test and review :)

**Comment by barryvdh** [comment]
Should be fixed with `laravel-echo@1.1.4`, released half hour ago.

I do think that you need to think about CSRF protection, because those will expire while you can still be logged in with cookies. So either long lived sessions or disable CSRF protection on `/broadcasting/auth`?

**Comment by tlaverdure** [comment]
@barryvdh we need to keep CSRF protection available but maybe we could create an option to to disable CSRF if that is your preference. You could also use  long lived sessions or JWT for your mobile apps.

**Comment by barryvdh** [comment]
CSRF don't need to disabled here, you could just disable in the your Laravel route middleware.

Using JWT tokens isn't really possible by default, using standard laravel-echo, is it?

**Comment by tlaverdure** [comment]
Ok, and you are right, not by default but it is possible by adding an auth header when you instantiate laravel-echo with headers [options.auth.headers](https://github.com/laravel/echo/blob/master/src/connector/connector.ts#L12) i.e. `Authorization: Bearer ejxnahdnaf.1241hnaefnmasf....` which should be passed to the SocketIoConnector.

I've tested that much, but think there needs to be an additional method on the connector that exposes a way to update the headers before you attempt subscribe to a channel.

**Comment by barryvdh** [comment]
Setting custom auth headers would not effect the CSRF protection affected by all POST requests, but would indeed be nice for long lived sessions.
