### ISSUE TITLE
Events on failures (no authentication, csrf token etc)

### ISSUE THREAD

**Issue by barryvdh** [tlaverdure/laravel-echo-server#91]
Is it possible to throw some sort of error event we can listen to, to react on certain errors? For example when subscribing to a channel without permission, user has been logged out, csrf token is not valid etc.
Then we can show a message or reload the page / send to login.

**Comment by tlaverdure** [comment]
@barryvdh I think so. Let me test something out...

**Comment by barryvdh** [comment]
Closing in favor of #103
