### ISSUE TITLE
Http Subscriber example

### ISSUE THREAD

**Issue by barryvdh** [tlaverdure/laravel-echo-server#92]
So there is an HTTP subscriber, which would avoid having to use Redis at all right? 

You describe the payload here: https://github.com/tlaverdure/laravel-echo-server#http
But don't really mention the Authorization header.

Is there an example HttpBroadcaster? Should that be added to Laravel, or just add it to the example directory here?
(coming from https://github.com/laravel/internals/issues/332 to simplify setup)

**Comment by tlaverdure** [comment]
Yes this method does not require Redis. It was just a small idea that I had, and didn't think to create a HttpBroadcaster. My intention was to add the ability to send events from anywhere, even outside of Laravel. Which could be useful if you want to broadcast events that you don't plan on retaining in your db.

**Comment by barryvdh** [comment]
@tlaverdure Can you email me on barryvdh at gmail ? Want to discuss something related and can't find your email.

**Comment by barryvdh** [comment]
What perhaps also would be cool for the Http server, get some statistics about your socket, eg:

`GET /count`: `this.io.engine.clientsCount`
`GET /rooms`: `this.io.sockets.adapter.rooms`
`GET /rooms/<channel>`: `this.io.sockets.adapter.rooms[<channel>]`

So you can get sort of like a dashboard or statistics using HTTP requests.
