### ISSUE TITLE
can't leave a channel [question]

### ISSUE THREAD

**Issue by lengas** [tlaverdure/laravel-echo-server#98]
When I connect to 11 channels, the server outputs this message:

> Possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit

I don't know if this is a problem.
I always leave current channel before connect to a new channel using:

`Echo.leave('name-of-the-channel');`

I googled this message and found that node is not removing the listener from the old channel listener.

Another question I have is why every time I connect to a channel the server otputs something like this:

> [00:39:47] - 8BjTHoFwnNaywF7JAAAI left channel: private-chat-conversation.22
[00:39:47] - 8BjTHoFwnNaywF7JAAAI joined channel: private-chat-conversation.22

First "left channel" is fired (never joined the channel before) and then "joined channel" is fired. Is normal?
Also when I run `Echo.leave` function nothing happens and there isn't any message from the server.

**Comment by barryvdh** [comment]
The last part is fixed by this: https://github.com/tlaverdure/laravel-echo-server/pull/97

**Comment by barryvdh** [comment]
I think the second part is because the disconnect listener is not removed on unsubscribing (leaving on client-side). See https://github.com/tlaverdure/laravel-echo-server/pull/97#issuecomment-272657288
Should now also fix this.
