### ISSUE TITLE
Getting continuously socket.io/?EIO=3&transport=polling 404 

### ISSUE THREAD

**Issue by xparthx** [tlaverdure/laravel-echo-server#99]
Hello, 

I have a simple blog site where the user can comment on the blog. I just want to show a simple popup notification to the blog author when someone comments on his blog.

I have already read this:

https://laravel.com/docs/5.3/broadcasting#introduction

Here is what I did to achieve the task:

1) Setup an event, which gets fired upon new comment

2) Imported:

`<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>`
in blade template

3) Added in, resources\assets\js\bootstrap.js: (as per the Laravel documentation says)

```
import Echo from "laravel-echo"
window.Echo = new Echo({
    broadcaster: 'socket.io',
    key: 'http://blog.local:6001'
});
```
4) I have setup this package as per the: https://github.com/tlaverdure/laravel-echo-server#laravel-echo-server

5) Fired command: laravel-echo-server start

When, I open the web browser and check console, I'm continuously getting this errors:

`socket.io-1.4.5.js:1 GET http://blog.local/socket.io?EIO=3&transport=polling&t=LZkVvZQ 404 (Not Found)`
Here is my "laravel-echo-server.json"

```
{
    "appKey": "7k2g9nlm6i492ckorlmp35ng4frusfmt4uq1n68usn3re5lcl4sfg3gibi5d",
    "authHost": null,
    "authEndpoint": "/broadcasting/auth",
    "database": "sqlite",
    "databaseConfig": {
        "redis": {},
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        }
    },
    "devMode": false,
    "host": "blog.local",
    "port": "6001",
    "referrers": [],
    "socketio": {},
    "sslCertPath": "",
    "sslKeyPath": ""
}
```
I think some issues with socket connection.

Let me know, if anyone needs some more info.

Note:

I'm not sure that, do I really need this package for my purpose or not. I just installed it because it was mentioned on Laravel's documentation. As I said I just need real time popup notification.

Any help would be appreciated.

Thanks

**Comment by KekoApp** [comment]
Hey, without seeing the rest of your code I can't say this will get it
working.

It looks like it's not specifying a port on the connection. That URL should
look like this:

 http://blog.local:6001/socket.io?EIO=3&transport=polling&t=LZkVvZQ

This is perhaps something to do with your local setup and it's ports?

**Comment by barryvdh** [comment]
Are you actually setting `key`? You need to set the `host`. See the Socket.IO section: https://laravel.com/docs/5.3/broadcasting#driver-prerequisites

**Comment by xparthx** [comment]
@barryvdh, yes you are right. I also figure out that later and that solved that issue.
However, I'm still not able to get it completely working.

So far I have done this:

Controller action:
```
broadcast(new NewVote());
event(new NewVote()); // Also tried this
```

"NewVote" Event class:
```
public function broadcastOn()
    {
        return new Channel('new-vote');
    }
```

Javascript:
```
import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://assessment.local:6001'
});

window.Echo.channel('new-vote')
    .listen('NewVote', (e) => {
        console.log(e);
    });
```

laravel-echo-server.json
```
{
    "appKey": "0p4o9t942ct15boc4nr8tjb178q29fdmlcat8c1p1s51i2pbq9nmtjud94t4",
    "authHost": null,
    "authEndpoint": "/broadcasting/auth",
    "database": "redis",
    "databaseConfig": {
        "redis": {},
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        }
    },
    "devMode": true,
    "host": "assessment.local",
    "port": "6001",
    "referrers": [],
    "socketio": {},
    "sslCertPath": "",
    "sslKeyPath": ""
}
```
Already this commands are running:

```
laravel-echo-server start
php artisan queue:work
php artisan queue:listen
gulp watch
```
All I'm expecting a console massage when, I fire the event. But I'm not getting anything on the console.

Let me know if any other information needed.

Note: My socket.io server is running successfully without any error.

Thanks,
Parth Vora

**Comment by barryvdh** [comment]
And you are using the redis broadcaster? Do you see events getting triggered in your queue listener?

**Comment by xparthx** [comment]
I'm using MySQL as datatabase. I have nothing to do with redis or sqlite. (Its redis in configuration as default)So I'm not sure that should I use this package or not. All I want to do is to get the notification at front end when Laravel fires the event. 

No, I don't see anything on queue listener.

**Comment by barryvdh** [comment]
Currently there is only a redis subscriber + simple http subscriber (no example broadcaster yet). But when https://github.com/tlaverdure/laravel-echo-server/pull/95 is merged, you could use the Pusher subscriber. Right now, you need to setup a redis broadcaster.

**Comment by tijme** [comment]
I think

`
import Echo from "laravel-echo"
window.Echo = new Echo({
    broadcaster: 'socket.io',
    key: 'http://blog.local:6001'
});
`

Must be

`
import Echo from "laravel-echo"
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://blog.local:6001'
});
`
